### ISSUE TITLE
Worker builds hang when running with debug error logging

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#100]
@chefsalim commented on [Tue Jan 23 2018](https://github.com/habitat-sh/habitat/issues/4483)

When turning on debug log (eg, on acceptance), the build worker builds are hanging.

This is because we are stalling on the log pipe in the runner:

cmd.stderr(Stdio::piped());

We need to find a better solution to piping stderr output in the runner.

**Comment by fnichol** [comment]
Resolved when habitat-sh/builder#210 merges
