### ISSUE TITLE
Builder Event Notifications

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1000]
User story:
As an internal or external user, I can subscribe to notifications of selected events in the Builder workflow, and use these events to build custom integrations and workflows that are specific to my organization or use case.

Acceptance Criteria:
1. Notifications can be subscribed to at the origin level
2. Notification subscription includes specific events of interest
3. Notification events can be specified at an origin or origin/package level
4. Notification subscription includes an endpoint for notifications to be delivered to
5. Subscription endpoint will be an http endpoint initially, but should not preclude being an email address or other transport in the future
6. An API is provided to create/edit/delete configuration for notifications
7. Notifications are sent in a reasonable, timely manner to the subscriber
8. On failure to send, notifications may be retried N times (N >= 0)
9. Notifications have an ordering mechanism
10. Notifications are secured appropriately

Proposed Events:
  * Build group status — build status for any build group that was triggered by a plan in “myorigin"
  * Build status (individual package) — build status change of any package in “myorigin"
  * Build group promotion/demotion — promotion change for any build group that was triggered by a plan in “myorigin”
  * Package promotion/demotion — any package in “myorigin"
  * Package upload — any package uploaded to “myorigin”
  * Dependent package promotion/demotion — promotion change for any package that a plan in “myorigin” depends on

Aha! Link: https://chef.aha.io/features/APPDL-15

**Comment by baumanj** [comment]
> * Subscription endpoint will be an http endpoint initially, but should not preclude being an email address or other transport in the future

Should we require `https`?

Also, would it make sense to have an event for origin key changes?

**Comment by chefsalim** [comment]
Good points @baumanj ... endpoint should be https by default (and allow option for http for testing/etc)
Origin key notifications haven't come up in prior discussions, but could be good ones to have as well

**Comment by eeyun** [comment]
This isn't stale so I'm leaving a comment here to appease fascist-bot

**Comment by sajjaphani** [comment]
This isn't stale
