### ISSUE TITLE
Generate personal access tokens via Habitat Builder

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#101]
@ryankeairns commented on [Tue Jan 23 2018](https://github.com/habitat-sh/habitat/issues/4484)

This work is related to the near-term objective of switching to use Habitat generated personal access tokens. It will require both backend/API changes in addition to UI work to generate/copy/regenerate/delete your access token (on your profile).

The UI feature work and flow can be viewed in this Invision prototype:
https://chef.invisionapp.com/share/C5E6NIURX#/261858081_profile

---

@ryankeairns commented on [Tue Jan 23 2018](https://github.com/habitat-sh/habitat/issues/4484#issuecomment-359927681)

![profile-token](https://user-images.githubusercontent.com/446285/35300275-8f845226-004d-11e8-998d-674a2a59f6bc.gif)

**Comment by chefsalim** [comment]
Pushed to live - closing
