### ISSUE TITLE
Ability to filter "sandbox" channels from install attempts

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/builder#1010]
### Describe the Enhancement:

When performing a `hab pkg install`, the user should be able to avoid iterating through all the sandbox channels associated with the `pkg_name`. 

### Describe the Need:

[What kind of user do you believe would utilize this enhancement, and how many users might want this functionality]

### Current Alternative
[Is there a current alternative that you can utilize to workaround the lack of this enhancement]

### Can We Help You Implement This?:
[The best way to ensure your enhancement is built is to help implement the enhancement yourself. If you're interested in helping out we'd love to give you a hand to make this possible. Let us know if there's something you need.]

**Comment by raskchanky** [comment]
Hmm.  I _think_ we're doing this today, but I'm probably missing the context around what you're describing.  [Here](https://github.com/habitat-sh/habitat/blob/master/components/common/src/command/package/install.rs#L1025) is the logic for retrieving the list of recommended channels when installing a package.  Note the last argument to `list_channels()` is `false`, which [should filter the sandbox channels out](https://github.com/habitat-sh/habitat/blob/master/components/builder-api-client/src/lib.rs#L1088-L1090).  What am I missing?

**Comment by tduffield** [comment]
@raskchanky how are sandbox channels defined? Specifically, we have a bunch of custom sandbox channels (`buildkite-UUID`) that we want to filter.

**Comment by raskchanky** [comment]
Ahhh, _that's_ the piece I was missing.  Sandbox channels are defined internally as channels that Builder automatically generates when doing a build, prefixed with `bldr-`.  Your request makes a lot more sense now.
