### ISSUE TITLE
Update Terraform for new ACM certs

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1012]
Need to update Terraform for our new cert management for builder-<env>.habitat.sh
We have migrated over to using the Amazon Certificate Manager (ACM).

**Comment by mivok** [comment]
There are two possible approaches here:

1. There is an ssl_certificate_arn variable in the terraform configuration. Simply setting this to the ARN of the new certificate (look this up in the AWS web console in the ACM section) will be sufficient. I couldn't see from a quick look where this was set, but it appears to be something updated outside of this repository.
2. Add the following code (or similar) which will look up the ARN of the ACM certificate dynamically:
    ```
    data "aws_acm_certificate" "habitat_cert" {
      domain      = "*.habitat.sh"
      types       = ["AMAZON_ISSUED"]
      most_recent = true
   }
    ```
    and replace any instances of `${var.ssl_certificate_arn}` with `${data.aws_acm_certificate.habitat_cert.arn}`, also removing the variable definition.
