### ISSUE TITLE
[builder-worker] Provision additional studio network interface at boot time

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/builder#102]
By attaching the additional network interface at boot/provision time, the worker (and by extension the Airlock networking) will be guaranteed to have its networking before the service starts. This is in contrast to the current state where the additional network interface is "hot" attached after the worker instance is completely provisioned.

**Comment by nellshamrell** [comment]
It looks like this was addressed in http://github.com/habitat-sh/builder/issues/125, so I'm going to close this for now.  If you are still seeing this issue, please feel free to re-open :)
