### ISSUE TITLE
Unpin actix

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#1035]
As part of the `cargo update` required to make builder pull the `core` crate from the `habitat` repo, actix got upgraded to `0.8.1` and subsequently started panicking every time `builder-api` or `builder-jobsrv` started up.  I spent a few hours trying to track it down but was ultimately unsuccessful.  In the interest of time, I pinned the version for `builder-api` and `builder-jobsrv` to `0.7.9` but it'd be good to track down what the actual issue was and unpin actix for those 2 crates.

https://github.com/habitat-sh/builder/pull/1028

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/1110 and other PRs
