### ISSUE TITLE
Improve the UX of the package visibility API

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#1043]
Right now, if you want to toggle the visibility of a package, you need to use the FQPI, e.g.

```
curl -v \
-X PATCH \
-H "Accept: application/json" \
-H "Authorization: Bearer $HAB_AUTH_TOKEN" \
https://bldr.habitat.sh/v1/depot/pkgs/core/redis/3.2.4/20170215222111/private
```

This is terrific if you want to toggle the settings on just that specific release of `core/redis`, but what if you wanted to toggle the visibility on every release of `core/redis/3.2.4`, or even *gasp* every version and release of `core/redis`?  Then you're stuck writing some shell scripts to cobble everything together.

What would be delightful from a UX perspective is to be able to do something like

```
curl -v \
-X PATCH \
-H "Accept: application/json" \
-H "Authorization: Bearer $HAB_AUTH_TOKEN" \
https://bldr.habitat.sh/v1/depot/pkgs/core/redis/3.2.4/private
```

as well as

```
curl -v \
-X PATCH \
-H "Accept: application/json" \
-H "Authorization: Bearer $HAB_AUTH_TOKEN" \
https://bldr.habitat.sh/v1/depot/pkgs/core/redis/private
```

It's possible these routes as written would conflict with existing routes, so don't take it as is verbatim (although if the routes are type-safe, they might be fine).  They're just to illustrate the point.

**Comment by jtimberman** [comment]
This is related to #1042 ;)
