### ISSUE TITLE
Build groups getting randomly stuck in 'Dispatching' state

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1068]
### `hab` CLI version
v0.81.0

### Scenario:
While investigating an issue of a build group not being appropriately queued in builder today we discovered a handful of `groups` that were stuck in the `Dispatching` state. Some of these have been stuck in this state for more than a month.

### Steps to Reproduce:
We don't know why these jobs are getting pinned in this state but there are still a handful of groups like this that can be viewed on the live datastore node with the query:
```
builder=# select * from groups where group_state = 'Dispatching';
```

### Expected Result:
We expect that when a job is hung in a Dispatching state like this if there is no failure and no progress the job is instead converted to a state of 'Canceled'.

### Actual Result:
Most of the time this appears to be working correctly. However some jobs appear to never get cleaned up.

**Comment by mwrock** [comment]
closed by #1104
