### ISSUE TITLE
Some jobs stuck in `queued` state

### ISSUE THREAD

**Issue by bixu** [habitat-sh/builder#1072]
### `hab` CLI version
```
hab --version
hab 0.81.0/20190507225652
```

### Platform Details
Public Builder

### Scenario:
I've configured automatic builds for the `smartb/pandas` package, but they don't fire from the CLI or UI or Github push.

### Steps to Reproduce:
```
hab bldr job start smartb/pandas
hab bldr job status 1252033949755482112
☁ Determining status of job group 1252033949755482112

CREATED AT                        GROUP ID             STATUS  IDENT          TARGET
2019-05-22T10:17:48.640344+00:00  1252033949755482112  Queued  smartb/pandas  x86_64-linux

```

### Expected Result:
Since the Plan is just download and re-package of a Pip module, I expect the build to finish in 5 or so minutes.
### Actual Result:
Job stays stuck in "queued" state. The previous stuck job was _months_ old, surprisingly.

Please feel free to Slack me directly about this, as it's blocking some work of ours.

**Comment by chefsalim** [comment]
@bixu You should be able to cancel the old job either from the UI, or from the cli with a 'hab bldr job cancel' command.  Once the old job is cancelled, the newly queued job should resume.

**Comment by bixu** [comment]
@chefsalim, yeah that's what we did. However, we're still unable to see any auto build jobs created for this particular package. We also can't trigger a manual build from the UI. (The package in question is as https://bldr.habitat.sh/#/pkgs/smartb/pandas/jobs )

**Comment by chefsalim** [comment]
I've manually cleared the stuck build.  Please re-open if this repros - thanks!
