### ISSUE TITLE
core/drush packages seem to be incorrectly missing

### ISSUE THREAD

**Issue by james-stocks** [habitat-sh/builder#1093]
### `hab` CLI version
hab 0.82.0/20190605214029

### Scenario:
Building `core/drupal` results in this failure:

```
★ Install of core/mysql-client/5.7.21/20190305213913 complete with 6 new packages installed.
   drupal: Resolved dependency 'core/mysql-client' to /hab/pkgs/core/mysql-client/5.7.21/20190305213913
» Installing core/drush
☁ Determining latest version of core/drush in the 'stable' channel
✗✗✗
✗✗✗ Package not found.
✗✗✗
   drupal: WARN: Could not find a suitable installed package for 'core/drush'
   drupal: ERROR: Resolving 'core/drush' failed, should this be built first?
   drupal: Build time: 0m15s
   drupal: Exiting on error
```

In the bldr UI, it appears that there are no packages for core/drush:
https://bldr.habitat.sh/#/pkgs/core/drush/latest

> There are no available Habitat artifacts (.hart files) for this origin/package.

However clicking the build jobs for this package shows completed builds in the stable channel e.g. https://bldr.habitat.sh/#/pkgs/core/drush/jobs/1257965619359449088

### Steps to Reproduce:

Clone [core-plans](https://github.com/habitat-sh/core-plans) and run `hab pkg build drupal`

**Comment by chefsalim** [comment]
Looks like the regex pattern matching we are doing for the latest package is failing for the case where the version is only a single digit number - eg, "8" for drush.
