### ISSUE TITLE
Malformed ident in package deps can cause scheduler thread to panic

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/builder#1095]
In a recent incident, the scheduler thread panicked at https://github.com/habitat-sh/builder/blob/814573abb3404dd15bb9a77fb8445076c9c63b1e/components/builder-jobsrv/src/server/scheduler.rs#L405 which was called from https://github.com/habitat-sh/builder/blob/814573abb3404dd15bb9a77fb8445076c9c63b1e/components/builder-jobsrv/src/server/scheduler.rs#L269,

**Comment by baumanj** [comment]
At the very least, it would be good to change that `unwrap` to an `expect` so we can get more useful information even when running in a release build.
