### ISSUE TITLE
Add platform switcher to packge details page - latest tab

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/builder#1098]
### Describe the Enhancement:
As described in issue https://github.com/habitat-sh/builder/issues/825 and https://github.com/habitat-sh/builder/issues/948, currently there isn't a way for users to target builds or view the package manifest for a specific platform of a given package. Adding a platform switcher in the package details page - latest tab will help resolve the two issues at once.

### Describe the Need:

- _For all users across Builder UI_: when there are multiple platforms available for a package, a user can use the switcher to view the different manifests and plans for different platforms, as well as the "latest stable" content (no "supported platforms") on the right side panel.
- _As an owner or member of an Origin for a package_: when there are multiple platforms available for a package, a user can use the switcher to target new build for different platforms. By selecting a specific platform, a user can not only see its corresponding manifest, plans, and the "latest stable" content,  but also the build settings and the "Build latest version"  button. The button will only trigger builds on the single selected platform among the switcher. E.g. if a user selects the "windows" platform and is seeing the windows package manifest, the "Build latest version" will only build the windows package. 

### Acceptance Criteria:

- [ ] Remove the "support platforms" content for all users across all packages
![image](https://user-images.githubusercontent.com/9401459/59643582-14788580-911e-11e9-811e-26189c9dded1.png)
- [ ] When there is more than one platform available for a package, display the platform switcher. The platform switcher contains all platforms that are available, with the first option from the left selected by default. The sequence for all possible platforms from left to right are: Linux, Linux 2, Windows, and macOS. 
- [ ] The name of the selected platform should be included in the URL. e.g. https://bldr.habitat.sh/#/pkgs/core/7zip/linux/latest
- [ ] Switching the selected platform will update all the content on the `latest` tab, including the package manifest, plan details, build button and setting. The availability of the build button and settings depends on the role of the users as described in the "describe the need" part.
- [ ] The build button label is defined as `{selected-platform-icon} Build latest version`. Only one platform can be selected at a time.
**Accessibility**: hide the entire label including the icon from screen readers and then have an aria-label of `Build latest <platform-name> version`
**Note**:  in the future, if we add the `All` option in the platform switcher under the `versions` tab, the build button label changes to `Build all latest versions` with no icons
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/edea823e-ddb9-4cf8-b258-89b17c6664f9)
- [ ] For macOS packages, show the `{macOS-icon} Build latest version` button in `disabled` state, with a message below explains "Builder couldn't build the package because a macOS Plan file is not supported yet. Stay tuned." ([View mockup](https://chef.invisionapp.com/share/SHRQ64L67WG#/screens/360329093))
- [ ] For packages that don't have a plan connected for a specific platform, show the `{selected-platform-icon} Build latest version` button in `disabled` state, with a message below explains "Builder couldn't build the package because there is no {platform name} Plan file." In the future, we will add separate settings for different platforms in another issue.
([View mockup](https://chef.invisionapp.com/share/SHRQ64L67WG#/screens/360329094))

### UX Design:

- [Clickable prototype](https://chef.invisionapp.com/share/SHRQ64L67WG#/screens/360329095)
- [Design spec (inspect link)](https://chef.invisionapp.com/d/main#/console/17374423/360329095/inspect)
Whoever works on the UI development part, ask me to add you to the InVision project to view the design spec.

#### Style Change note
After discussing with Scott Christopherson, we came to an agreement on a style change for the switcher and a few other visual details. The updated mockup looks like [this](https://chef.invisionapp.com/share/SHRQ64L67WG#/377018864_v4-Package_Detail_-_Platform_Switcher_-_Linux). The interaction pattern still follows what's in the clickable prototype.

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/1148
