### ISSUE TITLE
Clicking on a version to see the actual artifacts takes a long time.

### ISSUE THREAD

**Issue by bdausses** [habitat-sh/builder#1113]
### `hab` CLI version
N/A - UX issue

### Platform Details
N/A - SAAS bldr.habitat.sh UX issue

### Scenario:
Browsing packages and looking at available artifacts takes a long time.  This might be load related.

### Steps to Reproduce:
Go here:  https://bldr.habitat.sh/#/pkgs/core/7zip and click on 16.02...  That section takes a crazy long time to actually expand.

### Expected Result:
That section should drop down in a much more time sensitive manner.

### Actual Result:
It takes 9 or 10 seconds to drop down.

**Comment by chefsalim** [comment]
Related - https://app.zenhub.com/workspaces/core-repos-57e1e83308ec936f021c876a/issues/habitat-sh/builder/535

**Comment by danielcbright** [comment]
I'm experiencing this issue too, not only with core packages, but private origins as well. I can share package details if needed.
