### ISSUE TITLE
Create Origin via CLI

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1129]
### Describe the Enhancement:
Allow creation of origins via the `hab` cli.

### Describe the Need:
Any user that prefers to use the CLI over logging into the front-end would likely use this feature. We also have need of similar origin behaviors via the CLI, for example: https://github.com/habitat-sh/builder/issues/1014

This work would also simplify the workflow for users with on-prem builder services. It is necessary to fully support automated installation and configuration of those builder services.

### Current Alternative
Currently the only way to create an origin is via the UI or a curl command.

**Comment by chefsalim** [comment]
This work is already done - https://github.com/habitat-sh/habitat/commit/65465b443e846ef02946461240fd04b61107ec10#diff-234c005e746f9d09ab10ad8a6b974874
