### ISSUE TITLE
Bitbucket Oauth Failures

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1132]
### Scenario:
Cannot sign in to builder UI when bitbucket is configured as the Oauth identity provider. Failure on login, unable to authenticate.

### Steps to Reproduce:
Configure Oauth to use bitbucket.
Click sign-in button.

### Expected Result:
This should work!

### Actual Result:
Unable to authenticate.

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/1130
