### ISSUE TITLE
New builds not triggered with plans and build paths in bldr.toml

### ISSUE THREAD

**Issue by adamhjk** [habitat-sh/builder#1140]
### Platform Details
AWS, Github 

### Scenario:
With a private repo in si/si-graphql, I have a plan connected in builder. When the code (not the plan) in the repo updates, a new build is not triggered.

### Steps to Reproduce:
* Enable a build on a repo with multiple plans
* Connect the plans to builder
* Have a `.bldr.toml` in the root with:

```
[si-graphql]
plan_path = "components/si-graphql"
paths = [ "components/si-graphql/*" ]
```

* Push a commit to `components/si-graphq/README.md`, or whatever, and watch the build not be triggered.

### Expected Result:
The build should be triggered. :)

### Actual Result:
The build is not triggered.

**Comment by chefsalim** [comment]
The issue here was that the plan was in a "habitat" subfolder but the plan path did not point directly to it. Leaving this issue open to add better documentation and logging
