### ISSUE TITLE
Windows packages in the stable channel do not appear as "Latest Stable"

### ISSUE THREAD

**Issue by robbkidd** [habitat-sh/builder#1144]
### Platform Details

Windows packages in https://bldr.habitat.sh/. Page footer there reports `habitat/builder-api-proxy/8390/20190618004855` at the time this issue is being opened.

### Scenario:

I expect to see packages listed as stable, but I don't see them for when the package platform is Windows.

For example: 
https://bldr.habitat.sh/#/pkgs/core/dotnet-472-runtime/latest says:

> **There are no available Habitat artifacts (.hart files) for this origin/package.**

The "Versions" tab at https://bldr.habitat.sh/#/pkgs/core/dotnet-472-runtime shows that 0.1.0 has a release in the stable channel, but does not list it in the "latest stable" side bar.

![Screen Shot 2019-08-16 at 10 14 37 AM](https://user-images.githubusercontent.com/517302/63173925-e70d6280-c00e-11e9-92d5-e893c8e73eb7.png)

### Steps to Reproduce:

Visit https://bldr.habitat.sh/#/pkgs/core/dotnet-472-runtime ? See that it says there are no stable packages despite a release sitting in the stable channel.

**Comment by robbkidd** [comment]
Another example:

https://bldr.habitat.sh/#/pkgs/pschaumburg/putty/latest displays the latest Linux release `pschaumburg/putty/0.72/20190815123548` (currently only in the unstable channel).

https://bldr.habitat.sh/#/pkgs/pschaumburg/putty -> Versions tab shows that the latest Windows release is in the stable channel, but there is no "Latest Stable"

![Screen Shot 2019-08-16 at 10 33 38 AM](https://user-images.githubusercontent.com/517302/63175144-66039a80-c011-11e9-9aa2-3e00ab24bb94.png)

**Comment by chefsalim** [comment]
This looks fixed on acceptance with the platform version tabs - eg, https://bldr.acceptance.habitat.sh/#/pkgs/core/dotnet-472-runtime/latest

**Comment by dmccown** [comment]
Closing as this looks like it has been fixed. Please let us know if you're still having issues!
