### ISSUE TITLE
Have Read-Only / Key-Only membership to an Origin

### ISSUE THREAD

**Issue by TheLunaticScripter** [habitat-sh/builder#1149]
### Describe the Enhancement:
Currently, there are only two levels of membership to an origin, an owner and a member. Both have access to the origin signing key as well as the ability to upload packages to the origin. By adding a limited access origin member this would allow a user to be able to use their current auth token to pull private packages from the origin without having access to upload or create new packages for that origin. 
### Describe the Need:

This would allow people to publish packages and grant users the ability to install them without giving them full access to the origin. In my opinion, this is the critical step to premium habitat content.

### Current Alternative
Currently, the only real alternative is to make the packages public. If we are talking about SaaS Builder and a public package is not an option then they need to stand up an on-premise depot and then limit access through OAuth. This causes an additional maintenance requirement for the customer.

### Can We Help You Implement This?:
Yes, I am currently looking at what it will take and have talked with @eeyun and @smacfarlane about the database. Currently, the first iteration could be adding an additional boolean field to the `origin_members` table called `key_access`. This would require a database migration that would update this field for all current members to true. This would probably need to start as an API where the default for a new invitation is `false` then through an API post-call like to `/origin/users/{username}/key_access/` to grant a user key access. There may be some UI changes to remove the keys tab from view for the user or it could be as simple as returning a grayed out warning like `Sorry, you currently do not have access to the {origin} keys please contact the owner of this origin to request access`.

**Comment by jeremymv2** [comment]
Doing a little discovery, it seems to me anyways, that the [pub fn authorize_session](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/authorize.rs#L26-L77) function is a logical API that can be augmented to take a parameter representing the CRUD "action" being required by the caller. The function can then determine, based on a "role" flag in `origin_members` table, whether or not the action is permitted.

This can be the start of a rudimentary RBAC API, and be expanded in the future to also take a "resource" parameter being acted upon. This would be similar to the [AuthZ API](https://github.com/chef/automate/tree/master/components/authz-service#elements-of-the-authz-query) in Automate.
