### ISSUE TITLE
Builder supports packages for multiple platforms

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/builder#1177]
## What problem are we solving?
A Habitat package can be built for multiple platforms -- Windows, Linux, Linux 2. Today it is difficult to know which platforms are supported for a given package, and it's difficult to manage uploading and downloading packages for various platforms. It's also difficult to connect plans and change settings.

​## Objective and key results
It should be easy for a user to manage and view packages that support multiple platforms.

## Acceptance criteria. 
I can create a package with no plan or artifact attached.
I can connect a plan for Linux, Linux 2, and Windows to a package.
I don’t have to go through the first step of selecting the GitHub repo in order to edit the other settings. 
UI and user flow matches the Invision Mockup ​
I can disconnect a plan from a package
I can change settings per connected plan
I can change the default package visibility
On prem builder has no UI for connecting plans, otherwise the above apply

​## Dependencies and blockers. 

n/a

## Evidence. 

Several related issues (#552, #50, #337 )

​## Out of scope. 

While we are fixing several Builder UI issues related to solving this problem, we will avoid the temptation to majorly rework the UI.

​## Open questions.

n/a

**Comment by stidhamlisa** [comment]
Moving back to Ready for Work as the UI team is currently booked.

**Comment by eeyun** [comment]
This work is now complete and as of today released!
