### ISSUE TITLE
[Builder UI] Create an empty package

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/builder#1179]
## Problem
Currently, there are two ways where users can create a package in Builder: one is to upload a pre-built artifact (.hart file) to Builder; one is by connecting a plan file. When we were designing the new flow which allows multiple plan files connected to a single package, we realized that the flow becomes much more complex if we continue tying "connecting a plan file" together with possibly "creating a package" at the same time. There are three points in the flow where we need to verify if this is connecting a plan file for an existing package or not. To simply the logic, we want to separate the task of "creating a package" out of the "connecting a plan file" flow. So that each task flow becomes simpler, both for the user and the technical implementation.

The solution is that users should be able to create a package that has neither a plan file connected nor an artifact exists. We call it an "empty package".

An empty package shouldn't contain any information around what platform it supports since that is dictated by what plan files and artifacts it has connected to/contains.

## Acceptance Criteria
- Click on the “create package” button from the `Origin > Package` tab, show a modal with an input field for origin names, using the same modal component in `Origin > Integrations > Edit / Create Integrations`.
- Modals don't have separate URLs.
- Validate the package name is unique within the origin and fulfill the requirement as specified in the UI.
- Follow the same validation messages pattern for Creating New Origin (https://bldr.habitat.sh/#/origins/create)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/3bb0dc51-be46-4ba7-a04b-56df261094e1)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/6838f844-8510-4d1a-9d03-c6264362032d)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/b4d9be1e-047a-410d-ba79-e7ef28af8e65)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/f1098cff-d315-4a33-b109-e9e94f622388)
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/178b151d-b29e-4860-9b77-26b3a892e8fb)

- Create an empty package with no artifacts or plans, by default, land on the `Origin > Package > Settings` tab after creation.

## Demo
- visit Builder site, sign in
- select an origin in My Origins
- under the Packages tab, click on "create package"
- in the "create package" modal, click "cancel". the modal should disappear
- click "create package" again, in the modal, type in names that are: 1. exist already; 2. contains a `^` character; 3. longer than 255 characters; 4. valid; to demonstrate the validation messages.
- once the name is valid, click on "save & continue"
- land on the Settings tab in the new package view with the name just entered

## UX Design
https://chef.invisionapp.com/share/E4U4DEYPZM2#/387103450_origin-Packages-Create_Packages_Modal

## Docs
Update docs and tutorials where the "connect a plan file" button is mentioned.  @kagarmoe
For example:
https://www.habitat.sh/demo/build-system/steps/7/

**Comment by SEAjamieD** [comment]
@apriofrost - in the acceptance section, are you asking that we use the actual same modal component from integrations edit/delete (integration-credentials-form.dialog.ts) or just that we model it after this Modal?

**Comment by SEAjamieD** [comment]
I have to pause on this until I get my VM/Builder setup fixed.  If I can get it fixed today, I'm determined to open a PR on this by the end of the day tomorrow.  It's was off to a good start until my VM broke.  Will keep you posted.

**Comment by apriofrost** [comment]
Hi @SEAjamieD , I meant to use the same modal style following the "integrations edit/delete" (integration-credentials-form.dialog.ts) , but make the headings, labels, buttons, etc. to match with what's shown in the UX design mockup.
My language sounds confusing probably because we don't have componentized UI elements in Builder yet.
![image](https://user-images.githubusercontent.com/9401459/70189706-da3d7900-16a8-11ea-8fb2-8f42391edadf.png)
Let me know if you have more questions :)

**Comment by stidhamlisa** [comment]
Moving back to Ready for Work as the UI team is currently booked.

**Comment by stidhamlisa** [comment]
Moving to Iteration 11
