### ISSUE TITLE
[Builder UI] Setting up / editing plan connections revamp

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/builder#1181]
## Problem
Firstly, the existing plan setup and editing UI is split into two steps, and it's impossible to go to the second step without selecting a GitHub org and repo in the first step. Sometimes it takes a while to load all the org and repo, causing frustration when users only want to update a setting located in the second step. In addition, the navigation to navigate back to the first step from the second is currently broken.
Secondly, the existing setting up plan connection flow is designed for Linux plans only. As we add the support for multi-platform packages, we should redesign the UI to fulfill the plan requirements for each specific platform.

## Acceptance Criteria
- all UIs in this issue are only accessible from the SaaS Builder, not the on-prem Builder.
- users can connect up to three plan files, one plan for one platform: Linux, Linux 2 and Windows.
- create an overlay UI component similar to what Automate has today, and make it responsive.
- consider adding a swipe up and down transitional animation for the overlay when it enters and dismisses from the view. 
- add a URL for the overlay `https://bldr.habitat.sh/#/pkgs/{origin-name}/{package-name}/settings/{platform-name}-plan`. 
  - For example `https://bldr.habitat.sh/#/pkgs/apriofrost/sample-node-app/settings/linux2-plan`
- re-use the existing UI components for selecting GitHub org and repo
- every element remains the same for different platform except for the following parts highlighted in red squares:
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/2209ac2e-f03a-47f3-869c-6fc748497cac)

- The copy variation for the "path to plan file" sections are:

#### Windows
Enter the path to your plan file from the root of your repo. By default, we check for habitat/plan.ps1.

Note:  after the new plan connection flow roll-out, all the existing Windows plan connection needs reconfiguration from users, because we did not store the Windows plan file path. If a user lands on the plan editing page from an existing Windows plan connection, the default plan path is likely the same as Linux as `habitat/plan.sh`. We need to highlight the plan path input field as `error` (red outline) and show an error message "A Window plan file name must end with `.ps1`." That means we will need to add a verification at the front-end to verify if the plan file name ends with `.ps1` which is the only format we currently support for the Windows plan file.

#### Linux 
Enter the path to your plan file from the root of your repo. By default, we check for habitat/plan.sh.

#### Linux 2 
Enter the path to your plan file from the root of your repo. By default, we check for habitat/plan.sh.
Note: for Linux 2, if users point to the Linux 2 specific plan, show an error: Enter the path to your Linux plan file. This should be handled in the backend.

- for plan files for all platforms, we need to validate if the origin name _and_ the package name specified in the plan file match with the current one in the UI. Previously we don't validate the package name. Show the error messages in the UI.

- keep the "publish to container registries" and "automatic dependency rebuilds" turn off by default, as it is today. Make no changes to the two sections.

- click the "save connection" button will close the overlay add an item in the "connected plan files" section in the Settings tab.

- click the gear icon in the "connected plan files" table opens the same overlay UI, users can make edits to existing plan connection and "save connection" again.

- click the close icon in the  "connected plan files" table removes the connected plan file. The function exists today and no changes are needed.

## Demo
- In the Settings tab for a package, click on the "connect a plan file" button, select a platform from the dropdown list.
- click the "Builder GitHub app" link, shows the installed app in a new tab
- click the "refresh" link, refresh the view with the overlay still showing up
- Enter the setting up plan connection overlay, select an org and repo
- enter the path to plan file
- leave everything else as default, click "save connection"
- see that a new plan file is added to the "connected plan files" table
- click the gear icon to enter the editing UI
- click the x icon to remove the plan

## UX Design
https://chef.invisionapp.com/share/E4U4DEYPZM2#/387298349_origin-Packages-Linux_Plan_Connection_Overlay

**Comment by scottopherson** [comment]
> all UIs in this issue are only accessible from the SaaS Builder, not the on-prem Builder.

Does anyone know if there are existing features with this particular acceptance criteria? If not, this is something new that needs to be added to the UI. How should the UI determine if it's running in SaaS or on-prem mode?
  - Pass a flag via https://github.com/habitat-sh/builder/blob/master/components/builder-api-proxy/habitat/config/habitat.conf.js?
  - Call some API endpoint on UI app startup to retrieve a flag?
  - Set a flag by checking if the current URL matches known URLs of SaaS deployments?

**Comment by scottopherson** [comment]
Is `enable_builder` such a flag? https://github.com/habitat-sh/builder/blob/master/components/builder-api-proxy/habitat/config/habitat.conf.js#L7

I'm not sure or not if it's purpose is for that or not. I see it used for hiding and showing certain areas in the UI, particularly the settings tab for packages: https://github.com/habitat-sh/builder/blob/master/components/builder-web/app/package/package/package.component.html#L36

**Comment by eeyun** [comment]
I'll let @chefsalim make the final say on this but yeah I'm pretty certain that flag is more or less the one that we want and I believe that's how it works today?
