### ISSUE TITLE
New API "get projects for package"

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1184]
With the new package creation and connection flow we will need an API that supports getting all of the projects for a package.

Based on internal discussions this is necessary due to planned alteration of the the origin_projects table to have separate entries for each platform of a package. We'll need to be able to enumerate the projects that are configured for an individual package.

**Comment by SEAjamieD** [comment]
@eeyun - This ticket is currently labeled as blocking https://github.com/habitat-sh/builder/issues/1180 - checking in because it looks like this ticket may actually done?  Wanted to see if I can start on #1180.  Thanks!

**Comment by eeyun** [comment]
This work is completed!

**Comment by SEAjamieD** [comment]
Rad! thank you!
