### ISSUE TITLE
[Builder UI] Revamp artifact visibility settings at origin, package and artifact levels

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/builder#1189]
## Problem
As mentioned in issue #1042 #1043 , and to follow our new model for visibility settings:
![image](https://user-images.githubusercontent.com/9401459/66525257-b9daaf00-eaa9-11e9-9ad8-792edf5eb982.png)

## Acceptance Criteria
- change the languages about "private/public packages" to "private/public artifacts" across Builder UI.
- change the copy for default visibility settings at origin and package level to match with the mockup, making it clear that the visibility settings only apply to future build artifacts and not the existing ones.
- add a unique URL for versions when an accordion for a specific is open, for example, https://bldr.habitat.sh/#/pkgs/apriofrost-demo/sample-node-app/1.0.1/
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/d95a7084-31ce-4f03-8cac-d28402056201)
- add a deeper level page for individual artifact using the UI page template for packages and origins
    - the URL already exist today, for example, https://bldr.habitat.sh/#/pkgs/apriofrost-demo/sample-node-app/1.0.1/20181204174005
- make the bread crumb navigation work as below: ![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/2e8359ab-6e1b-43bb-9ddb-7b5a1cadc30b)
- in the artifact page, has a "manifest" and a "settings" tab ("build jobs" tab is TBD)
- users can change the visibility of the artifact under the "settings" tab.

## Demo
For a package that has multiple versions exist:
- click the Artifact tab in the package view
- click on a version name, see a list of releases in the same version with their visibility setting shown as icons
- click on a specific release, see the artifact page with the manifest tab selected for that release
- click the Settings tab, see the visibility setting
- toggle the visibility setting, if it is from public to private, show a confirmation modal
- click the "change to private" button, see the visibility setting is saved, and visibility icon in the heading updates to reflect the latest setting.
- toggle the visibility back to public, see it is saved and the heading icon updates.

## UX Design
https://chef.invisionapp.com/share/E4U4DEYPZM2#/387965042_origin-Packages-Versions

## Docs
Add docs to introduce the new way to change artifact visibility.

**Comment by SEAjamieD** [comment]
Draft PR: https://github.com/habitat-sh/builder/pull/1274
