### ISSUE TITLE
Update Builder Nginx HTTP access log format

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1190]
The following fields are useful for diagnosing the system performance and should be added to the log format for Nginx (builder-api-proxy):

```
$upstream_status
$upstream_response_time
```
https://nginx.org/en/docs/http/ngx_http_upstream_module.html?&_ga=2.78341265.40875800.1570668198-1300803674.1570668198#var_upstream_header_time

**Comment by eeyun** [comment]
This work was completed by #1213
