### ISSUE TITLE
Acceptance builder should update supervisors from 'current' channel

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#1191]
As we modify our `habitat-sh/habitat` release pipeline, the artifacts will land in a `current` channel before being promoted to stable.  Acceptance builder should consume those artifacts to run them for a period before they are promoted to stable.  This can be accomplished by either: changing the channel the supervisors watch from `builder-acceptance` to `current`,  or adding an expeditor subscription to promote the contents of `current` to `builder-acceptance`.

**Comment by christophermaier** [comment]
This is taken care of when https://github.com/habitat-sh/cloud-environments/pull/110 merges and the environments are re-Terraformed.
