### ISSUE TITLE
Package on builder can be missing dependencies

### ISSUE THREAD

**Issue by markan** [habitat-sh/builder#1211]
### Builder version
is that deployed to production as of 2019-10-29

### Scenario:

A package can be in the stable channel yet be missing dependencies.
The current latest version of core/spring-petclinic (core/spring-petclinic/4.2.6/20160824210913) lists core/jre8/8u102/20160729190435 as a dependency, yet this is not present in builder.

The TDEPS listed here: https://bldr.habitat.sh/#/pkgs/core/spring-petclinic/4.2.6/20160824210913
are:
```
core/acl/2.2.52/20160612075215
core/attr/2.4.47/20160612075207
core/cacerts/2016.04.20/20160612081125
core/coreutils/8.25/20160729192409
core/gawk/4.1.3/20160729192843
core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/gmp/6.1.0/20160612064724
core/grep/2.22/20160729192643
core/inetutils/1.9.4/20160729192802
core/jdk8/8u92/20160620143238
core/jre8/8u102/20160729190435
core/libcap/2.24/20160612075226
core/linux-headers/4.3/20160612063537
core/mpfr/3.1.4/20160612064810
core/mysql/5.7.14/20160812153521
core/ncurses/6.0/20160612075116
core/openssl/1.0.2h/20160729194249
core/pcre/8.38/20160729192620
core/procps-ng/3.3.11/20160612075316
core/sed/4.2.2/20160612075228
core/tomcat8/8.5.4/20160824210409
core/zlib/1.2.8/20160612064520
```

### Steps to Reproduce:

```
 hab pkg download core/jdk8/8u92/20160620143238 --target=x86_64-linux
» Preparing to resolve packages and download transitive dependendencies for 1 package idents
» Using channel stable from https://bldr.habitat.sh
» Storing in download directory "/home/mark/.hab/cache" 
☛ Verifying Checking the download directory (/home/mark/.hab/cache) permissions and creating it (if needed)
☁ Determining latest version of core/jdk8/8u92/20160620143238 for x86_64-linux in the 'stable' channel
Ø No packages matching ident core/jdk8/8u92/20160620143238 for x86_64-linux exist in the 'stable' channel. Check the package ident, target, channel and Builder url (https://bldr.habitat.sh) for correctness
✗✗✗
✗✗✗ Package not found. core/jdk8/8u92/20160620143238 for x86_64-linux in channel stable
✗✗✗
```

### Expected Result:

The package should be flagged somehow as incomplete, or possibly not allowed to be in an incomplete state and in stable.

I see a use case for *transient* incomplete packages being uploaded, particularly to unstable; otherwise users would have to upload in strict topological order. However, it is unlikely that anyone would want to *promote* an incomplete package, especially not to stable. It is likely that the jdk and jre packages in question existed at the time of upload, but it might be worth doing a sanity check when packages are removed to see what breaks.
Possible choices could be:
* Blocking deletion of packages that have dependencies
* Marking packages as incomplete in the UI
* Removing packages with broken dependencies from the stable channel. 

### Actual Result:
See above

**Comment by markan** [comment]
This was discovered via https://github.com/habitat-sh/on-prem-builder/issues/217

**Comment by smacfarlane** [comment]
Two things to note: `core/spring-petclinic` was a a demo app that has been removed from the core origin, so it shouldn't be needed in the full deps seed list.   

Because it has been removed, it hasn't been built in a very long time and deps on an outdated version of Java.  This particular package has been toggled private, as the changes in how we sort versions were causing it to bubble to the top ahead of the more recent builds that use semver versioning ([Context on Java versioning in core](https://github.com/habitat-sh/core-plans/blob/master/docs/dev/policy_documents/java-semantic-versioning.md))

So, I wouldn't necessarily call this a bug in Builder, as much as some cleanup work we need to do on the `core` origin and the seed lists.

**Comment by markan** [comment]
I'd argue that this package probably should be either removed, or marked private.

From a discussion with @smacfarlane it sounds like right now, if a package is marked as private, it's not accessible, even via a fully qualified ident. So any package depending on it is broken. 

One option would be to allow private packages to be downloaded via their fully qualified idents, even if they don't appear otherwise.
Another option would be to somehow mark/protect packages whose dependencies aren't available anymore, or warn on deletion/marking private that you are about to break packages.

**Comment by eeyun** [comment]
Strange, this could be a regression since i believe it use to be possible to install a package from a fully qualified ident regardless of whether it was private. We need a mechanism for deprecating packages full stop but thats a non-trivial feature addition that would need some discussion.
