### ISSUE TITLE
[on-prem builder] Allow to define a remote origin and redirect instead of syncing

### ISSUE THREAD

**Issue by Tensibai** [habitat-sh/builder#1212]
### Describe the Enhancement:

Using an on-prem builder, you need to sync core periodically.
The idea is to allow to define an origin with its builder/depot uri and allow the local builder to redirect to the builder really hosting the origin asked for.

### Describe the Need:

Probably of interest to all on-prem builders to avoid the periodic syncing of core or other public origins. 

### Current Alternative
None that I kow

### Can We Help You Implement This?:

My rough idea is to alter the Origin structure to add a 'remote_builder' property 

```
pub struct Origin {
    #[serde(with = "db_id_format")]
    pub owner_id: i64,
    pub name: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub default_package_visibility: PackageVisibility,
    pub remote_builder: String,
}
```
Next step would probably be a new method in `https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/resources/origins.rs` to check the property and return a 302 with the remote_builder url if that's the case but I'm very unsure what would be the correct approach here.

I didn't check if habitat side needs a change to handle a redirect.

**Comment by predominant** [comment]
I feel that builders should be self sufficient. Each endpoint / builder should contain all packages.

Redirecting would encourage on-prem-builder owners to redirect to community run resources, or Chef-run resources, which (in the case of Chef) ultimately won't be permitted long term without a paid license in place.

In the case of the community hosted Biome, this would create additional stress on the bandwidth requirements for the builder service.

Where I think this *does* make sense is for passthrough and caching/downloading. Consider the following interaction between two builder instances that have been registered with each other (this would be a new feature):

1. Builders A and B are registered / authenticated with each other
2. User / system attempts download from Builder A of package w/x/y/z (not present on Builder A)
3. User / system is issued an instruction to wait and retry for that package
4. Builder A contacts Builder B for package w/x/y/z
5. Package w/x/y/z is downloaded along with all keys and dependencies required to Builder A
6. User / system retries download from Builder A

This has been loosely discussed in the past, but I don't know where the discussion left off.

**Comment by jsirex** [comment]
I agree with @predominant that builders should be self sufficient. 

We can improve syncing by doing "incremental sync".
Fortunately each key and package has a release timestamp. [My current sync solution](https://github.com/habitat-plans/bio-sdk#bio-depot-sync)  lists all packages in source and then checks it exists in dest. So it downloads only new packages and promote one that is not promoted.

If I can ask builder to list packages newer/since a `DATE` I can **significantly improve syncing** process.

Also, @Tensibai I see potential issues with redirect: I try install package and on-prem builder redirects me to another builder. Package is being downloaded from upstream, but then I need its' transitive dependencies which potentially do not exist on on-prem builder. Who will redirect and where? What if I have 5 different upstream builders? Things get too complicated..

**Comment by Tensibai** [comment]
Concerning the Chef builder, I thought the licensing applied to origin owners but not to consumers, I may have misunderstood that point.

A proxy cache approach make sense to limit the stress on "upstream" builders indeed.

Something along the line of trigger an asynchronous sync of the dependencies on request. This may worth a small head request after some time to check if the upstream has been updated and resync if it's the case.

The drawback of syncing is the extra complexity, a "traditional" proxy-cache approach may be lighter to implement but maybe it doesn't make sense in builder api context.

**Comment by Tensibai** [comment]
@jsirex I may overlook something, but the dependencies download would follow the same path as the initial package, if the dependencies comes from 5 different origins on different builders, the on-prem builder must have them configured indeed. (There's a side benefit here of "partitioning" the load).

My main idea behind was: someone publish a package on biome, a Chef customer want to use it:
How does this customer get this package from biome when their habitat configuration point toward Chef builder ?

If I get it right actually an on-prem builder is necessary to sync Chef and Biome builders into the same one to get both "worlds" packages. 
I'm opening the talk to see if the workflow can be made easier and/or the on-prem builder optional.

**Comment by eeyun** [comment]
We have a whole boatload of historical context on this issue specifically and it is a doozy. We actually used to have automated pull through syncing and now we have the bulk download/upload tool as a stopgap solution. I'll try to type some of that out here in the next day or two as I hopefully get some free time.
