### ISSUE TITLE
Add configuration option to disable force uploading

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/builder#1222]
In order to develop a backup strategy in the near term, we would like to be able to assume that uploaded artifacts are immutable.  The `force` upload option, however, breaks this assumption.

Conversations have indicated that the --force option was put in place to remediate a problem that we don't think exists anymore.

A configuration item to disable this ability to force-upload packages would allow us to make the immutability assumption for newly installed Chef Automate-based Habitat Builder installations.

**Comment by eeyun** [comment]
To add a little color commentary to this feature, this was originally added as a safety net during a behavior change in package upload in which it was possible for the package to get written to the database but not stored in the artifact storage. The behavior is effectively the same as a standard upload except that we don't check if the package already exists in the database when the upload request is made. 

What this means is we still do our checksum matching and all other verifications on upload, but we allow you to write the package to the artifact store again should it be entirely missing. We have had customer's use this to both easily correct issues after doing bad things like manually removing packages from their artifact store and repopulating their database after making some bad decisions. 

I originally (in slack) told @stevendanna that I'd need to be heartily convinced to allow this, but honestly the more I think about it, the more i think this is reasonable. Feature flag it, that way folks who havent migrated to the newer builder clusters that could still hit this still have the ability to use this if they need it, but then it doesnt have to be on be default. It feels like a win to me.

**Comment by markan** [comment]
@eeyun So to clarify, does the current force update only work if the package is physically missing from builder artifact storage? And we verify that the checksum data (presumably already stored in the DB) must match when uploaded? The metadata is included in the checksum, right? So things like TDEPS and the like couldn't be changed by the second upload.

That's a pretty narrow case, and actually seems safe.

What I think would be problematic is if you could upload one package, then replace it with another with the exact same fully qualified ident, but different metadata or contents.

Allowing different packages with the same fully qualified ident creates some strange consistency problems. A user could start with a package A with fully qualified ident uploaded, have package B (which depends on A) resolve it’s TDEPS using that version, and then have a new version of A (A’) force uploaded with different deps and the same FQ ident as A.
That would mean that when B (built with A) was installed, it  would download A’ but have TDEPS inconsistent with it.

**Comment by stevendanna** [comment]
From our (deployment-team's) perspective, we can likely work-around non-immutable packages at the expense of a little more work in the backup process.  Really, we just need to know one way or another which y'all would prefer.

**Comment by chefsalim** [comment]
Based on offline discussions, we can unblock the backup/restore scenario as long as we guarantee that the force uploaded package has the exact same checksum that is already in the metadata. This should be a straightforward check to add to the upload path.
