### ISSUE TITLE
Unable to connect and build windows plans in acceptance

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/builder#1225]
@davidMcneil and I have been trying to build some connected windows plans on acceptance. I have see a few problems:

** dem/pester
This plan is connected but when either of us builds it, it's status immediately changes to `complete`. There is no build log generated.

** mwrock/contosouniversity
I went through the connection screen and was told that it succesfully connected. However, this does not show up in "Connected Plans". Trying to build it results in the same behavior as `dem/pester`

** core/lessmsi
Builds succesfully on acceptance

We were able to succesfully connect and build `dem/pester` on prod.

**Comment by eeyun** [comment]
Was this ever resolved?

**Comment by smacfarlane** [comment]
@mwrock I believe this has been corrected with the release of project settings enhancements.  https://forums.habitat.sh/t/builder-project-settings-enhancements/1302

I've gone through the connection workflow on acceptance and live and was able to connect a plan and build a package for Windows, so I'm going to go ahead and close this issue out now.
