### ISSUE TITLE
[CI] Automate syncing of acceptance environment

### ISSUE THREAD

**Issue by scotthain** [habitat-sh/builder#1226]
For many reasons, it is desirable to sync up the acceptance builder environment after a release of habitat. Mainly, we'd like to get the packages that were just released added to Acceptance, but ensuring that any new `core` packages are periodically moved over is also useful.

**Comment by scotthain** [comment]
Currently the package sync is done manually by running https://github.com/habitat-sh/on-prem-builder/blob/master/scripts/on-prem-archive.sh as needed, treating production bldr as the "upstream depot" with the `sync-packages` functionality. This should probably be revisited and perhaps updated to use new hab cli functionality.

**Comment by jsirex** [comment]
Probably this will help you a bit while thinking on more reliable/native solution:
https://github.com/habitat-plans/bio-sdk#bio-depot-sync

It dirty written, but it works. The `bio-depot-sync` command is stateless, doesn't require storage (each artifact downloaded and uploaded in memory), is able to sync only specified channel, all versions or only latest..
