### ISSUE TITLE
Trigger package synchronization from prod to acceptance in response to Habitat releases

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#1230]
In order to have Acceptance Builder mirror Production Builder as much as possible, we should ensure that newly-released Habitat artifacts (e.g., new Supervisor packages, etc.) are synced over to the Acceptance Builder after each Habitat release.

Currently, this is done on a manual, ad-hoc basis, using our [on-prem-archive.sh](https://github.com/habitat-sh/on-prem-builder/blob/master/scripts/on-prem-archive.sh) script. This task is to automate that process.

(The fact that we currently use a script in the `on-prem-builder` repository suggests that this trigger might need to live there, but that may depend on the future of that script; do whatever makes the most sense.)

**Comment by scotthain** [comment]
This could also be a scheduled task if we wanted.

**Comment by mwrock** [comment]
Now that we have `hab pkg download` we can likely use that instead of `on-prem-archive.sh` to make this simpler.
