### ISSUE TITLE
[Builder UI] Users can connect up to three plan files, one for each platform

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1240]
As shown in the mockups for #1181 users need to be able to connect up to three plan files per package. Linux, Linux2 and Windows. 

Project creation and update operations should now pass the `target` selection into the project creation request body. In Liz's mockup that comes from a button dropdown when a user clicks 'connect plan' however this location might need to change for an initial pass. 

GETs and DELETES of projects should now pass the target in as a query parameter. So long as we are always passing the target data to any of these operations we should be unblocked.

**Comment by vjeffrey** [comment]
if it's possible to get this up for review by wednesday (12/4), the hab team will be able to avoid doing extra to feature flag things

**Comment by scottopherson** [comment]
https://github.com/habitat-sh/builder/issues/1181#issuecomment-560572559

The UI may need to add its own flag around SaaS vs on-prem unless I'm unaware of an existing one.
