### ISSUE TITLE
Allow to build package from on-prem gitlab

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/builder#1266]
There is closed https://github.com/habitat-sh/builder/issues/485 looks similar. But I decided to create a separate one.

It would be super cool if I can connect a plan with on-prem gitlabs' repository.
So if I push code to the gitlab builder will automatically build all necessary packages.

It also will resolve issue https://github.com/habitat-sh/builder/issues/845 because I no longer need a workaround.

**Comment by chefsalim** [comment]
Agree it would be useful and something to consider for the future
