### ISSUE TITLE
Spike: Proposal for solving circular dependency issues

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/builder#1269]

**Comment by markan** [comment]
This is a research spike to produce a concrete plan for circular dependencies. This should describe a solution or solutions, and break out detailed tasks for future execution.

**Comment by markan** [comment]
https://docs.google.com/document/d/1ursBuwosNieHlbFp4oVN9eVd844u_ZLqQDg8hMjUOxs/edit?pli=1#
