### ISSUE TITLE
[on-prem depot] Make checking for circular dependencies optional

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#127]
Right now when you upload a hab package, [we check for circular dependencies](https://github.com/habitat-sh/builder/blob/master/components/builder-depot/src/server.rs#L788-L821).  That checking needs to be hidden behind a flag in the configuration file so that we can turn it off if we want to.  That will make it possible to ship an on-prem depot that doesn't include builder-jobsrv or builder-worker.

**Comment by chefsalim** [comment]
There is a builds_enabled config that we can leverage..

**Comment by raskchanky** [comment]
It's just for non-core builds though.  Probably worth adding a new option.

**Comment by raskchanky** [comment]
It turns out this doesn't quite encapsulate everything that needs to happen.  Closing in favor of https://github.com/habitat-sh/builder/issues/137
