### ISSUE TITLE
Investigate DB call time spikes

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1279]
This is a placeholder work item to further investigate and mitigate DB call time spikes in the TP95 percentile. The current threshold is at 1.5sec warn, 2.5sec alert.  We may need to add additional logging to track specific calls and look at tweaking the DB pool configuration as well.

**Comment by eeyun** [comment]
Following the new metrics added to the dashboard we've effectively verified the source of the call time spikes as at least tangentially related to the get latest channel package call. We were already aware that this call was expensive likely due to our channels implementation as the ORM call looks like the following:
```
            .inner_join(origin_channel_packages::table.inner_join(origin_channels::table))
            .filter(origin_packages_with_version_array::origin.eq(&ident.origin))
            .filter(origin_packages_with_version_array::name.eq(&ident.name))
            .filter(origin_channels::name.eq(req.channel.as_str()))
            .filter(origin_packages_with_version_array::target.eq(req.target))
            .filter(origin_packages_with_version_array::visibility.eq(any(req.visibility)))
            .filter(origin_packages_with_version_array::ident_array.contains(ident.clone().parts()))
            .order(sql::<PackageWithVersionArray>(
                "string_to_array(version_array[1],'.')::\
                 numeric[] desc, version_array[2] desc, \
                 ident_array[4] desc",
            ))
            .limit(1)
            .get_result(conn);
```
