### ISSUE TITLE
[Builder UI] Allow user to depart membership from an origin

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1292]
### Describe the Enhancement:
We don't have UI bits for departing membership from an origin

### Describe the Need:
It's not currently possible to leave an origin you don't wish to be a part of via the UI and now that we have the departure API we should get this added.

### Current Alternative
Current alternative is to use the hab-cli to make the departure

**Comment by apriofrost** [comment]
### Solution
Allow origin members (not including the owner) to initiate the action to depart from the origin in the Builder UI. After the action is initiated, show a confirmation modal that allows users to understand the consequences of the action before confirmation. If confirmed, the user is removed from the member's list of the origin, and no longer has the access previously granted for members.

### Acceptance Criteria 

- [ ] Add a `Depart from Origin` button at the bottom of the table, with the secondary button style in the "danger" color. Following the space definition of the "Upload a private key" button under the `private key` table under the `keys` tab.
- [ ] When the button is triggered, show a modal with the heading `Depart from origin?` the `danger` color and the body `Departing from <origin_name> will revoke your access to create packages and utilize private artifacts in this origin.`, along with the `Depart from Origin` primary button and the `Cancel` tertiary button. 
- [ ] When the `Cancel` button is triggered, close the modal and show the previous screen with the `members` tab.
- [ ] When the `Depart from Origin` button is triggered, initiated the event. If successful, show a `success` toast notification with the body `Departed from origin`; If not successful, show a `failure` toast notification with the error messages in the body.
- [ ] Once the member successfully departed from the origin, refresh the page and show the public view for the departed origin. If the origin is private, show the landing page of My Origins (`https://bldr.habitat.sh/#/origins`).

### Demo Instruction

1. Navigate to the `members` tab of a **public** origin
2. If the current user is the owner of the origin, show that there is no `Depart from Origin` button.
3. If the current user is not the owner of the origin, show that there is `Depart from Origin` button.
4. As a member (not the owner), click on the "Depart from Origin" button, a confirmation modal shows up as an overlay.
5. On the confirmation modal, click the "Cancel" button, the overlay disappears.
6. Click on the "Depart from Origin" button again. On the confirmation modal, click the `Depart from Origin` button.
7. See a toast notification pops up from the bottom of the window with two types of messages: successful and failure, with its corresponding body content described in the Acceptance Criteria.
8. Upon success, the user is presented with the public view of the departed origin with the `packages` tab selected.

** repeat the same steps for a **private** origin. In step 8 shows that the user is navigated to the landing page of My Origins (`https://bldr.habitat.sh/#/origins`).

### Mockup
- InVision link:https://chef.invisionapp.com/share/96VZ28STD7H#/screens/404934405_origin-Members (scroll to the bottom of the page to start)
- Video demo: https://drive.google.com/file/d/1OcEsT0rU_dfWpkzCqBcwIDVsqWhkmdPg/view

**Comment by SEAjamieD** [comment]
@eeyun - Could you point me to correct endpoint for a user to remove themselves from an origin?  I tried reusing the same one for deleting other members... `< /depot/origins/${origin}/users/${member} >` but got a "Forbidden" message back, probably from here: https://github.com/habitat-sh/builder/blob/694ba7ba0a158f19f817fd7b96aa790b91550937/components/builder-api/src/server/resources/origins.rs#L1095

If you believe this _is_ the correct endpoint to use, i'll start looking to see if this is a dev environment issue.

**Comment by jeremymv2** [comment]
@SEAjamieD alas, that endpoint is not the correct one for self departing.

The use must send an HTTP POST to `/depot/origins/ORIGIN_NAME/depart`.

Take a look at our API [tests](https://github.com/habitat-sh/builder/blob/f06a39ca29ed3c2a75006a221c5d724c4fb4e812/test/builder-api/src/origins.js#L274-L330) and our [raml](https://github.com/habitat-sh/builder/blob/7f45bcd9b71c6371b5fc6631a1b6e44600afdd08/components/builder-api/doc/api.raml#L881) for some examples.
