### ISSUE TITLE
Channel related DB Call Time Optimizations

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1295]
based on the history here: #1279 as well as our own historical knowledge of the channels implementation we are very aware that our current channels implementation is very poorly performant and functionally inadequate. We might need multiple cards to get this all fully resolved but for now we should investigate optimizing the call first and think about functional changes later.

**Comment by markan** [comment]
The key goal of this is to improve some of the worst case API behavior in builder.

In particular the current hotspots seem to be:
* The DB call: latest_channel_package (see graph  in Live API Dashboard https://app.datadoghq.com/dashboard/55b-wpy-s6k/live-api-dashboard?from_ts=1585942118527&live=true&tile_size=m&to_ts=1585945718527)

This is a particularly slow DB call used by a number of APIs (TODO identify which APIs are impacted)

* API depot/pkgs/ORIGIN/PACKAGE/VERSION (e.g. https://bldr.habitat.sh/v1/depot/pkgs/core/7zip/16.04?range=0)
This may be a slow implementation in the API, or db issues; needs more research.

**Comment by markan** [comment]
The latest_channel_package call is something like:
```SELECT "origin_packages_with_version_array"."id", 
       "origin_packages_with_version_array"."owner_id", 
       "origin_packages_with_version_array"."name", 
       "origin_packages_with_version_array"."ident", 
       "origin_packages_with_version_array"."ident_array",
       "origin_packages_with_version_array"."checksum",
       "origin_packages_with_version_array"."manifest", 
       "origin_packages_with_version_array"."config", 
       "origin_packages_with_version_array"."target", 
       "origin_packages_with_version_array"."deps", 
       "origin_packages_with_version_array"."tdeps", 
       "origin_packages_with_version_array"."exposes", 
       "origin_packages_with_version_array"."created_at", 
       "origin_packages_with_version_array"."updated_at", 
       "origin_packages_with_version_array"."visibility",  
       "origin_packages_with_version_array"."origin", 
       "origin_packages_with_version_array"."build_deps", 
       "origin_packages_with_version_array"."build_tdeps", 
       "origin_packages_with_version_array"."version_array" 
       FROM ("origin_packages_with_version_array" 
             INNER JOIN ("origin_channel_packages" 
                         INNER JOIN "origin_channels" 
                         ON "origin_channel_packages"."channel_id" = "origin_channels"."id") 
             ON "origin_channel_packages"."package_id" = "origin_packages_with_version_array"."id")
       WHERE "origin_packages_with_version_array"."origin" = 'core'
         AND "origin_packages_with_version_array"."name" = 'gcc'
         AND "origin_channels"."name" = 'stable'
         AND "origin_packages_with_version_array"."target" = 'x86_64-linux'
         AND "origin_packages_with_version_array"."visibility" = ANY('{public, private, hidden}'::origin_package_visibility[])
         AND "origin_packages_with_version_array"."ident_array" @>  '{core, gcc}'::text[]
       ORDER BY string_to_array(version_array[1],'.')::numeric[] desc, 
                version_array[2] desc, 
                ident_array[4] desc 
       LIMIT 1;
```
running EXPLAIN ANALYZE give us
```
 Limit  (cost=18665.98..18665.99 rows=1 width=1438) (actual time=105.658..105.659 rows=1 loops=1)
   ->  Sort  (cost=18665.98..18665.99 rows=1 width=1438) (actual time=105.658..105.658 rows=1 loops=1)
         Sort Key: ((string_to_array((regexp_matches(origin_packages.ident_array[3], '([\d\.]*\d+)(.+)?'::text))[1], '.'::text))::numeric[]) DESC, ((regexp_matches(origin_packages.ident_array[3], '([\d\.]*\d+)(.+)?'::text))[2]) DESC, (origin_packages.ident_array[4]) DESC
         Sort Method: top-N heapsort  Memory: 27kB
         ->  Nested Loop  (cost=16020.64..18665.97 rows=1 width=1438) (actual time=87.618..105.626 rows=3 loops=1)
               ->  Hash Join  (cost=16020.35..18665.31 rows=2 width=1350) (actual time=86.938..105.503 rows=18 loops=1)
                     Hash Cond: (origin_channel_packages.package_id = origin_packages.id)
                     ->  Seq Scan on origin_channel_packages  (cost=0.00..2154.59 rows=130759 width=16) (actual time=0.009..11.244 rows=130759 loops=1)
                     ->  Hash  (cost=16020.34..16020.34 rows=1 width=1342) (actual time=79.381..79.381 rows=11 loops=1)
                           Buckets: 1024  Batches: 1  Memory Usage: 19kB
                           ->  Seq Scan on origin_packages  (cost=0.00..16020.33 rows=1 width=1342) (actual time=1.696..79.343 rows=11 loops=1)
                                 Filter: ((ident_array @> '{core,gcc}'::text[]) AND (origin = 'core'::text) AND (name = 'gcc'::text) AND (target = 'x86_64-linux'::text) AND (visibility = ANY ('{public,private,hidden}'::origin_package_visibility[])))
                                 Rows Removed by Filter: 78487
               ->  Index Scan using origin_channels_pkey on origin_channels  (cost=0.29..0.32 rows=1 width=8) (actual time=0.004..0.004 rows=0 loops=18)
                     Index Cond: (id = origin_channel_packages.channel_id)
                     Filter: (name = 'stable'::text)
                     Rows Removed by Filter: 1
 Planning time: 0.766 ms
 Execution time: 105.762 ms
 ```

**Comment by markan** [comment]
Now in RAM, still slow
SELECT *, COUNT(*) OVER () FROM (SELECT
"packages_with_channel_platform"."id",
"packages_with_channel_platform"."owner_id", 
"packages_with_channel_platform"."name",
"packages_with_channel_platform"."ident", 
"packages_with_channel_platform"."ident_array",
"packages_with_channel_platform"."checksum", 
"packages_with_channel_platform"."manifest",
"packages_with_channel_platform"."config", 
"packages_with_channel_platform"."target",
"packages_with_channel_platform"."deps", 
"packages_with_channel_platform"."tdeps",
"packages_with_channel_platform"."build_deps", 
"packages_with_channel_platform"."build_tdeps",
"packages_with_channel_platform"."exposes",
 "packages_with_channel_platform"."visibility",
"packages_with_channel_platform"."created_at",
"packages_with_channel_platform"."updated_at",
 "packages_with_channel_platform"."origin",
"packages_with_channel_platform"."channels",
"packages_with_channel_platform"."platforms"
 FROM "packages_with_channel_platform" 
WHERE "packages_with_channel_platform"."ident_array" @> '{core, gcc}'::text[]
 AND "packages_with_channel_platform"."visibility" = ANY('{public, private, hidden}'::origin_package_visibility[])
 ORDER BY "packages_with_channel_platform"."ident" DESC) t LIMIT 50 OFFSET 0;
                                                                                                    QUERY PLAN                                                                                                     
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=82802.46..82803.13 rows=27 width=1421) (actual time=4197.037..4197.047 rows=24 loops=1)
   ->  WindowAgg  (cost=82802.46..82803.13 rows=27 width=1421) (actual time=4197.036..4197.045 rows=24 loops=1)
         ->  Sort  (cost=82802.46..82802.53 rows=27 width=1413) (actual time=4197.012..4197.014 rows=24 loops=1)
               Sort Key: packages_with_channel_platform.ident DESC
               Sort Method: quicksort  Memory: 52kB
               ->  Subquery Scan on packages_with_channel_platform  (cost=71489.86..82801.82 rows=27 width=1413) (actual time=3908.791..4196.925 rows=24 loops=1)
                     Filter: ((packages_with_channel_platform.ident_array @> '{core,gcc}'::text[]) AND (packages_with_channel_platform.visibility = ANY ('{public,private,hidden}'::origin_package_visibility[])))
                     Rows Removed by Filter: 307788
                     ->  WindowAgg  (cost=71489.86..77730.94 rows=312054 width=1413) (actual time=3717.483..4142.305 rows=307812 loops=1)
                           ->  Sort  (cost=71489.86..72270.00 rows=312054 width=1369) (actual time=3717.452..3756.678 rows=307812 loops=1)
                                 Sort Key: op.ident
                                 Sort Method: quicksort  Memory: 587028kB
                                 ->  Hash Join  (cost=35485.76..43012.69 rows=312054 width=1369) (actual time=283.222..550.044 rows=307812 loops=1)
                                       Hash Cond: (ocp.channel_id = oc.id)
                                       ->  Hash Join  (cost=34059.78..40767.49 rows=312054 width=1357) (actual time=271.776..470.047 rows=307812 loops=1)
                                             Hash Cond: (ocp.package_id = op.id)
                                             ->  Seq Scan on origin_channel_packages ocp  (cost=0.00..5888.54 rows=312054 width=16) (actual time=0.005..27.008 rows=307812 loops=1)
                                             ->  Hash  (cost=32136.57..32136.57 rows=153857 width=1349) (actual time=270.925..270.925 rows=153680 loops=1)
                                                   Buckets: 262144  Batches: 1  Memory Usage: 210901kB
                                                   ->  Seq Scan on origin_packages op  (cost=0.00..32136.57 rows=153857 width=1349) (actual time=0.004..88.791 rows=153680 loops=1)
                                       ->  Hash  (cost=922.10..922.10 rows=40310 width=28) (actual time=11.228..11.228 rows=42784 loops=1)
                                             Buckets: 65536  Batches: 1  Memory Usage: 3214kB
                                             ->  Seq Scan on origin_channels oc  (cost=0.00..922.10 rows=40310 width=28) (actual time=0.007..4.921 rows=42784 loops=1)
 Planning Time: 1.238 ms
 Execution Time: 4215.980 ms
