### ISSUE TITLE
[on-prem depot] Bootstrapping packages script

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#130]
There are two options here.

The easiest thing to do is just to write a simple bash script that can pull a specific set of packages from the public Habitat depot and upload those artifacts to the on-prem depot.  This should be considered a must-have.  The specific set of packages that are needed is still TBD, but this script can be written and tested using any random set of packages for now, and refined after we have the final list.

Time permitting, a better long term solution is to have the on-prem depot automatically try to download packages from the public Habitat depot if it can't find them in its own local storage.  So the flow from the server's perspective looks like:
* Client requests to download a package
* Try to find said package in our local archive.
  * Success?  Send it to the client.  Done.
  * Not found?  Try to download said package from the public depot.
    * Success?  Send it to the client.  Also store it in our local archive as though the user had just uploaded it.  Done.
    * Not found?  404.  Done.

**Comment by chefsalim** [comment]
Updated title, and will open a separate issue for the longer-term cache-thru approach.

**Comment by raskchanky** [comment]
FWIW, I don't think the pull-through approach would be that much work.  That was the main reason I picked up this issue 😁

**Comment by chefsalim** [comment]
We might need both - a script to populate the core packages initially, and then something to pull from the public depot, as initially there will be no package metadata at all...?

**Comment by raskchanky** [comment]
Which core packages are we wanting to populate an on-prem depot with initially?

/cc @elliott-davis

**Comment by chefsalim** [comment]
I'd think we just take them all. We could probably use a combination of the bootstrap script + the bulk promote tool to retrofit a simple script that takes all the latest core packages and puts them up on S3, and then they can easily be downloaded and installed on-prem from that bootstrap.

**Comment by raskchanky** [comment]
Ah, so to clarify the kind of script(s) we're writing here:

There will be one script that is intended to be run on the builder-api production server, to find every hart file and tar them all up into a giant tarball (and it will be giant - the acceptance tarball @elliott-davis made a few months ago was on the order of 50GB), and from there, upload that tarball to S3.

Then there will be a separate script, which will connect to S3 and download the giant tarball, un-tar it, and manually upload all of the resulting hart files to the newly installed on-prem depot.

Do I have that correct?

**Comment by raskchanky** [comment]
The requirements for this seem like they're in a continuous state of flux, so in an effort to nail down something concrete, here is what I'm going to build.  There will be a script that gets a list of every package we have from the core-plans repo.  It will download the latest stable version of all of those packages and tar them all up.  It will upload that archive to S3.  It will also download that archive from S3, extract all the files in it and upload those files to the specified depot.

Anything that deviates from the above description can be done as a separate task another time.

**Comment by chefsalim** [comment]
👍
