### ISSUE TITLE
PackageTarget isn't accounted for when starting jobsrv

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#1302]
When jobsrv starts up, it fetches the latest version of each package in order to build the PackageGraph, which is used to calculate reverse dependencies for builds. [code](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/mod.rs#L172-L173).  The [structure](https://github.com/habitat-sh/builder/blob/master/components/builder-core/src/target_graph.rs#L30-L32) that holds the graph, does take into account package target, and the loading does correctly bucket packages by their targets. [code](https://github.com/habitat-sh/builder/blob/master/components/builder-core/src/target_graph.rs#L72-L76)

However, the function called to get the latest version of each package, [Package::get_all_latest](https://github.com/habitat-sh/builder/blob/master/components/builder-db/src/models/package.rs#L471-L487) does not take PackageTarget into account, meaning our input into the graph generation on boot is incomplete.   

This will correct over time, as packages are built and rebuilt, and has largely been a non-issue until recently due to minimal overlap between Windows and Linux packages, and jobsrv having high uptime.   As we add more packages that are available for multiple targets, (such as core/python), the likelihood of incorrect build groups (how this particular issue manifests) will become a more common occurrence.

**Comment by chefsalim** [comment]
The way this is designed is that the TargetGraph does the filtering when the graph is built, so this _should_ be ok - https://github.com/habitat-sh/builder/blob/master/components/builder-core/src/target_graph.rs#L73

**Comment by smacfarlane** [comment]
> The way this is designed is that the TargetGraph does the filtering when the graph is built, so this _should_ be ok - https://github.com/habitat-sh/builder/blob/master/components/builder-core/src/target_graph.rs#L73

I don't think that function is the problem. I believe our input into that function is incorrect, or more accurately incomplete, on jobsrv start.   To verify this I loaded the following packages into a development Builder instance:
```
results/smacfarlane-minimal_package-0.0.0-20200208140843-x86_64-linux.hart, 
results/smacfarlane-minimal_package-0.0.0-20200208141054-x86_64-linux-kernel2.hart
````

After wrapping https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/mod.rs#L169 with `dbg!()`, rebuilding and restarting jobsrv I got the following output:

```
builder-jobsrv.default(O): [components/builder-jobsrv/src/server/mod.rs:170] packages.iter().map(|p| p.clone().into()).collect() = [
builder-jobsrv.default(O):     id: 1442043248800448512
builder-jobsrv.default(O):     owner_id: 1442042898911600640
builder-jobsrv.default(O):     ident {
builder-jobsrv.default(O):       origin: "smacfarlane"
builder-jobsrv.default(O):       name: "minimal_package"
builder-jobsrv.default(O):       version: "0.0.0"
builder-jobsrv.default(O):       release: "20200208141054"
builder-jobsrv.default(O):     }
builder-jobsrv.default(O):     checksum: "11ab5b3a5bd2c79b60b8247ac059930ed8abb57124a4c1ea67bdeffd799112ad"
builder-jobsrv.default(O):     manifest: "# smacfarlane / minimal_package\n\n\n* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>\n* __Version__: 0.0.0\n* __Release__: 20200208141054\n* __Target__: x86_64-linux-kernel2\n* __Upstream URL__: upstream project's website or home page is not defined\n* __License__:  \n* __Source__: source URL not provided or required\n* __SHA__: SHA256 checksum not provided or required\n* __Path__: `/hab/pkgs/smacfarlane/minimal_package/0.0.0/20200208141054`\n* __Build Dependencies__: no build dependencies or undefined\n* __Dependencies__: no runtime dependencies or undefined\n* __Interpreters__: no interpreters or undefined\n\n# Plan\n\n## Build Flags\n\n```bash\nCFLAGS: no CFLAGS\nCPPFLAGS: no CPPFLAGS\nCXXFLAGS: no CXXFLAGS\nLDFLAGS: no LDFLAGS\nLD_RUN_PATH: no LD_RUN_PATH\n```\n\n## Plan Source\n\n```bash\npkg_name=\"minimal_package\"\npkg_origin=\"habitat-testing\"\npkg_maintainer=\"The Habitat Maintainers <humans@habitat.sh>\"\npkg_version=\"0.0.0\"\n\ndo_build() { :; }\ndo_install() { :; }\n```"
builder-jobsrv.default(O):     config: ""
builder-jobsrv.default(O):     target: "x86_64-linux-kernel2"
builder-jobsrv.default(O):     visibility: Public
builder-jobsrv.default(O):     ,
builder-jobsrv.default(O): ]
builder-jobsrv.default(O): [2020-02-08T14:12:48Z INFO  habitat_builder_jobsrv::server] Graph build stats (PT0.000108568S sec):
builder-jobsrv.default(O): [2020-02-08T14:12:48Z INFO  habitat_builder_jobsrv::server] Target x86_64-windows: 0 nodes, 0 edges
builder-jobsrv.default(O): [2020-02-08T14:12:48Z INFO  habitat_builder_jobsrv::server] Target x86_64-linux: 0 nodes, 0 edges
builder-jobsrv.default(O): [2020-02-08T14:12:48Z INFO  habitat_builder_jobsrv::server] Target x86_64-linux-kernel2: 1 nodes, 0 edges
```

I would expect the `Target x86_64-linux` to have `1 nodes, 0 edges`, but as we can see `Package::get_all_latest` only returned a single item for x86_64-linux-kernel2. This is because it only considers `(origin,name)`, for uniqueness rather than `(origin,name,target)`.
