### ISSUE TITLE
Design spike for read-only access

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1304]
We want to consider what the user workflow looks like end-to-end for a read-only access scenario.

Acceptance criteria:
* Workflow should consider use case of delivering effortless packages
* Workflow should consider both web UI and hab cli usage
* Workflow should consider how this feature evolves into a full RBAC
* Workflow should consider how this feature aligns with Automate IAM
* Design mockups and flow chart created and reviewed

**Comment by eeyun** [comment]
This has been completed!
