### ISSUE TITLE
[on-prem depot] Package the depot up into the A2 installer

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#131]
The details on this are still TBD, pending a discussion with the A2 installer team.

**Comment by chefsalim** [comment]
Some notes from discussions:
- Installation should be optional
- If possible, we should re-use the postgres and nginx that is already part of A2
- If possible, hook into the backup/restore strategy for A2
- Single-node only (at least until ChefConf)

**Comment by chefsalim** [comment]
Closing for now - if this gains traction again it should be re-opened by product mgmt
