### ISSUE TITLE
[on-prem depot] Authenticate with A2

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#132]
The details of this are still TBD, pending a discussion with the A2 auth team.

Right now, we're assuming that A2 will expose a standard oauth provider and we auth with that.  That means that anything specific to GitHub in our auth process will need to be removed and made generic.  It also means that it's possible to work on this task w/o the A2 auth service being ready.  We should be able to substitute any oauth provider (e.g. bitbucket) and work against that until we're able to work against the actual A2 service.

All of these details might change, however.

**Comment by chefsalim** [comment]
Per discussion with A2 team, the current approach is to auth with A2 via the OIDC (OpenId Connect) protocol, which is essentially Oauth2 + a new id token that gets sent back along with the access token.  We will get the user account required info (name, email addr, etc) from the id token.

**Comment by cnunciato** [comment]
There's a WIP branch for the UI work to enable this here:

https://github.com/habitat-sh/builder/tree/cdn/a2-oauth

We'll also need support in builder-api that knows how to receive the provider-supplied `code` from the UI at `/authenticate/:code`, exchange it for the provider's access token, and return a Builder session token, along with whatever additional information about the user we can, either at the same endpoint or a different one. (I'd rather not have the UI making calls directly to external services.)

**Comment by chefsalim** [comment]
@cnunciato Agreed. Also, I assume we can/will send the id token in addition to the code to the authenticate endpoint?

**Comment by raskchanky** [comment]
@chefsalim Maybe it works differently in A2, but with GH and BB you just send the code.

**Comment by chefsalim** [comment]
@raskchanky With A2 we have an added id token as per OIDC Connect, so we need some way to get that token to the back end so we can figure out what user is authenticating - currently we use something like github.user but we won't have an A2 API for that.

**Comment by cnunciato** [comment]
I _think_ Dex has an endpoint for this actually &mdash; I'll see if I can dig it up.

**Comment by chefsalim** [comment]
If Dex has an API we can use it - it makes the solution more specific to the A2 implementation rather than just depending on the OIDC connect standards. OTOH it might save us some work on authz.

**Comment by chefsalim** [comment]
Re: my note above - I think we should _not_ use the Dex API, instead use the user info from the OpenId Connect.  This will enable us to also support on-prem builder without A2 with generic providers - right now we're limited to github and bitbucket, we should be able to open that up to any standard OAuth/OpenId Connect provider.

**Comment by chefsalim** [comment]
A2 provider is completed and shipped in on-prem depot
