### ISSUE TITLE
Top level user origins Packages column really means Artifacts

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/builder#1325]
As part of the recent Package settings [revamp](https://github.com/habitat-sh/builder/pull/1288) changes, we should probably consider a follow up with a clarification of what we mean by the "Packages" column of the top-level user's Origins page.

It is in truth, a count of the number of **Artifacts** that exist.
This could lead to user confusion.

![Screen Shot 2020-03-02 at 11 38 24 AM](https://user-images.githubusercontent.com/1991696/75697024-811abc80-5c7a-11ea-8d71-aafa30005490.png)

![Screen Shot 2020-03-02 at 10 21 08 AM](https://user-images.githubusercontent.com/1991696/75697064-8e37ab80-5c7a-11ea-850f-8dc211aefc4a.png)

**Comment by eeyun** [comment]
I'm looking at this and realizing I think actually we've got something else going on here. I don't know how that package count is being returned but core looks correct. So specifically i think that column is referring not to top level packages, or even artifacts. I think it refers to connected plans!

**Comment by jeremymv2** [comment]
@eeyun yeah, i snooped around and it looks like the Packages column count is coming from the `/user/origins` endpoint.

This expands to the `package_count` of the `origins_with_stats` view.
`package_count` are the entries from `origin_pacakges`: https://github.com/habitat-sh/builder/blob/7806eb97c8bc611f4244967fcc068da329597e05/components/builder-db/src/migrations/2018-11-02-111111_diesel_query_improvements/up.sql#L78-L83

**Comment by apriofrost** [comment]
Good catch! I agree that on the "my origins" page, the count under the "packages" column should reflect the count of packages (whether it has artifacts or not) in the origin.
