### ISSUE TITLE
apparent discrepancy in privacy settings display

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/builder#1327]
I may be mistaken by the intent of the UI icons and names, however, this appears to be a bug in that several indicators on the same page are apparently at odds.

![Screen Shot 2020-03-02 at 12 53 08 PM](https://user-images.githubusercontent.com/1991696/75703357-508c5000-5c85-11ea-9ee5-f1c27ce49641.png)

![Screen Shot 2020-03-02 at 12 54 18 PM](https://user-images.githubusercontent.com/1991696/75703348-49fdd880-5c85-11ea-98a2-e7fc31425dfd.png)

**Comment by apriofrost** [comment]
hi @scottopherson , when you get a chance, could you take a look at the icon display under the "latest" tab and the side panel? They should match what's selected under the "settings" tab for the default visibility.

**Comment by jeremymv2** [comment]
This is because we are not returning the `visibility` field in the Project response:
The frontend doesn't see that field so it's using a default of "Private packages".

https://github.com/habitat-sh/builder/blob/a890a7f9fc66fc8ae829eda8026a06b91e3dc64f/components/builder-db/src/models/projects.rs#L20-L37

![Screen Shot 2020-03-04 at 12 34 33 PM](https://user-images.githubusercontent.com/1991696/75906343-8dd31800-5e14-11ea-975f-741b919f2d71.png)

**Comment by jeremymv2** [comment]
@scottopherson @apriofrost it turns out that the `visibility` field in the `origin_projects` table is only for backward compatibility and the frontend should NOT be looking there. The visibility setting in that side bar, under the "Build" heading should come from the `origin_package_settings` table and therefore mirror the setting that the user toggled for the package builds:

![Screen Shot 2020-03-05 at 3 22 21 PM](https://user-images.githubusercontent.com/1991696/76022462-35277c00-5ef5-11ea-85f1-6596f39b2e45.png)

**Comment by pozsgaic** [comment]
I checked on live and acceptance, and the privacy settings are matching.  In the attachment below, the privacy setting is "Public packages", while it was previously "Private packages".

![image.png](https://images.zenhubusercontent.com/60f70d9d51d0f3ab3aca920e/a6954c5f-8975-4d5d-8a83-705a959b021a)

Below we see the Default Visibility is Public:

![image.png](https://images.zenhubusercontent.com/60f70d9d51d0f3ab3aca920e/2c0f4379-2a6d-4f3d-b26c-56f5186c37a6)

**Comment by pozsgaic** [comment]
This matches the defaults package visibility of Public in the code at that time and now.

Then:
https://github.com/habitat-sh/builder/blob/a890a7f9fc66fc8ae829eda8026a06b91e3dc64f/components/builder-api/src/server/resources/origins.rs#L199

Now:
https://github.com/habitat-sh/builder/blob/main/components/builder-api/src/server/resources/origins.rs#L186

**Comment by pozsgaic** [comment]
I changed the visibility from public to private in a test origin in the acceptance environment, and the display was consistent throughout.  Screenshots below.

![Screen Shot 2022-01-05 at 1.51.32 PM.png](https://images.zenhubusercontent.com/60f70d9d51d0f3ab3aca920e/3ecdfb1c-600a-47dd-8385-d3e04216e760)

![Screen Shot 2022-01-05 at 2.01.04 PM.png](https://images.zenhubusercontent.com/60f70d9d51d0f3ab3aca920e/18d3e950-56b7-4a90-a6c0-d81c96950528)

**Comment by mwrock** [comment]
sounds like this is safe to close.
