### ISSUE TITLE
Datastore upgrade requires manual intervention

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#1344]
If a user was running the builder-datastore service prior to #1315 , they will be unable to start the service once that version of the package has been promoted, with the following error: 

```
builder-datastore.default(SV): Starting service as user=hab, group=hab
builder-datastore.default(O): 2020-03-09 17:46:40 GMT FATAL:  database files are incompatible with server
builder-datastore.default(O): 2020-03-09 17:46:40 GMT DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 11.2.
```

This only affects existing users, and postgres itself _should_ prevent data corruption, but we need to provide manual upgrade instructions for on-prem users before the package is promoted.

**Comment by eeyun** [comment]
I think it's possible we could bypass this work. Let me know your thoughts but with a push towards a single deployment model of any builder services we could just not promote a new postgres version for the stack. The work here initially was just housekeeping anyways and wasn't a requirement for any underlying features.
