### ISSUE TITLE
Convert usage of Threads to Futures in Jobsrv and Worker 

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#1375]
In the JobSrv and Worker, we spawn threads in a number of places to prevent long-running tasks from blocking the main thread of execution.  With #1364 coming in and bringing async/await with it, we now have multiple places where we try to call async functions in inside `thread::spawn()`. This doesn't work unless you make the closure passed to spawn async so that you can `await`, but that isn't supported in stable Rust today.

To work around this in the Worker we create a Tokio runtime for each job that we spawn https://github.com/habitat-sh/builder/pull/1364/commits/393c22e43eb7b34935dd5c276f12e1b313c115a5  This is not ideal, but works as the workers only operate on a single job at a time and the cost of spawning the runtime is minute compared to the duration of execution for a build job. 

The jobsrv spawns multiple threads and its tasks are shorter lived, so the workaround used for the worker would be inappropriate. Instead, we stay pinned at Rusoto 0.42 and Futures 0.1.

The usage of `thread::spawn` can most likely be removed in all cases and replaced with `async` fns. This issue is created to track that work so that we can minimize churn in #1364.

**Comment by markan** [comment]
Some of this may be moot, in that there is a new scheduler (scheduler2.rs).
Also, it may be worth considering whether we do this or simply rework the worker code in its entirety.
