### ISSUE TITLE
unexpected UI behavior when displaying artifact versions

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/builder#1377]
A user happened to noticed some unexpected behavior in the UI when clicking on a packages "Versions" tab and expanding the releases for a particular version.

<img width="1214" alt="Screen Shot 2020-03-30 at 3 12 10 PM" src="https://user-images.githubusercontent.com/1991696/78038149-7d8e5a00-733a-11ea-95b2-e1061dad8a5d.png">

We verified with the developer tools that the backend API was responding with the expected 1 package result, however the UI was displaying multiple row entries for that specific release.

<img width="1432" alt="Screen Shot 2020-03-30 at 5 13 48 PM" src="https://user-images.githubusercontent.com/1991696/78038304-b2021600-733a-11ea-8b2f-e595d1bf5ce0.png">

Captured API response for the above screenshot:
```
{"range_start":0,"range_end":0,"total_count":1,"data":[{"origin":"chefkenny","name":"national-parks","version":"7.0.1","release":"20190626204915","channels":["stable","unstable"],"platforms":["x86_64-linux"]}]}
```

Browser:
```
Google Chrome is up to date
Version 80.0.3987.149 (Official Build) (64-bit)
```

This behavior is not 100% reproduceable and somewhat elusive, possibly suggestion an caching problem?

**Comment by SEAjamieD** [comment]
On Hold until my local has the ability to connect packages

**Comment by SEAjamieD** [comment]
Thanks to hab team for getting me unstuck here!

So far, I haven't been able to reproduce and all is looking normal in my system.  I'm gonna keep playing with it to see if I can get it mimic above and will report back in a few says.

**Comment by SEAjamieD** [comment]
@jeremymv2 - I still haven't been able to reproduce this.  Are you still seeing this happen at all?

**Comment by jeremymv2** [comment]
Going to close this as cannot reproduce.

**Comment by jeremymv2** [comment]
Thanks @SEAjamieD for helping us look into this!! ❤️
