### ISSUE TITLE
UI Integration Settings Popping Under Package settings

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#1387]
### Scenario:
Currently unable to enable external publishing integrations for packages. 

### Steps to Reproduce:
Enable an origin integration, go to a package to configure the publication to dockerhub et al.  Enable the dockerhub publishing endpoint.

![Screenshot from 2020-04-10 14-38-24](https://user-images.githubusercontent.com/12615148/79014668-63722a00-7b39-11ea-960a-540c6ddc28b2.png)

You'll notice you are unable to save the settings. The reason being there is another pop-up that should be visible after enabling the setting. When you close out of the settings tab the pop-up is there, is has rendered beneath the settings pane. 

![Screenshot from 2020-04-10 14-38-47](https://user-images.githubusercontent.com/12615148/79014811-a7652f00-7b39-11ea-8231-0b027ad84ee3.png)

Unfortunately because the actual settings have not been saved, completing the pop-under will not save to the package settings and thus the integration is unable to be used.

### Expected Result:
The configuration panel for the publication integration should pop over the settings pane so that the config values can be updated and subsequently saved by the user.

### Actual Result:
The configuration panel pops UNDER the settings pane and thus cannot be saved appropriately making it impossible to configure new publishing integrations.

**Comment by jsirex** [comment]
It looks really close to current bug in the builder: use anonymous browser and try to open ANY public package -> you will be **forced** to sign in page.. 

This is because somewhy settings tab is tried during page load..
For someone it might be blocker.

**Comment by jsirex** [comment]
Looks like I was wrong and this issue is not related, so decided to create dedicated issue: https://github.com/habitat-sh/builder/issues/1389
