### ISSUE TITLE
Dev studio: `build-builder` should start the supervisor if it's not running

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/builder#139]
Since `build-builder` replaces the binaries for existing packages, those packages need to exist. That's why the first thing `build-builder` does is check if the services are running and if not it starts them with `start-builder`. This behavior isn't triggered if the supervisor isn't running at all. In this case, it should be started with `sup-run`, then `start-builder`.

**Comment by chefsalim** [comment]
should be resolved by change in https://github.com/habitat-sh/builder/pull/734
