### ISSUE TITLE
enforce habitat package version constraints

### ISSUE THREAD

**Issue by hhodzic** [habitat-sh/builder#1407]
Filing this issue on customer's behalf:

When a package is uploaded to bldr with a malformed semver (e.g.: "1.1.0." - notice the trailing period), the database view origin_package_views will fail with a

ERROR: bad semver value '1.1.0.': empty pre-release section at char 5

The result is when searching for that package (I have tested in bldr web front end), NO packages will be returned with the result looking like they have been removed or deleted.

The command that actually did the upload (and broke the view):

hab pkg upload --url https://bldr ./results/my-pkg-1.1.0.-20200420194512-x86_64-linux.hart

I fixed this by editing the data in columns ident and ident_array in origin_packages table.

**Comment by jeremymv2** [comment]
We've also seen a package version with `..1` be upload to Builder successfully only to cause all sorts of issues later.
