### ISSUE TITLE
Private packages with a public origin visible/accessible to public.

### ISSUE THREAD

**Issue by arashzandi** [habitat-sh/builder#1408]
It seems that newly created private packages where the origin has a public default package visibility are accessible to public. The affected package has `License: Proprietary` set.

```
git clone git@github.com:habitat-sh/core-plans.git
```
Choose a simple plan (core/redis e.g.) and change `pkg_origin=<public_origin>` and `pkg_license=("Proprietary")`.

```
cd core-plans/redis
hab studio enter
HAB_ORIGIN=<public_origin>
build .
source results/last_build.env
hab pkg upload results/$pkg_artifact
rm -r results/
echo $pkg_ident
```
Exit studio and then:
```
unset HAB_AUTH_TOKEN
hab pkg search <public_origin>/redis
hab pkg install <public_origin>/redis
```

Also you can verify that the package is shown as private in Builder:
https://bldr.habitat.sh/#/pkgs/<public_origin>/redis/latest

Aha! Link: https://chef.aha.io/features/APPDL-34

**Comment by mwrock** [comment]
not stale. The settings page clearly states that after setting the package to private:

```
The artifacts do NOT appear in public search results and can ONLY be utilized by members of this origin
```

**Comment by pozsgaic** [comment]
Repeated the steps and reproduced the issue with the same result:
package visibility was "public" using the curl command above for the test package created on a public origin.

One observation was that there is no entry for  pkg_license in the results/last_build.env file.

**Comment by pozsgaic** [comment]
I created a public origin and then created an empty redis package, changing the visibility for this package to "private" before saving.  This time when I tried the curl, the visibility attribute was correctly set to "private".
