### ISSUE TITLE
Add "hab origin key list" subcommand

### ISSUE THREAD

**Issue by msuriar** [habitat-sh/builder#1409]
To find the list of origin keys I have, I need to currently do:

`hab origin key export msuriar --type=public`

This is annoying. It would be nice to be able to just list all the origins I have keys for, and the <origin>-<timestamp> values for them.

**Comment by krasnow** [comment]
@eeyun @jeremymv2  Can one of you take a look at the current state of the backend and see if this is something we could plumb in easily now?

**Comment by jeremymv2** [comment]
@krasnow the API endpoint does exist via GET `/v1/depot/origins/<ORIGIN>/keys`. It's just a matter of creating the hab cli subcommand.
