### ISSUE TITLE
Reintegrate graph-cli work into builder graph

### ISSUE THREAD

**Issue by markan** [habitat-sh/builder#1411]
We've substantially changed the graph structure to support the new cycle work.

Now we need to reintegrate this into the existing builder graph work. 

This will require:
1) Cleanups to remove obsolete and experimental code that was built as part of the research
1) refactoring the code to support the API that the rest of the builder uses
1) replacing the old code with the new
1) a full test harness for the code

This probably will involve some work around making the builder-graph library the primary repository of graph information. The intent of this to be able to merge this work into builder without needing to touch the job dispatch etc, just swap out the graph.

Known issues
1) Circular dependencies aren't currently supported by the rest of bldr-jobsrv, so we need to remain compatible
2) Cycle detection needs to be done incrementally (when packages are added or updated,  and also in a batch form. For now this should be runtime edges only (perhaps clone the graph, do detection on subset There are a lot of other constraints (origins should form a DAG) but those aren't going to be enforced for now.
3) We may want to stand up a separate builder cluster built on this work for extensive testing before merge.

This work is succesful when we have a single build graph abstraction used by both the advanced build graph CLI command and the old builder.

This does NOT include making the builder handle cyclic dependencies or build them. That will be a later unit of work.

**Comment by smacfarlane** [comment]
This work has been split into multiple cards tracked under the #1276 epic: 

#1457
#1458
#1523
#1524
#1525
#1526
#1527
#1528
#1529
