### ISSUE TITLE
Need one call that returns the full list of latest packages on a channel

### ISSUE THREAD

**Issue by gavindidrichsen** [habitat-sh/builder#1419]
## The Enhancement:

I want to use one call and return only the latest packages associated with a channel.

This feature request is related to #1418

### The Need:

This would be useful especially when attempting to verify the change or delta to a channel that has occurred.  For example, 
* I've uploaded 50 packages to my channel, how do I verify that the exact identifiers have been successfully uploaded?
* Are the latest packages on the channel equal to the ones I've uploaded?  This was an actual issue during the latest refresh, where an incorrect package core/mage version, which was greater than the uploaded package, was shadowing the new refreshed version.
* What's changed on the stable channel for the x86-linux target between yesterday and today?  

Being able to download yesterday's and today's full list allows a delta to be computed 

### Current Alternative

There doesn't seem to be an alternative that I know of.  However, this is not blocking us.  I do have a workaround at the minute which is to (1) download the full list (2) normalize the list by stripping off the version/timestamp and uniquify; (3) use the unique list and do individual curl's to Builder to obtain the 'latest' version for each.

If there are 700+ unique core/plans on a channel, then this means 700 individual curl requests are required to get the full 'latest' list for all channel packages

**Comment by markan** [comment]
It seems like an endpoint of the form:
/depot/channels/ORIGIN/CHANNEL/latest?target=TARGET
which would for ORIGIN and CHANNEL list the latest packages for TARGET would fit the bill.

@gavindidrichsen does this sound suitable.

This looks relatively straightforward to add to the existing API, and would probably make a decent first project or pairing opportunity.

**Comment by gavindidrichsen** [comment]
> /depot/channels/ORIGIN/CHANNEL/latest?target=TARGET
> a decent first project or pairing opportunity.

@markan: That looks perfect.  Yes, I'd love to pair in on this update.  Cheers!

**Comment by jeremymv2** [comment]
This looks like a great idea and I would recommend a slight modification to the endpoint:
`/depot/channels/ORIGIN/CHANNEL/pkgs/latest?target=TARGET`. 

I think the above URL more closely adheres REST semantics declaratively indicating that the action requested is on `pkgs` and not on `CHANNEL`. It would fit nicely into the existing API [endpoint](https://github.com/habitat-sh/builder/blob/75682134f5a547666f6341c53d1fe208ad219242/components/builder-api/doc/api.raml#L1262-L1295)
