### ISSUE TITLE
A single source of truth for origins

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#142]
Right now when origins are created, that's [done in builder-originsrv](https://github.com/habitat-sh/builder/blob/master/components/builder-originsrv/src/data_store.rs#L803).  As soon as the create is successful, [we asynchronously schedule a copy of the created origin to builder-sessionsrv](https://github.com/habitat-sh/builder/blob/master/components/builder-originsrv/src/data_store.rs#L824).

When someone queries for a user's origins, [they query builder-sessionsrv](https://github.com/habitat-sh/builder/blob/master/components/builder-api/src/server/handlers.rs#L521).  This leads to a case where the UI is creating an origin for a user and then needs to sleep for a second before it can query for a user's origins and have the newly created origin show up.

There's probably some historical context around why we do it this way that I'm missing, but it doesn't make sense to me that we need to do it like this.  The `origin_members` table of `builder-originsrv` stores a mapping between users and origins and is immediately up to date by the time the call to create an origin succeeds.

We should stop duplicating origins on `builder-sessionsrv` and instead change the mechanisms that currently use that data to reference the `origin_members` table of `builder-originsrv` instead.  In fact, we already have [2 protocol messages](https://github.com/habitat-sh/builder/blob/master/components/builder-protocol/protocols/originsrv.proto#L37-L43) designed to retrieve a user's origins from `builder-originsrv`, so we should utilize these.

**Comment by mwrock** [comment]
This may add some context: my recollection is that the replication of origins into sessionsrv was due to sharding constraints on the originsrv db. We could not query by account across shards in that db.

Would be great if we could eliminate this copy!

**Comment by chefsalim** [comment]
This should be resolved now with shard merge, db merge, and elimination of sessionsrv :)
