### ISSUE TITLE
Connecting plan kicks off three builds when one type is connected.

### ISSUE THREAD

**Issue by MindNumbing** [habitat-sh/builder#1420]
### `hab` CLI version
Not using CLI, using bldr web UI.

### Platform Details
Any platform

### Scenario:
When connecting a plan to BLDR on core. Adding in this case the plan.sh file in the plan settings for the first time, results in three different builds being created by builder. Those that haven't been connected immediatly fail.

### Steps to Reproduce:
Try to connect a new plan for the first time to an origin on bldr.

### Expected Result:
I would expect that, when only adding one type of plan, in this case a linux plan, that only a linux build would be kicked off.

### Actual Result:
Three builds are kicked off, one for linux, kernal2, and windows. Any that aren't connected at that time fail.

GROUP ID  | STATUS | IDENT | TARGET
1510941468868485120  Canceled  core/buildah      x86_64-windows
1510941468818145280  Complete  core/buildah      x86_64-linux
1510941468809748480  Canceled  core/buildah      x86_64-linux-kernel2

**Comment by MindNumbing** [comment]
Perhaps related, this pr generated three builds:

GROUP ID | STATUS | IDENT | TARGET
1515453161892257792 Dispatching core/rust x86_64-linux
1515453161690923008 Dispatching core/rust x86_64-linux-kernel2
1515453161523142656 Dispatching core/rust x86_64-windows

**Comment by smacfarlane** [comment]
I think this is a remnant of before Builder was able to connect plans per-target.  It used to be the case where you could only connect one plan, and the front end had no way to determine if the user wanted to build for multiple targets, so would fire off for all three possible targets. 

I _think_ this is the code in question: https://github.com/habitat-sh/builder/blob/master/components/builder-web/app/package/package-sidebar/package-sidebar.component.ts#L37-L38

Now that we can connect a plan per-target,  we should only be firing of a job for the target we just connected.

**Comment by MindNumbing** [comment]
The lines in question blame to nine months ago, but I have seen this happening just last week when adding a new plan to builder.
