### ISSUE TITLE
Design Proposal: Remove /rdeps/<origin>/{name}/group API

### ISSUE THREAD

**Issue by markan** [habitat-sh/builder#1462]
# Remove the rdeps group API endpoint

We would like to remove the /rdeps/<origin>/{name}/group API and underlying code. It is
- currently broken
- never properly represented the internal jobsrv scheduling algorithm
- the underlying framework is likely to be substantially reworked in an incompatible fashion once build time deps fully land.
- apparently unused

## Motivation

The original purpose was to expose an understanding of the build order graph for external users to consume, instead of using builder's internal jobsrv to rebuild packages. But it actually implements a different ordering algorithm. It was never meaningfully tested, and appears to be broken currently. 

We would like to remove it as we are rewriting the jobsrv build system and the new approach isn't really able to be represented in a compatible fashion. It would be nice to avoid fruitless work attempting to preserve it in the new approach.

## Specification

Implementation is simply removing the API endpoint code, and the corresponding RPC handler in jobsrv, and whatever protobuf cleanup makes sense.

## Downstream Impact

This is only available on the SaaS builder, and we only have a handful of accesses in the last month, nearly all of which is traceable to internal users. Given it's currently broken it seems unlikely anyone will be inconvenienced.

**Comment by MindNumbing** [comment]
I don't currently use the grouped rdep endpoint, and anytime I have tried to consume it for rebuild group information it has been inaccurate or outright broken. More than happy to have this removed from the API provided that the more widely used rdep functionality is left working. 👍

**Comment by christophermaier** [comment]
All the arguments for removing the endpoint sound good to me. The downside (if it even exists) seems very small, and the benefits are huge :+1:

**Comment by jeremymv2** [comment]
Let's do this 👍
