### ISSUE TITLE
[on-prem depot] UI should allow demoting packages (stable/unstable only)

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#152]
We should be able to toggle stable/unstable via the UI.
An appropriate confirmation dialog should be shown.

**Comment by cnunciato** [comment]
@ryankeairns Do you happen to have any UX I might follow for this one?

**Comment by ryankeairns** [comment]
@cnunciato I don’t, but my thought would be to show an x on hover (inside the tag, on the right end), then upon click show a conformation dialog. 

I can whip up a mockup Monday!

**Comment by cnunciato** [comment]
Fixed with #251.
