### ISSUE TITLE
add event -> webhook emmission to `builder-notify`

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/builder#1553]
With the underlying message bus libraries now fully functional, the `builder-notify` service needs the capability to emit a `BuilderEvent` to a HTTP(s) webhook endpoint. Right now the `builder-notify` service simply loops on continual consumption of event bus messages.

https://github.com/habitat-sh/builder/blob/bcb05a9efae721f9750be91a365f5c81cbaa56eb/components/builder-notify/src/server.rs#L43-L51

Completion of this work will simulate the end-to-end life-cycle of an example event as it is created via a channel promotion all the way to its delivery to an HTTP endpoint. We will then be able to begin testing the feature with early access customers.

**Comment by pozsgaic** [comment]
builder-notify has been removed.  Closing.
