### ISSUE TITLE
Create periodic "canary" jobs in Builder to surface platform issues

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#158]
@christophermaier commented on [Wed Feb 07 2018](https://github.com/habitat-sh/habitat/issues/4570)

It can be useful trigger builds periodically (say, nightly) in Builder; any failures in those jobs would show latent issues in the platform.

This is not necessarily any kind of permanent solution to monitoring the health of Builder, but can be an easy-to-implement, high-value action we can take to increase the effectiveness of our monitoring in the near term.

(This was precipitated by heretofore silent failures of the Docker export stage of builds.)

**Comment by chefsalim** [comment]
Thinking through this a bit more, a Builder Health Check is likely a better use of our resources vs. a short term canary job. In general, I prefer having checks that don't change the system state - a canary would be considered a "destructive" test. Also I'd prefer having a check that runs very frequently - eg, once a minute so we can do alerting that is timely.  We could enable a health check that would check the main points of breakage in a non-destructive manner without too much work I think.  @scotthain

**Comment by scotthain** [comment]
@chefsalim would a simple "every minute we curl the health check endpoints" job do the same thing? I know one of the concerns (at least short term) was detecting states where things "look" fine but builds are stalled. I'll obviously defer to you on the best thing we need here, but want to make sure we're covering all the criteria.

**Comment by chefsalim** [comment]
@scotthain yep that would be exactly what we would do... hook up that check to Datadog or some other outside in monitoring service.
