### ISSUE TITLE
AppArmor fixes for builder-worker

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#159]
Today we had an incident where Docker exports were unavailable due to Docker not being able to appropriately interact with apparmor. It appears that there was some change in how our worker instances booted up that impacted the interaction between Docker and apparmor. The irony is that we don't even use apparmor in our builds right now.

Though we were able to work around it by updating our Docker exporter (the new image build process didn't run afoul of apparmor), we should have a more principled way of dealing with this.

The first step would be upgrading our `core/docker` package to the latest version. This in turn will allow us to run our docker builds with apparmor constraints disabled.

Longer-term, it would be beneficial to the community at large to create a `core/apparmor` package that `core/docker` can depend on, ensuring that docker would always have access to the binaries and libraries it needs to manipulate apparmor profiles, should that be desired.

**Comment by elliott-davis** [comment]
A quickfix for this should be to add `/sbin/` to the path in the exporter so we can use the system apparmor.
