### ISSUE TITLE
Mirror the public depot

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#16]
@jtimberman commented on [Tue Aug 09 2016](https://github.com/habitat-sh/habitat/issues/1138)

As a Habitat user with network restrictions or other requirements, I want to run a Depot on my local network. To do this, I need to download all the core dependencies from the public depot or build them myself. The former is preferred as it will require less of my time, care, and feeding, and ensures that I can use known good builds of all packages. 

UX ideas

```
# mirror the entire public depot, including all origin public keys
hab depot mirror

# download a single package and its dependencies
hab depot download core/pkgname

# download an origin public key
hab depot download core
```

Open to other ideas or feedback. This would go nicely with our internal work to make the Depot easier to run for people.

---

@bdangit commented on [Tue Aug 09 2016](https://github.com/habitat-sh/habitat/issues/1138#issuecomment-238600076)

yes! 👍

**Comment by raskchanky** [comment]
We are actively working on officially supported on-prem depots right now.  That work is happening [here](https://github.com/habitat-sh/on-prem-builder).  That is a private repo for now, but will most likely be open-sourced at some point.  Additionally, there is work in progress [here](https://github.com/habitat-sh/builder/issues/150) to support pulling packages from an upstream depot if your default depot doesn't contain said packages.  Both of those should address this issue.
