### ISSUE TITLE
Surface Github API errors more explicitly

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#160]
Lately, we've been seeing throttling of our use of the Github API in Builder, which has negatively impacted the apparent stability of the platform for our users.

To better understand the exact ways this is affecting us, we should more explicitly surface Github API errors (e.g., in logs).

**Comment by chefsalim** [comment]
Github API errors are getting logged and also show up in Sumologic.
We can do a scrub to see if there's any that are missed getting logged currently..
