### ISSUE TITLE
Builder High Availability (Research)

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1623]
Currently Builder is having high availability issues for certain customers like Walmart because it is setup as a standalone instance. Example is the ticket : https://getchef.zendesk.com/agent/tickets/28578

Scope of Analysis:
1) How is ngnix setup and acting as reverse proxy
2) Do we cache any data locally and how do we manage caching of data in memcached ?
3) how to move Postgres to different cloud provider (AWS/ Azure Cloud) ? One of our customers is trying to move the instance to Azure and isn't able to do that because of RUST incompatibility. We need to be able to provide an ability to do this.

**Comment by mwrock** [comment]
some observations:

```
**Automate**
- wraps old 2018 pinned versions of builder
- separate load balancer with unconfigurable timeouts sits in front of builder nginx
- Has a separate configuration and secrets management mechanism wrapping hab config
- deployment and setup managed by automate's own go codebase
- automate has an HA strategy that does not include any builder components
- No major customers are using this deployment
- manages backups

**standard on-prem builder**
- managed by habitat team
- deployment code is bash based
- supports HA:
  - external postgres/minio/artifactory
  - front end scaling
- configuration, backup and maintenance is DIY

**General Notes**
- Given Automate's customized deployment, a single HA solution will not work in both deployment models (automate and on-prem)
- Taking the automate route will be governed by automate's release schedule
- An automate HA either needs to be engineered by the automate team, or allow for significant hab team resources
- Ideally an automate strategy should conform to the same patterns used by automate/ha
- Customers must be willing to migrate to automate if we roll out an automate/builder HA
- On-prem builder has the support for a DIY based HA but we can create scripts to standardize HA configuration and maintenance
- On-Prem builder can be developed independently by the hab team and at a more rapid pace
```

**Comment by rahulgoel1** [comment]
HA Builder : In our call with CA/ Field team there was a a mention that customers are setting up sticky sessions when they are running on prem builder in HA setup. Our SAAS builder is setup without any sticky sessions on load balancer. This was bit of surprise for me and I did talk to Matt on it . I had a quick chat with our Customer architects and here are the use case they mentioned requiring sticky sessions:
If they log in with Github or other Oauth function the sessions gets terminated and customers are put in an endless loop to log in over and again. This has been avoided by setting up sticky sessions on load balancer.
Customers have a process where they push new hart file to on-prem builder and a next step where they invoke builder API to verify that the updated package is present. Most of time the second call is not immediately successful as the second call hits a different node( when sticky sessions is not configured). This has been solved by setting up sticky sessions.

**Comment by rahulgoel1** [comment]
Additional items which needs to be analyzed further:
1) Test bed for performance testing of builder
2) The team would like to begin with scaling out Builder API

**Comment by rahulgoel1** [comment]
I and @mwrock  discussed and we think the sticky sessions is pretty much real for our customers. The reason on-prem depot is running into sticky sessions is because supervisor is not peered in the ring , so the memcache service running on each node is pretty much a standalone instance . This causes individual builder node to talk to each of the memcache service ( simulating a local cache vs distributed  cache). This causes sticky session on the on-prem depot. We will get into a call with our CA / Field team next week to have next steps on it. @sajjaphani Basically this resolves the sticky session use cases. We still need to analyze further on the performance test bed.

**Comment by rahulgoel1** [comment]
Here is the list of issues which we are planning to take up after completing our initial research and analysis : 
1) First version of the design Document ( scaling out front end nodes with single instance of postgres and minio)
2) Build the Highly available builder (on prem setup)
3) Load test using existing load workbench ( Research / Analysis)
4) Document for end users.
5) Upgrading postgres version to the latest one for builder.

**Comment by rahulgoel1** [comment]
HA Builder work items after discussing with Field team:
1) Scale Front End Nodes
2) Create separate cluster of Memcache nodes
3)HA setup for postgres
