### ISSUE TITLE
createdb error when database user has limited permissions

### ISSUE THREAD

**Issue by moutons** [habitat-sh/builder#1633]
### `hab` CLI version
```
[root@hostname1 ~]# hab --version
hab 1.6.181/20201030172917

root@hostname1 ~]# hab pkg list --origin habitat
habitat/builder-api/9034/20200827185135
habitat/builder-api-proxy/8997/20200812161534
habitat/builder-memcached/8880/20200430062921
```

### Platform Details
Oracle Linux 7

### Scenario:
When starting builder when the database user has limited permissions, an error state is encountered and the OR isn't properly handled.

### Steps to Reproduce:
Get bldr set up.
Set up an external postgresql DB where the users have limited permissions and all the necessary schemas exist, then grant limited permissions:

`grant usage on schema public to chef_user,chef_readuser,chef_rwuser;`

Restore a database backup to the external DB

`hab svc start habitat/builder-api`

### Expected Result:
Based on the code, one would expect the createdb to fail, but since the documented schemas required are created, installation/startup should proceed normally.

### Actual Result:

```
Oct 11 16:00:43 hostname1 hab[95467]: builder-api.default hook[init]:(HK): createdb: database creation failed: ERROR: permission denied to create database
Oct 11 16:00:44 hostname1 hab[95467]: builder-api.default(SV): Starting service as user=hab, group=hab
Oct 11 16:00:44 hostname1 hab[95467]: builder-api.default(O): thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "permission denied for schema public")', components/builder-db/src/migration.rs:37:5
```

**Comment by mwrock** [comment]
fixed by #1634
