### ISSUE TITLE
Customer Bug : Wabtec - Hab supervisor failed to install

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1648]
Customer Bug :  https://getchef.zendesk.com/agent/tickets/28967
https://github.com/chef/customer-bugs/issues/501

**Comment by mwrock** [comment]
Issue moved to [habitat-sh/habitat #8359](https://github.com/habitat-sh/habitat/issues/8359) via [**ZenHub**](https://www.zenhub.com/)
