### ISSUE TITLE
Builder Docs to updates API specs at docs.chef.io

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1662]
Problem Statement : Docs.chef.io has Builder API Docs at https://docs.chef.io/habitat/builder_api/. Currently the docs are being generated from a json file which is not generated automatically. The json is here :- https://github.com/habitat-sh/habitat/tree/main/components/docs-chef-io/static/habitat-api-docs.

What to do ? We would like to automate the generation of API Docs from builder so that the docs, api specs are in sync.

**Comment by mwrock** [comment]
Looks like when this was generated, there was talk of automating in the future: https://github.com/habitat-sh/habitat/pull/6729

**Comment by pozsgaic** [comment]
I tried to run this on the Mac but it did not work.  
I notice that there is some windows references in the Gemfile so will
try to run on an EC2 Windows instance

**Comment by pozsgaic** [comment]
I managed to get it working on Mac after commenting out the windows specific part and
re-installing the xcode-select and updating gem.  

It appears that this Habs doc website was removed a year ago:
https://github.com/habitat-sh/habitat/pull/8055

**Comment by pozsgaic** [comment]
I think that the source of truth are the api.raml files located in the respective repos:
builder:  components/builder-api/docs/api.raml
habitat:  components/habitat/docs/api.raml

I ran a raml-json converter on the builder api.raml file and compared the generated file to our builder-api.json and
found that the json file that I generated was a superset of the builder-api.json file.
So the builder-api.json we have is out of date.  

Based on the git history of the builder api.raml file, this file gets updated along
with the Rust code when a route is added, updated, or deleted.  Here is an example:
https://github.com/habitat-sh/builder/pull/1504
https://github.com/habitat-sh/builder/pull/1444

So if the api.raml file is current and then we could generate the builder-api.json file from it and
we would be in sync.   



git log --all --full-history -- $1

**Comment by pozsgaic** [comment]
Documenting here the places where the habitat api.raml is out of sync. This assumes each route should have an implementation in the habitat backend code.  

Missing routes:
1). components/sup/src/http_gateway.rs - there is no content for "metrics" in the habitat api.raml file

Other issues:
- Naming inconsistent between the raml file and the code.  Raml has services/{name}/{group} while the code has services/{svc}/{group}.

**Comment by pozsgaic** [comment]
The utility for converting raml to json (on MacOS):
oas-raml-converter

**Comment by pozsgaic** [comment]
There is a delta between the generated json file and what is in the repository

 {
-  "openapi": "3.0",
+  "openapi": "3.0.0",
   "info": {
-    "title": "Chef Habitat API Documentation",
-    "version": "",
-    "termsOfService": "https://www.chef.io/terms-and-conditions-of-use/",
-    "contact": {
-      "email": "support@chef.io",
-      "url": "https://www.chef.io/support/"
-    },
-    "x-logo": {
-      "url": "/images/habitat-logo.svg",
-      "altText": "Chef Habitat logo"
-    },
-    "license": {
-      "name": "Apache 2.0",
-      "url": "https://github.com/chef/automate/blob/master/LICENSE"
-    }
+    "title": "Habitat Supervisor",
+    "version": "undefined"
   },

Not certain if there is manual editing required but it seems that way.

**Comment by pozsgaic** [comment]
I am having some difficulty installing and setting up oas-raml-converter for Linux.  We want to automate this and run it automatically as part of release process.  
I am running the following from Ubuntu 18.04:
1) sudo apt install curl
2)  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
3) npm i webapi-parser
4) npm i -g oas-raml-converter.

When I try to run the oas-raml-converter,  I get this error:
/usr/bin/env: ‘node --harmony’: No such file or directory

I see a similar error from searching the internet from a few years back but want
to be able to handle without having to change any files manually.
https://github.com/mulesoft/oas-raml-converter/issues/13

**Comment by pozsgaic** [comment]
This commit shows the delta in content between the generated version from running the oas-raml-converter to the version in the repo.

https://github.com/habitat-sh/habitat/commit/1f8998190db87cda9e13ad3d205ed44b482e27fc#diff-bf2d90d75dac627d37e07a3ac512c216da645748c790eb0cdd302a6395386a55

**Comment by pozsgaic** [comment]
Looking into the .expeditor scripts I notice that in website.pipeline.yml the main step to deploy is to invoke
the script [website-deploy.sh](https://github.com/habitat-sh/habitat/blob/main/.expeditor/scripts/website-deploy.sh).
Inspection of this script, it is assumed that beneath habitat root directory, there is a "www" subdirectory.  This directory does not exist in the main branch (it was deleted).

**Comment by mwrock** [comment]
I remember at some point `www` was removed in favor of the `docs-chef-io` directory. So I don't think the website pipelines are being used at all. As part of this I'd suggest removing the pipeline yml files, the scripts they call, and the pipeline definitions from the `config.yml`.

**Comment by pozsgaic** [comment]
There is a syntax change from RAML 0.8 to RAML 1.0.  I created snippets of a RAML 1.0 file and was able to convert.  
For example, the _schemas_ keyword has changed to _types_ as in the sample declaration below:
0.8:
schemas:
    - netError: |
        {
            "properties": {
                "code": {
                    "type": "integer",
                    "required": true
                },
                "msg": {
                    "type": "string",
                    "required": true
                }
            }
        }
1.0:
types:
  netError:
    type: object
    properties:
      code: 
        type: integer
      msg:
        type: string

I will try to find a conversion tool from 0.8 to 1.0

**Comment by pozsgaic** [comment]
Using an online converter, I was able to iteratively determine the cause of the conversion error.  
https://mulesoft.github.io/oas-raml-converter/

The line:
https://github.com/habitat-sh/builder/blob/main/components/builder-api/doc/api.raml#L1309
was missing the "|" symbol.  The needle in the haystack has been located.

**Comment by pozsgaic** [comment]
Converter succeeded but dropped 5 of the 12 root routes in builder api.raml
Manually adding the missing "|" placated the converter but we still need to resolve the missing content.

**Comment by pozsgaic** [comment]
Using this to see the routes in the api.json file:
_cat api.json | jq -r .paths | jq keys[]

And this to count the number of routes in the api.json:
_cat api.json | jq -r .paths | jq keys[] | wc -l_

I generated the json output files manually and found the routes to be the same and the count is equal (63)
