### ISSUE TITLE
bump rust-toolchain to 1.56.1 and adjust plans to use it

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/builder#1664]
Like we have done in the habitat repo, we should bump to 1.56.1 and we should also edit all the plan files to ensure that rust version is used in package builds.

**Comment by pozsgaic** [comment]
The manual build failed for builder-notify when moving to 1.56.1 and was not picked up in our buildkite tests.   Manually building all packages that do not have coverage on buildkite.
