### ISSUE TITLE
Version Scanner to detect Minor Version/ Major Version Upgrades

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1666]
Problem Statement : How to identify minor version upgrades as different packages can have different version schemes ?

Design Ideas : We can have different algorithms which can be configured and plugged into our system which can be mapped to one or more than one package based on versioning scheme. For example we could begin with 2 algorithms one for packages following sem versioning and other for packages which follow another versioning scheme.

**Comment by sajjaphani** [comment]
Not all Habitat packages follow semantic versioning.
Below are a few examples:
name: openssl
current_version: 1.0.2zb
name: kmod
current_version: 28
name: openresty
current_version: 1.19.3.1
name: minio
current_version: 2021-03-17T02-33-02Z
name: camlp4
current_version: 4.12, latest_version: 4.13+1
name: openssh
current_version: 7.9p1

We cannot find a tool to parse each version scheme.
For some packages, each minor version change needs to be handled separately (E.g, Python)

If we follow the semantic versioning scheme, we should be able to address the majority of the packages, leaving the rest as corner cases.
These corner cases can be handled case by case separately.

**Comment by rahulgoel1** [comment]
@sajjaphani  Sounds good to me. Thanks.
