### ISSUE TITLE
add test coverage for builder-notify

### ISSUE THREAD

**Issue by pozsgaic** [habitat-sh/builder#1669]
- Component builder-notify has a rust build dependency, but does not appear to have buildkite coverage.
- A manual (hab pkg) build failed for this component and the plan file was updated to add missing build dependency.

**Comment by rahulgoel1** [comment]
@pozsgaic  I think we can close this one out. In my opinion it would be better to remove the code and functions related for builder notify. @mwrock  I feel that we should clean up some of the components which we aren't planning to use . This will help avoid confusion in future. Pls share your thoughts.

**Comment by pozsgaic** [comment]
Agree.  I was not aware at the time of issue creation that we were not using this service.

**Comment by mwrock** [comment]
Agreed! I think @pozsgaic submitted #1679 to address its removal.
