### ISSUE TITLE
Upgrade Builder Postgres to Version 13

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1678]
- [ ] Research different versions of postgres and select the version which we can  upgrade ( Our timeline is 30 jan 2022 , AWS is pulling support for postgres version 9.X on 30 jan 2022)

- [ ] testing strategy needs to be decided.

**Comment by mwrock** [comment]
We are currently using postgres 11.2 both in aws and [onprem](https://github.com/habitat-sh/builder/blob/5298517e6da96ccc8b2c6029c9dc63bf937e312d/components/builder-datastore/plan.sh#L3). The community EOL date for v11 is 11/14/2023 which gives us another 2 years of support.

We should keep this issue open and consider upgrading before too long but I don't think this is urgent at all.
