### ISSUE TITLE
Builder autobuild is failing if plan origin does not match origin on builder

### ISSUE THREAD

**Issue by pozsgaic** [habitat-sh/builder#1684]
### `hab` CLI version
[Version of the habitat binary where you are encountering the issue]
hab 1.6.319

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Linux 18.04

### Scenario:
[What you are trying to achieve and you can't?]
Publish a package to acceptance and have autobuild performed on git push.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using the CLI or Builder UI?]
1). Clone a habitat plan enabled github repo, noting the organization name and package name in plan.sh file.
2)  On acceptance builder UI, create an origin that does not match the name in the plan.sh file.  Then create a package whose name matches that in the plan.sh file.
3) Select "Build Latest Versions" and observe build on UI.
4) Make a change to the github repo and push the changes.  
### Expected Result:
Expecting the build to kick off and either succeed or fail.

### Actual Result:
Log entry is added in the builder-api log: "Failed to fetch project (plan may not be connected)"

**Comment by mwrock** [comment]
My suggestion here is that we make it so that the build works if the origins differ instead of fixing this via validation. If the origins do differ, it should build under the origin in bldr which is how the "build button" would behave.

**Comment by pozsgaic** [comment]
Looking at the builder code:
https://github.com/habitat-sh/builder/blob/main/components/builder-api/src/server/services/github.rs#L224
The origin and the name are used to lookup the plan in the database, and if these don't match, it will fail.
We have the origin that was specified in the plan file that we can use to create a new project.

**Comment by mwrock** [comment]
I don't think we want to use the origin in the plan file but the origin that the plan is associated with in builder. Basically we want to be consistent with the behavior of when someone clicks the "build latest" button or runs `hab bldr job start`.

**Comment by mwrock** [comment]
After talking with @pozsgaic offline, it seems that there is no way to the builder origin that the plan was "connected" to if the origin in the plan differs. The webhook payload simply does not provide us with that information nor does it seem possible to add it. Given this, I'm not sure how we can improve on this without making significant changes to the builder flow. If it can't find the project, well, then it can't find the project and because it is no UI or customer accessible log to surface that error to.
