### ISSUE TITLE
Create a builder script for Linux builds

### ISSUE THREAD

**Issue by pozsgaic** [habitat-sh/builder#1687]
We currently have a build.ps1 script in the builder repository, but do not have a similar build script for Linux builds.

Create a build script that can properly set up the environment as is done in build.ps1 and in the test/run_cargo_test.sh script.

**Comment by mwrock** [comment]
I think this is a good suggestion. I'd suggest it be accesible from the `makefile` so you could run a `make build` and have it build.

**Comment by pozsgaic** [comment]
Good idea.  Since some of the make targets do not currently build successfully, we should ensure as part of this effort that we can build all of our components using make.

**Comment by pozsgaic** [comment]
duplicate - closing
