### ISSUE TITLE
A problem in visiting a package with full ident

### ISSUE THREAD

**Issue by sajjaphani** [habitat-sh/builder#1728]
Navigating to a package ident from the browser URL is showing incorrect details. It is not a problem if we first navigate to a package versions page and choose a particular version.

https://bldr.habitat.sh/#/pkgs/habitat/builder-api/10024/20220211151009

It is causing because when we visit the package ident, the UI is fetching the latest package instead of the package with the fully qualified ident.

The same can happen when refreshing a page with a fully qualified ident.

The fix is to fetch the package metadata with the fully qualified ident and then fetch the channels.

**Comment by mwrock** [comment]
fixed via #1791
