### ISSUE TITLE
Origin support to unlist packages

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#18]
@lilianmoraru commented on [Mon Jul 11 2016](https://github.com/habitat-sh/habitat/issues/1051)

Currently there is no way to remove a package(unless there is good reason).

I propose `habitat` to support unlisting packages, like `crates.io` does.
The idea is that some packages might be broken or some other issues might appear with them.
The person that published that package might release another version with a fix and desire to unlist the broken package, currently this is not possible.
After unlisting, the package will still be present and work for those that specifically select to use that version, but it will not be available/visible to new users.

---

@eeyun commented on [Tue Dec 20 2016](https://github.com/habitat-sh/habitat/issues/1051#issuecomment-268356484)

This is absolutely something that we're going to want to take on. Thank you for opening the issue and we'll come back to close this circle when we have it implemented.

---

@lilianmoraru commented on [Tue Dec 20 2016](https://github.com/habitat-sh/habitat/issues/1051#issuecomment-268395768)

I gave these examples but the main reason I opened this was because there were to many old versions of packages and it was really confusing when trying to search for a package(example: search for `gdb`).

---

@gfodor commented on [Sat Sep 23 2017](https://github.com/habitat-sh/habitat/issues/1051#issuecomment-331661983)

+1 for this, we had a mis-naming of one of our packages ("libopus" vs "opus", a redistribution of the opus codec) and now we have the "libopus" (wrong) package floating around. not the end of the world but confusing until we can unlist it.

**Comment by eeyun** [comment]
I think it's possible that we could close this out. @gfodor and @lilianmoraru you can now delist packages in builder by setting a package to private! This should make it unsearchable for anyone outside of your origin. If this solves for your usecase let us know and we'll close it out, if not lets get some more details on requirements here.

**Comment by st-h** [comment]
This would be extremely useful. Currently one single error in publishing a package (e.g. a wrong version number) will blow up the UX of the builder UI:

- the incorrectly published pkg will always show up as the latest package (there is no way to hide it or undo publication)
- the versions tab prominently displays the invalid package at very first position, so you will never forget that one day someone made a mistake unless you hopefully will reach that version number one day
- there might be other related issue regarding if the date of a publication or the actual version number makes a package count as newer which might cause other issues: https://forums.habitat.sh/t/how-to-revert-a-published-package-with-incorrect-version-number/809/7 while being able to remove a package will probably not solve any other issues, it will at least give us a way to return to a consistent state.
