### ISSUE TITLE
[builder-web] Support configurable Oauth URLs (no hardcoding)

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#186]
Acceptance criteria:
1. There should be no hardcoded reference to github URLs in the web UI
2. All auth URLs should come from a configuration (including our internal endpoint that we call to exchange the code for a token).
3. The on-premise and dev docs are updated to reflect how to add this configuration

**Comment by chefsalim** [comment]
Open : should we also add a configuration for an OAuth provider type so the UI can trigger specific behavior based on type?  Eg, if we know the type is Github, then we can execute the flow for Github app based behavior when needed.

**Comment by cnunciato** [comment]
Fixed with #230.
