### ISSUE TITLE
[Epic] On-Prem Authentication

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#189]
This epic is to track the work to support authentication with providers other than github. Specifically:
1) Support Oauth providers other than github (Atlassian bitbucket, etc).
2) Support OpenID Connect for A2 integration

Background: Currently we are hard-tied to the hip with github and Github apps. Github app support is technically only needed for linking plans for builds, however we go through the Github app auth even when the plan linking functionality is not required (eg, for on-prem).  We need to de-couple ourselves from github, and develop a more flexible authentication solution that can support a variety of providers used commonly in the enterprise.  Later, we also need to decouple the VCS source repositories away from github - that is not the immediate work in this epic but we should consider it during the revamped designs.

**Comment by raskchanky** [comment]
Since all the issues on this epic are closed, I'm going to close it as well.
