### ISSUE TITLE
Fix or remove skipped tests from Builder API suite

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/builder#201]
After https://github.com/habitat-sh/builder/pull/124, there are [145 passing tests and 44 pending](https://travis-ci.org/habitat-sh/builder/jobs/341057980). We should either make the 44 pending pass or remove them if they're not valuable.

**Comment by chefsalim** [comment]
Now, almost all of the 44 skipped tests have been re-enabled or removed -we have only about 4 or so skipped, which will be resolved in time.
