### ISSUE TITLE
[on-prem] Add support for HTTP/S proxy to github client

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#207]
Currently, the builder services are not able to support outbound access via a proxy.  This is because hyper does not support environment proxies, and has to be explicitly configured to add a proxy during client setup.

Without this change, things like github authenticate will fail.

The simplest change will probably be to have the github-api-client (in the habitat repo) pick up proxy environment variables and inject them into the hyper client.

Link to sample hyper code: https://github.com/hyperium/hyper/blob/v0.10.13/src/client/mod.rs#L124

**Comment by raskchanky** [comment]
Just to be explicit, according to the curl manpage, the environment variables in question (with example values) look like this:

```
HTTP_PROXY = http://myproxy.com:8080
HTTPS_PROXY = https://myproxy.com:8080
```
