### ISSUE TITLE
[builder-web] Add build alerts to UI

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#21]
@tashimi commented on [Thu Apr 27 2017](https://github.com/habitat-sh/habitat/issues/2185)

When a user has a package that has dependencies that have more recent builds than the user's most recent build of their package, the UI should show a visual cue to indicate that the user needs to take an action to rebuild their package and take advantage of this newer version. 

This will require API & front end work. 

---

@ryankeairns commented on [Thu Sep 21 2017](https://github.com/habitat-sh/habitat/issues/2185#issuecomment-331197454)

@tashimi can we remove the Pre-Neighborhoods milestone from this issue (UI alerts)?

---

@tashimi commented on [Thu Sep 21 2017](https://github.com/habitat-sh/habitat/issues/2185#issuecomment-331204031)

@ryankeairns Sure, but let's create a follow up milestone because notifications is important and should be done short term (I would prefer to have it done by the end of October)

---

@ryankeairns commented on [Thu Sep 21 2017](https://github.com/habitat-sh/habitat/issues/2185#issuecomment-331209236)

Done, added an On Deck milestone.

---

@tashimi commented on [Mon Oct 02 2017](https://github.com/habitat-sh/habitat/issues/2185#issuecomment-333654628)

Fletcher would like to request a "Builder kicked off a build of xxx" in Slack

Aha! Link: https://chef.aha.io/features/APPDL-14

**Comment by eeyun** [comment]
This is being looked into - it's not stale, so, I'm leaving a comment. Damn you stalebot!

**Comment by sajjaphani** [comment]
This isn't stale
