### ISSUE TITLE
existing origin members cannot invite new members to origin(s)

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/builder#231]
Neither of our member accounts for the `smartb` origin can invite new members - we get an "Unauthorized" error:

https://bldr.habitat.sh/#/origins/smartb/members

![screen shot 2018-02-27 at 14 55 59](https://user-images.githubusercontent.com/16775146/36732556-5e62976a-1bce-11e8-8553-9c0ac69853e6.png)

**Comment by raskchanky** [comment]
@smartb-pair It's possible that you're running into an instance of a bug that was recently fixed, but hasn't been deployed to production yet.  https://github.com/habitat-sh/builder/pull/217

Can you try having the people you're trying to invite login to Builder first, then try to invite them again?

**Comment by elliott-davis** [comment]
Closing. Please re-open if this is still an issue
