### ISSUE TITLE
Super tiny hover text on Firefox Mac

### ISSUE THREAD

**Issue by onlyhavecans** [habitat-sh/builder#234]
I am on a Mac using latest Firefox 58.0.2 (64-bit) and the hover tooltip text is suuuuuper tiny. These old eyes have trouble reading this.

![screen shot 2018-03-01 at 10 32 44](https://user-images.githubusercontent.com/718435/36863065-861d4ce4-1d3d-11e8-944a-955d4b36f7cd.png)
![screen shot 2018-03-01 at 10 32 59](https://user-images.githubusercontent.com/718435/36863070-8979fbd0-1d3d-11e8-876a-c3e5a22a397f.png)

**Comment by elliott-davis** [comment]
@ryankeairns do you have any opinions on this?

**Comment by ryankeairns** [comment]
It could certainly be improved, though it doesn't directly block the capabilities of this feature. I can provide a mockup and/or make the change.
