### ISSUE TITLE
[builder-web] Improve plan-connection experience

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#253]
A few users have mentioned that it's unclear what's supposed to happen after connecting a plan to GitHub. The current behavior is that once a plan is connected, either a merge to the target branch or a click of the `Build Latest Version` button is required, but the UI doesn't make this clear, which leaves users confused.

We should either trigger a build immediately on connect or document what needs to happen next in order for the user to experience a first build.

cc @ryankeairns

**Comment by ryankeairns** [comment]
We tested it both ways in the original prototype and users did seem to prefer an initial build as you suggest. It was something that got put aside during the rush to that big release.
