### ISSUE TITLE
Docker build failed when trying to publish to Docker Hub Container Registry

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#255]
@tgj commented on [Mon Mar 05 2018](https://github.com/habitat-sh/habitat/issues/4705)

While going through the second tutorial in Habitat 101 (under the Learn tab at https://habitat.sh/), I encounter the following issue when trying to publish to the Docker Hub Container Registry.

Cannot connect to the Docker daemon at unix:///hab/svc/builder-worker/data/931311898694369280/dockerd/var/run/docker.sock. Is the docker daemon running?
✗✗✗
✗✗✗ Docker build failed with exit code: exit code: 1
✗✗✗

Any ideas why this would be happening? I have given Docker permissions for GitHub, and I don't have 2FA enabled. 

Also, the build passes when I remove the Docker Hub integration.

I've attached the build log here:
[build_log.txt](https://github.com/habitat-sh/habitat/files/1782783/build_log.txt)

---

@eeyun commented on [Mon Mar 05 2018](https://github.com/habitat-sh/habitat/issues/4705#issuecomment-370629271)

We'll have to look at this but it's very likely a serverside issue with the latest version of docker. I'll try and give this a full triage tomorrow.

**Comment by tgj** [comment]
Managed to successfully complete the tutorial with the changes you guys made. 🔥🔥🔥

**Comment by fnichol** [comment]
Awesome to hear, thanks for follow up!

**Comment by eeyun** [comment]
@fnichol I'm not 100% certain we want to close this just yet. Right now we've pinned the version of the docker package our workers are using to avoid the issue. I think the actual solution here is to replace the docker package in our workers with `img` and `runc`.

**Comment by eeyun** [comment]
This issue is actively being worked right now. @elliott-davis  just told me you can hold him accountable for this getting fixed. We have another tracking issue for this where we are actually following this work so we're going to close this one out. I'll add the link to the other issue momentarily.
