### ISSUE TITLE
Audit our dependencies

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#265]
Lately, when I've had to update dependencies for one library or other, I've noticed that other dependencies will dramatically change as well, often _downgrading_ to much older versions (this seems to happen with `serde`, but also with `base64`, and a few others). The resulting dependency set yields code that won't compile.

This can be worked around by manually tweaking the `Cargo.lock` file, but that's obviously not sustainable. We should make an audit of our dependencies and figure out what is causing the spurious behavior, and fix it (or, failing that, at least document it until it can be properly fixed).

**Comment by raskchanky** [comment]
@christophermaier I've noticed this behavior as well, most egregiously with serde.  I've started putting `>= 1.0` in the version constraint for serde in a few different crates (vs the `*` that's there now), as for reasons that I can't comprehend, cargo keeps reverting serde to a 0.8.x version.  Keeping it above 1.0 though, seems to fix things.

**Comment by fnichol** [comment]
I noticed the same and was going to see if setting version constraints in our Cargo.toml filed might help the resolver or expose a manual version pin that we’ve accidentally made by handling the Cargo.lock files.

I’d volunteer to look into this unless someone gets there first

**Comment by chefsalim** [comment]
The dependency audit and cleanup is done.  The downgrade issue is confirmed to be a bug in cargo.
