### ISSUE TITLE
Create new user metric dashboard(s) in DataDog

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#268]
@apriofrost has been compiling lots of user data on Builder lately, but it's been a very manual process.

Now that we're starting to instrument the platform more completely, we may be able to extract a number of the metrics we want directly from DataDog.

We should see what user metrics we want to capture, determine how we might instrument the platform to capture them, and create dashboards to expose these metrics in an intelligible manner.

**Comment by chefsalim** [comment]
May be nice to have, but does not seem like a priority atm.  This is probably also not a Datadog thing where we are mostly monitoring the service health.  Re-open when/if there is a clear product ask and prioritization.
