### ISSUE TITLE
Investigate tracing technology (particularly OpenTracing) for Builder

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#269]
In the interest of more fully instrumenting the Builder platform, we should investigate adding tracing technology across our services.

DataDog provides tracing through it's [APM](https://www.datadoghq.com/apm/) offering. This is compelling because our metrics are already aggregated there. However, it doesn't appear to use the [OpenTracing API](http://opentracing.io), a vendor-neutral tracing API from our friends at CNCF, which entails vendor lock-in.

There is a Habitat-packaged Jaeger client (CNCF OpenTracing System: https://github.com/jaegertracing/jaeger), home-grown here at Chef, which could be useful: https://github.com/chef/habitat-jaeger-agent)

**Comment by raskchanky** [comment]
What's odd though is if you look at the OpenTracing API home page, it specifically calls out Datadog as a "supported tracer", so maybe it's possible after all?

**Comment by raskchanky** [comment]
Related to OpenTracing and Datadog, I found these:

https://github.com/gchaincl/dd-go-opentracing
https://github.com/savaki/datadog

Both are in Go, which doesn't directly benefit us, though it does seem to indicate that it's possible to use the OpenTracing API with Datadog.

**Comment by christophermaier** [comment]
@raskchanky oh, maybe I just can't read 😦 If they support OpenTracing, then that makes things a no-brainer

**Comment by raskchanky** [comment]
![image](https://user-images.githubusercontent.com/947/37165620-efc6a860-22b1-11e8-9c24-59edb8546f73.png)

**Comment by raskchanky** [comment]
And yet they're not listed [here](http://opentracing.io/documentation/pages/supported-tracers.html).  So yeah, I think your reading skills are working fine.  😁

**Comment by eeyun** [comment]
I would guess since we no longer have microservices, are moving to direct db calls for most activities we probably can close this?

**Comment by raskchanky** [comment]
Seems fine
