### ISSUE TITLE
Add gauge metric for Github API rate limit

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#270]
Now that we're instrumenting our Github API calls, we can go a step further and expose our current rate limit. Per [the documentation](https://developer.github.com/v3/#rate-limiting), rate limit information is exposed in the HTTP response headers.

Once the tagging work described in https://github.com/habitat-sh/builder/issues/267 is complete, and we can take action based on which installation ID we're making a request for, we can expose our installation's current rate limit as a gauge metric. We don't need to track rate limits for anyone else; this would just be for our installation.

(Well, strictly speaking, this is not blocked by #267, but the logic for determining which installation ID we're dealing with is described in the discussion there, so check it out if you pick this issue up).

**Comment by chefsalim** [comment]
The rate at which we are calling github dropped dramatically after introduction/adoption of personal access tokens, so we probably don't need to spend any more time on github metrics atm.  Will re-consider if anything else changes.
