### ISSUE TITLE
Add metrics around exporter integrations usage in Builder

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#272]
For our own purposes, as well as partner development, it'd be nice to expose some basic metrics around the number of users that are taking advantage of our various exporters (Docker, ECR). 

We could increment a counter when someone adds an integration, decrement it when they disable it, record the number of builds successfully using it, etc.

**Comment by tashimi** [comment]
This would be great! Could we extend it for all our exporters & publishers?

**Comment by christophermaier** [comment]
@tashimi All the ones in Builder, at any rate... I was thinking of StatsD metrics, and not any kind of "phone home" telemetry from individual users out in the world. If _that_ is what you're after, that's a bigger lift.

**Comment by chefsalim** [comment]
I'm not sure datadog metrics are the thing that we want here.  The volume of these activities are low.  

We can start with a back end analysis of the data - for example, the project integrations from the DB:

```
select origin, count(*) from origin_project_integrations group by origin order by origin;
```

will show us the number of projects that have exports (integrations) set up.

Closing for now - we can re-open when there is more clarity from product on what we need.
