### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#28]
@chefsalim commented on [Thu Jul 06 2017](https://github.com/habitat-sh/habitat/issues/2693)

1. We need automated disk and database backups
2. We need a reliable way to do snapshots (if snapshots are the backup strategy) 
3. Look into implementing Postgres DR / backup solutions (someone mentioned S&W's shield last week)
4. Investigate running Postgres in HA mode - don't rely on a single instance (another S&W follow-up)

**Comment by elliott-davis** [comment]
Closing this for now. @chefsalim I know we do most of the items in this list now. If there is something missing, please re-open.

**Comment by nellshamrell** [comment]
Re-opening this - we had a database issue earlier today and, while we recovered, it showed how badly we need automated backups for at least the datastore.

**Comment by eeyun** [comment]
Automated backups are now configured and terraformed! We should at some point codify the process for restoration but for now snapshots happen nightly and rotate out after 7 days. Closing as completed!
