### ISSUE TITLE
Define metric endpoints using an Enum, not bare strings

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#281]
Currently, our `github.api.*` metrics can be defined using a bare string to define the wildcard portion (e.g., `github.api.check_team_membership`, `github.api.repo`, etc.). 

Rather than having free-form strings, we should define these in an Enum, to tightly constrain things, provide compile-time checking, and make it easier to see at a glance all the metrics the system is emitting.

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/700
