### ISSUE TITLE
Better process for package removal

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#286]
@chefsalim commented on [Tue Mar 06 2018](https://github.com/habitat-sh/habitat/issues/4712)

There are some cases (security issues, significant user escalations, and a need to clean up core origin, etc) where we need to remove packages from origins.  This issue is about having some sort of redirection or notification process if someone tries to use the removed package.

**Comment by chefsalim** [comment]
Duplicate of #18
