### ISSUE TITLE
[builder-web] Handle 404s on package pages

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#292]
@cnunciato commented on [Thu Jun 15 2017](https://github.com/habitat-sh/habitat/issues/2612)

For known bad package URLs:

https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0
https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0/20170615150934

.. we should render a more appropriate "not found" view.

**Comment by chefsalim** [comment]
Duplicate of #68
