### ISSUE TITLE
Add scopes to tokens

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#295]
Currently, personal access tokens cannot be generated with restricted permissions, which limits their use in many production deployment scenarios where access to private packages is required.

At a minimum, they should be able to be scoped to an origin (rather than a user), with configurable bits for read, write, and admin permissions.

(There's more to this issue; what's written above is a placeholder for further expansion and planning.)

cc: @chefsalim @adamhjk @reset @onlyhavecans

**Comment by chefsalim** [comment]
It's implicit in the above, but when we support scopes we should also enable multiple tokens.
