### ISSUE TITLE
Get Packages off disk and onto S3

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#30]
@chefsalim commented on [Thu Jul 06 2017](https://github.com/habitat-sh/habitat/issues/2697)

Currently we are storing the package repository on disk.  We should get them into S3 in order to reduce the incident surface area and reduce backup/restore tasks.

---

@mwrock commented on [Tue Aug 29 2017](https://github.com/habitat-sh/habitat/issues/2697#issuecomment-325829822)

also see #1933 for more context

**Comment by chefsalim** [comment]
Use cases / acceptance criteria:
1. Support hosted, on-premise and dev environments
2. Have security for private packages
3. Consider future tiering of storage (eg, hot vs. cold storage of packages)
4. Provide a seamless migration path for production and acceptance
5. Have appropriate configuration for Terraform
6. Any package integration tests should work
7. Feature flag to turn on S3 vs. local path

**Comment by elliott-davis** [comment]
I don't think 7 should be acceptance criteria since we should be moving all packages though an S3 compatible API. We can still maintain local storage of packages though minio or rook.

**Comment by eeyun** [comment]
This work is completed and in prod!
