### ISSUE TITLE
Gateway node should scale to multiple instances

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#311]
Currently the gateway node is unable to scale beyond one instance since it's persistent store is based on a file system being present. We should be using S3 or something similar as an object store for habitat artifacts.

**Comment by chefsalim** [comment]
Related - https://app.zenhub.com/workspace/o/habitat-sh/builder/issues/30

**Comment by eeyun** [comment]
Now that S3 backend is implemented we _might_ be able to consider this closed. We should re-evaluate and determine if we can in fact run multiple instances of the api now that this work is completed. If validation is successful this can also be closed.

**Comment by eeyun** [comment]
Now that we have tested that the API can scale to multiple nodes without error, we can consider this completed!
