### ISSUE TITLE
Update op tool to generate admin tokens

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#315]
Since we are deprecating the use of habitat teams for role privileges, we need a way to allow admin-type calls to the API.  An addition to the op tool to generate an admin token would be a straightforward solution.

**Comment by raskchanky** [comment]
@chefsalim Do we have a concept of an admin token right now?  Or would defining that be part of this task?

**Comment by chefsalim** [comment]
I think we can just use the Builder token @raskchanky ... it has embedded permissions flags in it - we can just set the admin flag, and not set the worker flag.  Also we'd set it to expire at some reasonable interval - eg, ~ 60 mins.  We'll need to also review the permission grant path to make sure things work as expected, any changes there should be minor.

**Comment by chefsalim** [comment]
Also related: https://app.zenhub.com/workspace/o/habitat-sh/builder/issues/388

**Comment by chefsalim** [comment]
Op tool has been deleted - we can revisit later when we add RBAC support to tokens
