### ISSUE TITLE
Point-in-time snapshot of a channel

### ISSUE THREAD

**Issue by jaym** [habitat-sh/builder#319]
Channels are moving targets. It would be useful to resolve a channel into an immutable pointer to a channel at a given point in time. This would help when trying to run a group of services locked down to a set of version/releases.
- It would be nice if it behaved like a channel from the supervisors perspective, just one that could never change
- Querying the versions/releases of packages is needed

**Comment by baumanj** [comment]
Closed per @jaym's request
