### ISSUE TITLE
List all built packages that were not promoted

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/builder#328]
This would be useful to detect packages that have been (re-)built but were not promoted as expected.

The original use case is for core-plans where some PRs have been merged but built package never promoted. Today, it is really hard to find them as there are ~570 packages.

It may be linked to the notifications feature somehow, not sure :)

Aha! Link: https://chef.aha.io/features/APPDL-13

**Comment by eeyun** [comment]
Leaving a comment here to appease our robot overlord. This is being investigated and should fit nicely into the notifications we're discussing.

**Comment by sajjaphani** [comment]
This isn't stale
