### ISSUE TITLE
Better workflow for connecting plans

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#337]
The current workflow for connecting plans always requires a Github App to be installed on the user's repo or org.  It also always associates the app id to the plan connection.  This means that we make authenticated calls against the app id, which count against the Github rate limits.

The epiphany here is that we do not need to make authenticated calls unless the repo is private. Therefore we do not need to either install the Github app, or associate the app id for public packages.
This would simplify both the workflow, and help eliminate rate limit issues.  

So, if we can add a check in the UI where the user can specify whether the repo is private or public, then we can use that check to trigger the rest of the workflow appropriately.

**Comment by chefsalim** [comment]
Related to https://app.zenhub.com/workspace/o/habitat-sh/builder/issues/50

**Comment by eeyun** [comment]
This work is now complete and as of today, released!
