### ISSUE TITLE
[devx] Need to be able to do cargo check 

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#344]
Currently we don't have a way to do a `cargo check` - this can slow down the dev workflow a lot in the early stages of dev work.

We either need to enable this in the studio, or bring back the scripts to set up Rust and required libraries (including protobuf) so that the cargo checks can be done outside of the studio.

**Comment by raskchanky** [comment]
It might be worth getting a little bit more specific here.  I'm guessing this is just for the `builder-protocol` crate?  I'm not sure why other crates would fail a `cargo check`.

I think enabling this outside the studio would likely be significantly easier than inside the studio, as that's something that used to work, and it's probably just a matter of adding a few `apt-get install`s to [the provisioning script](https://github.com/habitat-sh/builder/blob/master/support/linux/provision.sh).  I can still `cargo check` all the crates fine, but I'm using a custom provisioning script.

Off the cuff, something like:
```shell
apt-get update
apt-get install -y --no-install-recommends \
  build-essential \
  libprotobuf-dev \
  pkg-config \
  protobuf-compiler
```
is probably sufficient.

**Comment by chefsalim** [comment]
It's not only the builder protocol crate - we can fail because of missing libsodium, libarchive, libssl, zmq, postgres as well.  In case of protobuf it is also a bit more complicated, since we need libprotoc 3.x - and that does not always have an installable package (eg, for Ubuntu 16.04).  The provision script we need should be closer to the ones we used to have.

**Comment by raskchanky** [comment]
Well [the Vagrantfile](https://github.com/habitat-sh/builder/blob/master/Vagrantfile) specifies Ubuntu 17.10, so that's what we should consider when considering installable packages.

**Comment by chefsalim** [comment]
I had missed the version in the Vagrantfile... 17.10 just became LTS a few days ago, the last LTS version as of a week or so ago was still 16.04 which is what I picked up unfortunately.  17.10 will hopefully not have the protobuf issues, and if that's the minimum standard that needs to bubble up in the docs as well.

**Comment by chefsalim** [comment]
Closing for now
