### ISSUE TITLE
Builder WebHooks

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#35]
@reset commented on [Tue Aug 08 2017](https://github.com/habitat-sh/habitat/issues/2891)

We need a mechanism for notifying external systems of build and publish status for packages. This is often manifested in an HTTP callback known as a WebHook.

We should aim at a minimum to support WebHook notifications for
* Build finish - with a payload containing the status and information about the generated artifact
* Publish finish (i.e. Docker Hub export) - with the same payload as above

---

@tduffield commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/2891#issuecomment-335973344)

I would also be interested in a promotion notification.

**Comment by tduffield** [comment]
I'd also like to throw my hat in for promotion notifications.

**Comment by elliott-davis** [comment]
Duplicates #74
