### ISSUE TITLE
Unable to upload secrets from a same-named origin, different depot

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#351]
If I have an origin, say `cnunciato`, and I upload a secret to Depot A for that origin, then attempt to upload a secret to an origin on Depot B by the same name (i.e., also `cnunciato`), I get:

```
hab origin secret upload SOME_KEY "some val"
☛ Encrypting value for key SOME_KEY.
✓ Encrypted SOME_KEY=[REDACTED].
↑ Uploading secret for key SOME_KEY.
✗✗✗
✗✗✗ [404 Not Found] [err: ENTITY_NOT_FOUND, msg: vt:origin-public-encryption-key-get:0]
✗✗✗
```

This is apparently happening because `hab` is recognizing an encryption key downloaded from Depot A, using it to encrypt my secret, but then failing to upload it because that key doesn't also exist on Depot B.

It seems like minimally, we should improve the error messaging here to clarify what's actually happening, but this also feels like a bug in that `hab` generally handles origin public and signing keys from multiple depots without issue. 

It seems like ideally, `hab` would recognize that in this case, since we don't have the encryption key required by the target depot, it should download it, then use it to upload.

**Comment by mwrock** [comment]
Not super clear what the right path forward is regarding implementation. At the least we will add messaging that is more clear, but it needs to be addressed in some way.

**Comment by dmccown** [comment]
For 1.0 we should try to figure out a better error to show the user.
