### ISSUE TITLE
Signing in twice

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/builder#354]
I've noticed that if I've been away from the Builder UI for a while (perhaps long enough that my session expires?) that I have to sign in twice. The flow is that I click the Sign in with GitHub button, see the My Origins page for a split second, then get redirected back to the Sign in screen. Then I click the Sign in with GitHub button again and the My Origins page properly loads.

cc: @cnunciato

**Comment by cnunciato** [comment]
Legit find, thanks -- I've seen this before myself after being signed out automatically after a session-server restart.

**Comment by chefsalim** [comment]
This does not seem to happen any more - re-open if it re-occurs.
