### ISSUE TITLE
Habitat picks up keys of wrong origin

### ISSUE THREAD

**Issue by dcotech** [habitat-sh/builder#358]
I currently have two origins on habitat builder. For this example, let's say one origin is named red, the other is named blue

Red is the older origin, while blue is the newly created one. I made keys and everything in each respective one; however, when I use a builder through the blue red, it tries to pull keys from red (Causing the builder to error out).

Feel free to let me know what information you'll need to troubleshoot this.

**Comment by mwrock** [comment]
Thanks for filing this @dcotech! Is the `pkg_origin` setting of the plan connected to the blue origin set to `blue`. Can you verify when you navigate to the `red` origin that you do not see a connected plan for the one in the `blue` origin?

Can you share an excerpt of the error message you receive from the build log?

**Comment by raskchanky** [comment]
I'm going to close this for now due to inactivity.  If this problem persists, or if you need more information, please feel free to reopen.
