### ISSUE TITLE
Failure to upload large hart files 

### ISSUE THREAD

**Issue by djoos** [habitat-sh/builder#374]
Hi there,

we're in the process of ["Habitatizing" commercial of the shelf software](https://forums.habitat.sh/t/using-habitat-with-cots/423). The resulting .hart file is around 600MB and upon `hab pkg upload` initially the upload would retry 5 times: upload progress goes up to 100% and then retries, eventually getting _"Upload failed: We tried 5 times but could not upload [name of mypackage]. Giving up."_. After trying a couple times, I ended up getting a gateway timeout instead, see below, making use of `RUST_LOG=debug` (thanks @elliott-davis aka libsysguy!)...

FYI: I've replaced our origin, package name and version.

```
...
» Uploading results/myorigin-mypackage-myversion-20180412102103-x86_64-linux.hart
DEBUG 2018-04-13T08:47:38Z: habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/pkgs/myorigin/mypackage/myversion/20180412102103 with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.54.0/20180221022026 (x86_64-linux; 4.9.87-linuxkit-aufs)") }
DEBUG 2018-04-13T08:47:38Z: hyper::http::h1: request line: Get "/v1/depot/pkgs/myorigin/mypackage/myversion/20180412102103" Http11
DEBUG 2018-04-13T08:47:38Z: hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab/0.54.0/20180221022026 (x86_64-linux; 4.9.87-linuxkit-aufs)
, Authorization: Bearer _Qk9YLTEKYmxkci0yMDE3MDkyNzAyMzcxNApibGRyLTIwMTcwOTI3MDIzNzE0Ck9XZEZtK3FsMlFVQWY3MzRwRXB2UFF2bWdwdUhUZjNpCjBUYk0rSkVnd3VLaXRZR2lSdGZrcWNHWWZMRkxld3NBeHlxNWg2S0RxdWx6blVWVA==
, }
DEBUG 2018-04-13T08:48:37Z: hyper::client::response: version=Http11, status=GatewayTimeout
DEBUG 2018-04-13T08:48:37Z: hyper::client::response: headers=Headers { Via: 1.1 varnish
Via: 1.1 varnish
, Content-Length: 0
, Accept-Ranges: bytes
, Date: Fri, 13 Apr 2018 08:48:37 GMT
, Connection: keep-alive
, X-Served-By: cache-sea1021-SEA, cache-lcy19243-LCY
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
✗✗✗
✗✗✗ [504 Gateway Timeout]
✗✗✗
```

In the original "retry case" the package, version and release got created on bldr.habitat.sh (obviously not now anymore when getting the 504), at https://bldr.habitat.sh/#/pkgs/myorigin/mypackage. However the actual detail on the version (eg. https://bldr.habitat.sh/#/pkgs/myorigin/mypackage/myversion/20180412105416) is completely empty...

Thanks in advance for your help!
David

**Comment by raskchanky** [comment]
@djoos Thanks for opening this issue!  I just wanted to drop a quick note and let you know that we've been aware of issues with uploading large packages for a little while now and are trying our best to get to the bottom of it.  Hopefully we'll have some updates on this in the near future.  Sorry for the hassle!

**Comment by djoos** [comment]
Thanks for your reply @raskchanky!

In the meantime: is there any way to push our .hart to let's say S3 and then point to that location for build/runtime deps in plan.sh that depend on the package? #temporary #workaround

**Comment by raskchanky** [comment]
@djoos I don't believe that plan.sh supports any remote locations other than habitat depots.  Technically, you could put the file on S3 and pull it down as part of your build in one of the hooks, but then it's not an explicit dependency, and you lose the benefits there.

We recently [merged support for offline mode](https://github.com/habitat-sh/habitat/pull/4771) which would theoretically allow you to have your large hart file on disk and have it be picked up by the build program, instead of going out to the depot to find it.  The downside is that we haven't cut a release yet that includes offline mode.  It will be in the next release, though.
