### ISSUE TITLE
Add thread name to Builder logging output

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#38]
@christophermaier commented on [Wed Sep 06 2017](https://github.com/habitat-sh/habitat/issues/3090)

Most services that make up Builder run more than one thread of execution, but logging output does not reflect this, making it difficult to determine which thread a given message is coming from.

**Comment by chefsalim** [comment]
This hasn't been a big issue as the builder logging includes the module name.  Closing as we are probably not going to get to this.
