### ISSUE TITLE
Indicate in the web UI that a package (plan) is connected to Builder and exporting

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/builder#381]
As a user, I want to quickly see that my package is connected to Builder, so that I know it is currently auto-rebuilding and exporting.

Currently, the only ways to determine if a packages is connected and exporting are by...
- looking at the Settings tab for connection details
- knowing that the presence of data on the Build Jobs tab comes from Builder
- seeing the 'Build latest version' button in the sidebar

Some places to consider surfacing this data would be...
- the Packages tab (list of packages) when viewing an Origin
- the right sidebar of the Latest/Versions/Build Jobs tabs when viewing the details of a package
- in the body of the manifest text on the Latest tab
- in the metadata atop the build output view

For reference, previous mockups contained additional indicators that can be viewed below:
- [Invision - See icons in sidebar](https://chef.invisionapp.com/share/C5E6NIURX#/262349769_package_Detail_-_Build_Jobs)
- [Invision - Separate export data in build output view](https://chef.invisionapp.com/share/A6H3MIQ8CU2#/249157456_package_Detail_V2_-_Manifest_Expanded)
- [Invision - automated builds ON link](https://chef.invisionapp.com/share/5YH3M8CZPX3#/246380858_package_Detail_V2_Mesos)

**Comment by apriofrost** [comment]
Add a note for a typo in the existing copy under Origin - Members tab. ![image](https://user-images.githubusercontent.com/9401459/39782528-4def1572-52c7-11e8-9fcc-393026e96236.png)

**Comment by apriofrost** [comment]
@ryankeairns @cnunciato @mgamini Mockup for your final review: https://chef.invisionapp.com/d/main#/projects/prototypes/14173853

Screens that need updates are grouped by the page name:

- [ ] My Origins Landing Page
- [ ] Package Overview page
- [ ] Package Detail page

Note: the new UI is designed upon #380

**Comment by dmccown** [comment]
We'll re-open later if we revisit this.
