### ISSUE TITLE
Make package rebuilds more resilient

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/builder#385]
### The problem

Some package versions that were built at least once, might not be re-buildable by builder when its dependencies are rebuilt. This will likely cause inconsistent dependencies problems and break habitat usage.

### Causes of the problem

There are most likely two main causes that might prevent a re-build to pass:

* Temporarily unavailable distant source (SSL certs, downtime...)
* Permanent source removal (deleted after EOL)

### What we could try to do

To make re-builds more resilient and more fault-tolerant, it might be a good idea to offer an easy way to add `pkg_source` cache support in builder (or via a service we could recommend, next to it such as a proxy cache maybe?).

**Comment by fnichol** [comment]
There's a possible related feature which I've thought about every time SourceForge has an issue and I'm building a lot of packages: perhaps we should consider mirror support in a Plan. It could be something like an additional array like:

```sh
pkg_source_mirrors=(
  https://mirror1/$pkg_name/$pkg_version/thing.tar
  https://mirror2/$pkg_name/$pkg_version/thing.tar
)
```
or possibly treating `$pkg_source` as either a string or an array and if it's an array try each URL until we have success.

---

There's one catch in a specific case: we might be limited in what we can legally mirror. Or put another way: could we mirror an old Oracle JDK package if the original source was no longer served?

**Comment by predominant** [comment]
Is a mirror in scope for Habitat? As I see it, the core plans should have the official sources listed, which may fail from time to time. Configuration plans could override sources to specify mirrors if enterprises needed mirrors to be used, or alternatively transparent proxies with mirror redirection is a common approach.

I'm not saying mirroring capability doesn't necessarily belong here, just posing the question.

**Comment by reset** [comment]
Gonna cross-post this here: https://github.com/habitat-sh/core-plans/issues/1394#issuecomment-382566831

/cc @fnichol
