### ISSUE TITLE
Make it easier to diagnose `.bldr.toml` misconfiguration issues

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#389]
It can currently be tricky to diagnose issues with a `.bldr.toml` file. For instance, the following file initially looks correct, even though it likely doesn't do what the user wants at all:

```toml
[api]
plan_path = "habitat"
paths = [
  "src",
]
```
The issue is that while we automatically convert `plan_path` into a file glob on behalf of the user (i.e., internally, it becomes `habitat/*`), we _do not_ do this on the entries of `paths`. The user is expecting Builder to trigger a build when any files in the `src` directory tree are changed, but this configuration is only watching for changes to the literal file `src`; if the user had written `src/*` literally, everything would work fine.

Since users will want to watch a combination of directories and files, I don't know that there's a sure-fire way for us to automatically (and more importantly, _safely_) "glob-ify" entries in `paths`.

While our online documentation does show examples using fileglobs, we should be more explicit about the need for globs in `paths`, but not in `plan_path`. It would also be useful to explain exactly which globbing operators we allow, based on the [underlying library we are using](https://docs.rs/glob/0.2.11/glob/struct.Pattern.html), and to emphasize the fact that these are not general regular expressions.

What would _really_ be useful, though, is some kind of tool that users could run on a `.bldr.toml` file to check that it's actually going to match what they care about. If we had something that would output information like this:

```
Builder will trigger new builds when any of the following individual files change:

src
```
it would be very easy to see that something is wrong, particularly if you're expecting to see something more like this:

```
Builder will trigger new builds when any of the following individual files change:

src/census.rs
src/lib.rs
src/command/mod.rs
src/command/shell.rs
src/sys/unix/abilities.rs
src/sys/unix/mod.rs
src/sys/unix/exec.rs
src/sys/unix/users.rs
src/sys/mod.rs
src/sys/windows/abilities.rs
src/sys/windows/mod.rs
src/sys/windows/exec.rs
src/sys/windows/users.rs
src/http_gateway.rs
src/fs.rs
src/schema.rs
src/manager/peer_watcher.rs
src/manager/sys.rs
src/manager/file_watcher.rs
src/manager/service_updater.rs
src/manager/service/mod.rs.rej
src/manager/service/spec.rs
src/manager/service/package.rs
src/manager/service/composite_spec.rs
src/manager/service/health.rs
src/manager/service/mod.rs
src/manager/service/dir.rs
src/manager/service/supervisor.rs
src/manager/service/config.rs
...
```

**Comment by raskchanky** [comment]
I'm about to open a PR to address the docs side of this.  In the interest of not keeping issues partially completed, I'm going to open a separate issue for the idea of a linter tool and let my PR close this issue.

**Comment by raskchanky** [comment]
The new issue for the tool is https://github.com/habitat-sh/habitat/issues/4970
