### ISSUE TITLE
Windows Only Packages Not showing in "Latest" view

### ISSUE THREAD

**Issue by skylerto** [habitat-sh/builder#390]
If there are only windows platform hab packages, latest is not displayed and the text for `There are no available Habitat artifacts (.hart files) for this origin/package.` is displayed.

E.g. [core/sqlserver](https://bldr.habitat.sh/#/pkgs/core/sqlserver/latest)

**Comment by chefsalim** [comment]
Dup of https://app.zenhub.com/workspaces/57e1e83308ec936f021c876a/issues/habitat-sh/builder/825
