### ISSUE TITLE
Pullthrough Archive Service

### ISSUE THREAD

**Issue by Atalanta** [habitat-sh/builder#392]
As discussed in https://github.com/habitat-sh/core-plans/issues/1394, and https://github.com/habitat-sh/builder/issues/385, it would be great to have a kind of pull-through archive/cache capability, which combines iterating over a list of possible upstream sources with the ability to maintain our own copy of the source so we can still build and support packages which rely on older upstream versions, even if the upstream goes away (temporarily or permanently).

**Comment by eeyun** [comment]
I'm thinking with the on-prem upstream featureset we can consider this completed. The way this works today is if a package doesnt exist on your on-prem deployment and you request it, the on-prem builder depot will reach out to any of your configured upstreams and pull the package down to make it available.

If you're in agreement then I'll close this out, if not then I'd be keen to get some more perspective on this one.
