### ISSUE TITLE
Disable Build Button for base packages

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/builder#396]
Base plans currently cannot be built through builder, as they must be built in a specific order (this is something we will look to improve after the base plans refresh lands).

While this condition is true, we need to disable the build button for all base plans (which are listed [here](https://github.com/habitat-sh/core-plans/blob/master/CODEOWNERS) and the "Base Plans" heading.

**Comment by chefsalim** [comment]
"Auto-build" configuration is available now to better control automated builds, and also we can unlink plans from Builder that should not get built at all.
