### ISSUE TITLE
Capture and record the commit SHA for a build

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#407]
This request comes up often:

https://forums.habitat.sh/t/can-our-builder-build-see-our-git-revision-hash

It'd be nice to capture the SHA (e.g., from a webhook or CLI argument) and expose it as an environment variable in Builder — or maybe better, as additional package metadata somehow. Feels like something we should do, though, given how closely these concepts are usually associated.

**Comment by christophermaier** [comment]
Relevant: https://github.com/habitat-sh/habitat/issues/3045

**Comment by cnunciato** [comment]
Closing in favor of habitat-sh/habitat#3045.
