### ISSUE TITLE
Optimize session tokens

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#42]
@raskchanky commented on [Tue Sep 26 2017](https://github.com/habitat-sh/habitat/issues/3345)

This is related to https://github.com/habitat-sh/habitat/pull/3271

We can save some time traversing shards during account/session creation and retrieval if we create a fat session token that holds all the data we care about and store that, instead of storing the GH token directly.

**Comment by raskchanky** [comment]
This is ancient and outdated.  I'll open a new issue that's more relevant to how the code stands today.
