### ISSUE TITLE
Optimize the upstream depot processing

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#422]
There is some room to optimize the code that downloads packages from upstream depots right now:

* Instead of spawning a new thread each time we want to check for an update, we could have one long running background thread that pulls tasks from a list of idents to refresh.  The main thread just pushes idents to that list whenever something needs to be updated.  This would also let us seed that list with a list of packages to install the first time the depot starts up, which would eliminate the need for some of our current bootstrapping scripts.

* The logic to pull packages down and upload them could use builder-depot-client, which would make the entire process more encapsulated and portable.

**Comment by chefsalim** [comment]
A couple of other items:
* Throttling of calls to upstream - the upstream processing can put a lot of extra pressure on API calls to the upstream - having a long lived thread should allow more optimization on how often and how many calls we are doing to the upstream
* Better logging - it would be nice to have a persistent log (similar to the builder-scheduler.log on disk) that audits the refreshes (including failures).

**Comment by raskchanky** [comment]
This is done
