### ISSUE TITLE
Feature Request: improvements around integration of Builder and `plan.sh`

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/builder#429]
After some recent issues that were hard to debug, we've found ourselves wishing for additional sanity checking in Builder and a way to wire up Builder to a given Plan via the CLI.

We'd like to see a sanity check in Builder when pointing our Origin to a given `plan.sh` that ensures `pkg_origin` in said plan matches our Builder Origin.

We'd also like to see a CLI way to hook up the `plan.sh` to Builder, because we'd be more likely to catch errors like these if not being forced to switch back-and-forth between the browser and the terminal. UX might look like:
```
hab bldr connect <origin> <github/path>
```

**Comment by chefsalim** [comment]
![tenor-248547521.gif](https://images.zenhubusercontent.com/5a7219f64b5806bc2bc5175c/52cdc2fc-d914-44ba-a137-147153a749f3)

**Comment by fnichol** [comment]
I do like the idea of connecting a Plan via the command line and having some more checking and linting would increase the chances of success when wiring it up to Builder.

As for Builder checking the value of the Plan's `$pkg_origin`--it might be time to consider relaxing the need for this being a required variable. Also, I don't think that Builder needs to check this in the Plan anyway--we know what origin you are in and which package we're going to build. We also know if we have a secret key associated with the origin.

@smartb-pair If you had a moment, think you could file a Builder issue proposing to remove this origin check? Thanks!

**Comment by bixu** [comment]
Hmm - we actually would _prefer_ that the `pkg_origin` be respected and enforced both in Builder and Studio. It would be a great safety mechanism to prevent uploading packages to the wrong origin (think private code in a public originhz
