### ISSUE TITLE
Make auto-rebuild of packages opt-in

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#458]
Currently, once a plan is connected to builder, it will get auto-rebuilt any time a dependency re-builds.  While desirable for things like enterprise packages, it may not always be what is appropriate (eg, if you have a demo app that depends on core/node..).  We should make the auto-rebuild capability opt-in, and default it to off.

From a UI standpoint, this would be one more setting in the Settings page, that could go before or after the Public / Private package option.

### Mockup
👨‍🎤🖼 [Invision mockup for automatic dependency rebuild opt in](https://chef.invisionapp.com/share/48L8339GDVN#/303830964_package_Connect_-_Step_2_-_Opt-In)

**Comment by ryankeairns** [comment]
Mockup link has been added to the description. This adds a section to turn on/off the auto rebuild feature from within the 'connect a plan' flow. 

Let me know if you have any questions.

**Comment by chefsalim** [comment]
@ryankeairns Looks great, except we should have it off by default (also minor typo in text)

**Comment by ryankeairns** [comment]
Updated mockup per Salim's feedback.
