### ISSUE TITLE
Sumologic No Longer Capturing live/api/access

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#473]
Searches using `_sourceCategory=live/api/access` are no longer returning data. We should investigate to ensure the data collectors are still functioning properly.

**Comment by chefsalim** [comment]
Somehow we had gotten into a state where the collector on the API node was sending its data into the acceptance bucket.  A re-install of the collector (to a newer version) seems to have resolved the issue and data is flowing correctly again.
