### ISSUE TITLE
Expose Project Settings

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#479]
Right now, if I want to take a public package and make it private (or modify any of it's other settings) I only have 2 options, neither of which are very delightful.

1. I can get an arcane API call and curl it out with something like so:
```
curl -v \
-X PATCH \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $HAB_AUTH_TOKEN" \
https://bldr.habitat.sh/v1/depot/pkgs/core/redis/3.2.4/20170215222111/private
```
2. I can go through the UI which doesn't expose the settings directly but instead requires a user to configure as though the package is being connected for the very first time.

This is problematic for a couple of reasons that are hopefully clear from a UX perspective. At times, a user might simply want to inspect the settings of a project for configuring a new project (perhaps mirroring the config of another thing they want set up the same way). The other problem is, ideally a user could want to tweak a single setting of the project rather than fully reconfiguring it from the ground up!

**Comment by chefsalim** [comment]
Updated title.  The issue mentioned in #2 above is addressed by https://github.com/habitat-sh/builder/issues/552

This issue should deal with figuring out the best way to toggle visibility on a specific already-built package, and how to expose that to users (both web UI and hab cli)
