### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by uasaigoli** [habitat-sh/builder#485]
It would be awesome if bldr can integrate with gitLab just like gitHub.

**Comment by chefsalim** [comment]
GitLab integration is available for the on-premise version of builder: https://github.com/habitat-sh/on-prem-builder.  However, there are currently no plans for SaaS builder to integrate with GitLab.

**Comment by jsirex** [comment]
@chefsalim are you talking about authentication? But what about gitlab repositories itself? As I can see, there is no problem to deploy builder on-prem with `builder-worker` and `builder-jobsrv`. There only issue that `builder-worker` doesn't support gitlab as vcs.
