### ISSUE TITLE
JIRA integration

### ISSUE THREAD

**Issue by uasaigoli** [habitat-sh/builder#486]
I would be nice if bldr can integrated with JIRA so that each build will have changeset details. When release manager can make the decision to promote based on the content of the change.

**Comment by elliott-davis** [comment]
Could we get some more information about this integration? Use-case, etc?

**Comment by mwrock** [comment]
Closing now due to lack of response. Given more details we will be happy to reopen!

**Comment by uasaigoli** [comment]
Here is the use case: each build should capture release change text (hoping that 1 or 2 lines statement from the JIRA ticket). Based on captured text, release manager will pick the right build to promote/deploy to right region.
