### ISSUE TITLE
List origin projects and provide a way to navigate to them

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#49]
@cnunciato commented on [Fri Oct 06 2017](https://github.com/habitat-sh/habitat/issues/3579)

We need a way to modify the settings of a project/plan-connection that doesn't yet have any packages. This can be handled in the Settings tab -- we just need the UI to provide a way to navigate to that.

---

@cnunciato commented on [Fri Oct 06 2017](https://github.com/habitat-sh/habitat/issues/3579#issuecomment-334833981)

cc @ryankeairns 

---

@ryankeairns commented on [Fri Oct 06 2017](https://github.com/habitat-sh/habitat/issues/3579#issuecomment-334864815)

Adding link to mockups for this... in it you can:
1. view a pending packages (ie. plan connected, but not available releases yet)
2. view a package that has only manual uploads, just for comparison purposes

### To-do
- [ ] Add a new table above Packages that lists projects which have not .harts in the depot yet.

### Mockups
[Pending packages](https://chef.invisionapp.com/share/X3DQCM6DU#/249855195_create_Package_Empty)

cc:/ @raskchanky 

---

@ryankeairns commented on [Sat Oct 07 2017](https://github.com/habitat-sh/habitat/issues/3579#issuecomment-334936096)

This is good for launch, but I’d like to keep it open until it more closely resembles the mockup. We can move it to On Deck. 

Nice work knocking this out last minute @raskchanky !

**Comment by chefsalim** [comment]
Closing as there does not seem to be any priority to do additional work around what we already have currently for this scenario.
