### ISSUE TITLE
Create alert when builder serves a HART file that is zero bytes

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/builder#493]
The builder outage on Monday, June 18th was due to the fact that a zero-byte file had been cached at the nginx layer and was getting served as the core/gzip HART. We don't know exactly how the zero-byte file ended up in the cache, but it was the sumologic logs that ultimately surfaced this fact.

For the sake of early detection, it seems worthwhile to add an alert trigger in our sumologic logs for serving a zero-byte file.

**Comment by chefsalim** [comment]
Nginx caching is off in prod now, and off by default, so we don't anticipate a recurrence.  Will consider if this recurs for other reasons.
