### ISSUE TITLE
Disable nginx caching

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/builder#494]
A zero-byte file cached by nginx was instrumental to the builder outage on Monday, June 18th. Since our hit rate with Fastly caching is very high, it's not clear if we really benefit from the added complexity that caching in nginx gives.

Also, the nginx cache depends upon the HTTP user agent header, which seems questionable. I propose we try out disabling the nginx cache unless we can show a good argument that it provides value. We've already seen that it can exact a cost.

**Comment by chefsalim** [comment]
Couple of action items:
1. See if we can determine root cause - eg, is there a race condition we've missed
2. If not, add a config that turns off nginx caching, and we can experiment with having it off
