### ISSUE TITLE
Remove references to deleted VERSION file

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/builder#499]
The `VERSION` file was removed in [this PR](https://github.com/habitat-sh/builder/pull/441), but there are still a number of references to it in [rust files](https://github.com/habitat-sh/builder/blob/master/components/airlock/src/main.rs#L35) and [support scripts](https://github.com/habitat-sh/builder/blob/master/support/ci/fast_pass.sh#L13) which are confusing, cause noise in logs and should be removed.

**Comment by chefsalim** [comment]
The VERSION file is generated during the build, by reading the PLAN_VERSION env variable. So the VERSION references are still correct, and being used appropriately.
