### ISSUE TITLE
Upstream depot tweaks

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#500]
We've gotten feedback from a few customers that our current implementation of upstream depot syncing is sub-optimal.  Some tweaks to improve it are:

- [ ] Allow the calling process to optionally block until the upstream sync is finished, rather than doing it asynchronously in the background.  This could be accomplished with a new command line flag to `hab pkg install`.
- [ ] Allow any version of any package to sync, not just the latest version.
- [ ] For the background async installation, rather than doing it in a 60 second loop, do it on demand.

**Comment by chefsalim** [comment]
Tracking upstream issues and replacement plan in https://github.com/habitat-sh/on-prem-builder/issues/105
