### ISSUE TITLE
[builder-db] Test suite needs to unload `core/postgresql` service on start & stop

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/builder#507]
This came up when I was running `cargo test` from the root of this project. Running `cargo test` for the second time fails with and error saying that `core/postgresql` is already loaded. Most likely, this service should be checked for on start (possibly remove it?) and unloaded on finish of the suite.

**Comment by chefsalim** [comment]
This seems to be resolved with recent changes (db merge, etc) and does not repro any longer.  Re-open if you have a repro..
