### ISSUE TITLE
Leave an origin

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#51]
@reset commented on [Mon Oct 09 2017](https://github.com/habitat-sh/habitat/issues/3650)

We have the ability to remove members from an origin but we don't have the ability to leave one ourselves. We should add a button on the show origin UI component which allows you to leave an origin if you aren't the owner

**Comment by fnichol** [comment]
We'll need an API endpoint to finish this work up, otherwise it'll be (hopefully) straightforward.
