### ISSUE TITLE
Filter secrets data from pkg_source

### ISSUE THREAD

**Issue by btm** [habitat-sh/builder#510]
The `pkg_source` value in a plan.sh is displayed as 'Source' on bldr. If authentication credentials such as a Github token are placed in a variable that is used in this value, it is then expanded and displayed on the web.

This can be seen in this package: https://bldr.habitat.sh/#/pkgs/chef-server/compliance-profiles/1.7.0-dev/20171219195338 (that token has been revoked).

Having bldr not display this variable if it has a colon in it could be a useful gate to help avoid that kind of leak.

**Comment by dmccown** [comment]
This is an anti-pattern we should discourage people from following. We'll revisit post 1.0. We should also consider documentation.
