### ISSUE TITLE
Builder API / DB load profiling/tuning

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#517]
We have been seeing the database get under duress with an increase in some front end calls (eg https://app.zenhub.com/workspace/o/habitat-sh/builder/issues/519)

Initial observations (via the pg_activity tool) showed that count_unique_graph_packages_v1 shows up as one of the top calls when the DB is under stress. This is an expensive call that we should look at either tuning, or caching results on the front end.

There may be other calls that we want to tune as well.  For example, some APIs calls have a high fanout level that we may want to look at refactoring as well.

**Comment by cnunciato** [comment]
The regular expression in this query is probably worth looking into as a possible culprit: https://github.com/habitat-sh/builder/blob/1e70671da2ba147a184e291d20a6855eed89ed15/components/builder-jobsrv/src/migrations/2017-12-13-173340_initial_jobsrv_migration/up.sql#L388
