### ISSUE TITLE
Allow nginx config augmentation

### ISSUE THREAD

**Issue by chrisortman** [habitat-sh/builder#542]
I want to be able to run a few other services on the server where I'm going to put our builder. I'm wondering about adding either 

1. A new config property in

```

default.toml

[nginx]
include = ""

--

nginx.conf

server {
}

{{#if cfg.nginx.include}}
include {{cfg.nginx.include_directory}}
{{/if}}
```

2. An optional package bind that would work mostly the same way.

Number 1 seems more straightforward to me.

I am willing to do this work if it would be accepted.

**Comment by chrisortman** [comment]
So potentially on the server I might have an outward facing nginx instance that proxy's traffic to the nginx that builder has started up.

If I were going to run jenkins and maybe another app on there it seems like then I should keep to the same pattern and have a jenkins-proxy and my-app-proxy and have that outward nginx proxy to them.

This feels like something I shouldn't do but maybe it's fine?

**Comment by elliott-davis** [comment]
Hi @chrisortman,

We talked about this in triage and decided this isn't something we want to add to builder at this time.
