### ISSUE TITLE
lingering origin invite

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#55]
@robbkidd commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/3727)

I was invited to an origin a while back (Spring? May-ish?). I'm pretty sure I accepted it at the time.

Today, I see that I am a member of the origin and can definitely do things an origin Member can (I added a key, I connected a GitHub repo to a packge). But I've got a lingering invite that I don't know what to do with:

![both a member and awaiting RSVP](https://user-images.githubusercontent.com/517302/31452389-c96470ac-ae7c-11e7-8de5-e6e09c5f383c.png)

Last week, I only saw the invite which would error if I attempted to accept. I could _not_ interact with the origin.

---

@scotthain commented on [Fri Oct 13 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-336551649)

Doesn't seem to have any ill effects for me but I'm also seeing this, with a similar situation to Robb here. (I can confirm that I *did* accept the inv to the origin back in Apr/May-ish)

---

@rsertelon commented on [Sun Dec 10 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350586524)

@robbkidd @scotthain Do you still see the lingering invite? I've dug up in the code a little, but cannot find reasons for it to be shown.

---

@robbkidd commented on [Sun Dec 10 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350615578)

Yep. My origins list still appears as shown in the screenshot in this issue.

---

@scotthain commented on [Mon Dec 11 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350828245)

Likewise! Very strange :D

---

@rsertelon commented on [Mon Dec 11 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350830074)

~Can one of you invite me (temporarily of course) to one of your origins? So we can test that it will still happen or if your lingering invites are just quirks that would need a one-time database update :)~

@stevendanna has been invited and his invitation disappeared as expected.

I suspect there were a bug in the invitations process that might have been fixed since you accepted your invitations. A "simple" SQL query might be able to fix this?

---

@robbkidd commented on [Mon Dec 11 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350867308)

Yea, my money is on @scotthain and I having invitations in the database from before the roll-out of builder. It's probably something builder admins can clean up in the data as opposed to a bug in the current code base.

---

@scotthain commented on [Mon Dec 11 2017](https://github.com/habitat-sh/habitat/issues/3727#issuecomment-350871301)

I would 100% agree with this - we were very very early adopters (before there was a UX for accepting, IIRC) and this is likely just cruft if you can't replicate it.

**Comment by nellshamrell** [comment]
Closing this for now, but if you are still experiencing it, please request a database update.
