### ISSUE TITLE
Modifying Package Settings Shouldn't Attempt to Crawl GitHub When A Plan Is Already Configured

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/builder#552]
### Behavior Encountered

I have configured a repository/package in Builder that has a `habitat/plan.sh` connected. When I click the Settings "gear" icon, Builder attempts to connect to GitHub and select a repo an a plan file. 

![image](https://user-images.githubusercontent.com/12483/43229754-20d68a22-9023-11e8-9661-aeeec13b65ac.png)

### Behavior Expected

Go immediately to this screen:

![image](https://user-images.githubusercontent.com/12483/43229998-eb00b9b2-9023-11e8-934a-eddc250726cd.png)

And have an option to change the "Path to Plan File" by clicking on the text box that is shown there.

Thank you <3

**Comment by eeyun** [comment]
This work is complete and as of today released!
