### ISSUE TITLE
Want long search results

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#56]
@bixu commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/3728)

Right now `hab pkg search` returns only 50 entries total, which makes getting/parsing my complete package list programmatically (via cli) impossible.

---

@rsertelon commented on [Sat Nov 25 2017](https://github.com/habitat-sh/habitat/issues/3728#issuecomment-346966513)

The API seems to limit results to 50 at most [by](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L77) [design](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L141).

To get this feature we'd first need to allow more than 50 results at once.

---

@bixu commented on [Sat Nov 25 2017](https://github.com/habitat-sh/habitat/issues/3728#issuecomment-346967648)

Correct. Maybe there’s a performance reason for this, but I expect most CLI workflows to happily handle several thousand lines of output from a call.

Plus, if we *do* need a limit, showing the newest first would be nice :)

> On 25. Nov 2017, at 22:12, Romain Sertelon <notifications@github.com> wrote:
> 
> The API seems to limit results to 50 at most by design.
> 
> To get this feature we'd first need to allow more than 50 results at once.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

**Comment by smartb-pair** [comment]
@elliott-davis, this has come up again and is now a much bigger problem for us (we need to automate pkg demotion via search results).
