### ISSUE TITLE
Capture and indicate channel promotion/demotion activity

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#568]
Particularly with core plans, it can be helpful (particularly in debugging/incident-related scenarios) to know when a package was promoted to the `stable` channel (or perhaps any channel, for that matter). We should track this activity and represent it in the UI.

Not auto-backlogging this in order to prompt some discussion first in triage. 😄

**Comment by chefsalim** [comment]
We already track the promote/demote activity in the audit logs for debugging/incident purposes.  Exposing it in the UI might be interesting if/when we have notification capability (eg, "a package you depend on has a new version promoted to stable").

**Comment by dmccown** [comment]
This would be more useful as part of notifications #839
