### ISSUE TITLE
Implement "channel-to-channel" promotion

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#580]
As people start to use Builder as more of an integral part of their continuous delivery pipelines, it would be nice if we provided an API (and corresponding CLI command) that would allow users to atomically promote all the packages at the "head" of one channel into another.

The underlying idea here is that channels represent stages of a release pipeline. I've implemented some `curl` + `jq` scripting to mimic this in our own release pipeline, but it's not atomic (something could happen midway through the promotion resulting in half the packages being promoted and half not). If this is something that Builder provided out-of-the-box, it would help simplify the implementation of release pipelines based on Builder.

**Comment by raskchanky** [comment]
@christophermaier I'm not sure what you mean by "head" of a channel.  Can you elaborate a bit on that?

**Comment by christophermaier** [comment]
@raskchanky Sorry... I just mean the latest releases in a given channel. For example, if you've got `core/foo/1.0.0/1` and `core/foo/1.0.0/2`, it'll just promote the second one.

**Comment by christophermaier** [comment]
Addendum: It'd also be nice for this to return the latest version _for each package target_.

**Comment by fnichol** [comment]
I wonder if it'd be better to make `--latest-only` or something an optional behavior? I've always liked the idea of having a command that would "make the contents of *this* channel, the contents of *that* channel". Then if your environment (i.e. dev/staging/prod) was associated with a release channel, you would be promoting your full staging context into production.
