### ISSUE TITLE
Azure Container Registry post processor

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#59]
@reset commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/3744)

Add post-processor publishing support for [Azure's Container Registry](https://azure.microsoft.com/en-us/services/container-registry/) to Builder

#3742

**Comment by cnunciato** [comment]
The UI is complete for this and can be exposed by setting the `enable_publisher_azure` config item to `true`. It uses an integration type of `azure`.

**Comment by tashimi** [comment]
![tenor-67520597](https://user-images.githubusercontent.com/719646/37857618-c8769388-2eb9-11e8-981b-8eba5075c139.gif)
