### ISSUE TITLE
Google Container Registry post processor

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#60]
@reset commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/3745)

Add post-processor publishing support for [Google's Container Registry](https://cloud.google.com/container-registry/) to Builder.

#3742

**Comment by cnunciato** [comment]
@ell

**Comment by cnunciato** [comment]
Effing buttons.

**Comment by chefsalim** [comment]
Closing until product re-approval / resurrection with more details
