### ISSUE TITLE
Un-sharded services (eg, job server) should be able to route properly

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#61]
@chefsalim commented on [Sun Oct 15 2017](https://github.com/habitat-sh/habitat/issues/3787)

Currently, an unsharded service that sets it's 'shards' config to an empty list is unable to properly route messages. Need a proper solution so we don't have to iterate through 128 shards when only a single shard exists.

**Comment by nellshamrell** [comment]
We believe this has been addressed, but please feel free to re-open if this is still needed :)
