### ISSUE TITLE
Downloading Private Key appears to be broken in Builder UI

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#668]
@nellshamrell commented on [Thu Sep 20 2018](https://github.com/habitat-sh/habitat/issues/5662)

To reproduce:

Log into Builder
Navigate to one of your origins
Click on "Keys"
Click on the "Download" button next to the PRIVATE key (downloading the public key works fine)
Observe that no download takes place.

---

@jamesc commented on [Thu Sep 20 2018](https://github.com/habitat-sh/habitat/issues/5662#issuecomment-423364343)

I ran into this and it was my popup blocker causing it to fail.

**Comment by st-h** [comment]
using safari 11.1.2 on Mac OS 10.13.6:
tried to disable pop up blocker via `preferences -> security -> block pop-up windows`, but that does not resolve the issue. I don't have any additional pop-up blockers or extension installed.
