### ISSUE TITLE
Requests fail for integrations with spaces in their names

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#670]
Users with Builder integrations named with spaces (e.g., "Docker Hub") created prior to recent API and/or consolidation changes can no longer retrieve those integrations. Both GET and DELETE requests for them are failing. 

Tracing requests through the logs, you can see that GETs and DELETEs pass the spaces through to the API as `%20`, but those requests' corresponding DB queries are made with spaces:

```
builder=# SELECT * FROM get_origin_integration_v1('cnunciato', 'docker', 'Docker Hub');
 id | origin | integration | name | body | created_at | updated_at
----+--------+-------------+------+------+------------+------------
(0 rows)

builder=# SELECT * FROM get_origin_integration_v1('cnunciato', 'docker', 'Docker%20Hub');
         id         |  origin   | integration |     name     |   body    |          created_at           | updated_at
--------------------+-----------+-------------+--------------+---------------------------------------------------------
 943649113721938047 | cnunciato | docker      | Docker%20Hub | stuff...  | 2018-03-22 22:32:11.431804+00 |
(1 row)
```

**Comment by elliott-davis** [comment]
I think the fix for this is `UPDATE origin_integrations SET name = replace(name, '%20', ' ');`. Just tested in acceptance and it looks good.

**Comment by chefsalim** [comment]
Fixed in prod
