### ISSUE TITLE
Add job cancelation ability to the UI

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#69]
@chefsalim commented on [Fri Nov 03 2017](https://github.com/habitat-sh/habitat/issues/3998)

Now that we have an API (as well as hab cli cancel command), we should hook up the same functionality as part of the UI.

### UI Prototype
[Job cancel UI Mockup](https://chef.invisionapp.com/share/AREOTA4KQ#/266390910_package_Detail_V2_-_Versions_ALT_Job_Cancel)

#### Notes for prototoype
- :wip:

---

@cnunciato commented on [Fri Nov 03 2017](https://github.com/habitat-sh/habitat/issues/3998#issuecomment-341788307)

cc @ryankeairns

**Comment by ryankeairns** [comment]
@apriofrost This issue already has an Invision prototype though it's in the older UI (forgot that I made this :) ). It is likely enough that we could share/discuss with the Salim and Chris as a potential V1 solution.

**Comment by ryankeairns** [comment]
Split this apart after design is finalized.

**Comment by chefsalim** [comment]
Latest proto: https://chef.invisionapp.com/share/T8MTO5RN5BH#/screens
