### ISSUE TITLE
Cache not properly invalidated on promote

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#691]
When a package is promoted, builder seems to return the latest packages prior to the promote for the TTL time. This might be due to incrementing the incarnation number for the cache for the old channel, but no the new one.

**Comment by chefsalim** [comment]
I can't repro this - there's probably something else possibly going on.  The only theory I have atm is that there was a possible race condition - the promotion happened in the same second as an expiring cache, so it took one more cache invalidation for things to get resolved.  The (very rare) possibility of a race condition is one reason we may want to consider shortening (and spreading out) the cache validation period.

**Comment by chefsalim** [comment]
Looks like the missing case may be channel deletion
