### ISSUE TITLE
Expose more Builder activity in user-facing build logs

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#72]
@christophermaier commented on [Tue Nov 07 2017](https://github.com/habitat-sh/habitat/issues/4018)

We currently expose the actual contents of the Studio build in logs, as well as subsequent Docker image creation. We don't expose details of package upload, though (and there may be other stages of the process that are currently "silent"). If there is ever an issue in such a "silent" stage, it can be difficult to diagnose, or to even realize there is an issue.

**Comment by nellshamrell** [comment]
We do now alert the user when things are happening in terms of exports, and believe this can be closed for now.  If anyone wants us to revisit, please feel free to re-open.
