### ISSUE TITLE
[Builder UI] Indicate when you're working in admin mode

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#75]
@ryankeairns commented on [Tue Nov 14 2017](https://github.com/habitat-sh/habitat/issues/4051)

As an admin user, I want it to be obvious when I'm working under that mode
so that I can better understand why certain features and data are or are not available to me.

--------

### To-do
- [x] Add UI mockup 

### Mockup
[Admin mode mockup](https://chef.invisionapp.com/share/A9EGQR5TR#/263954722_profile_Godmode)
- adds banner that cannot be dismissed
- adds special profile photo and shadow

![profile godmode 2x](https://user-images.githubusercontent.com/446285/32803331-caf89542-c948-11e7-97a7-8234a623764d.png)

**Comment by nellshamrell** [comment]
@ryankeairns @tashimi - is this something we are still working toward?  Closing for now, but please feel free to re-open if this is something you want addressed.
