### ISSUE TITLE
Builder is not offering private keys for download, correctly.

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#756]
@predominant commented on [Tue Oct 30 2018](https://github.com/habitat-sh/habitat/issues/5797)

Creating a new origin, and then logging into builder (web) to download the private key yields a download with an incorrect filename:

It downloaded a file called `attachment; filename=_originname-20181030065810.sig.key_` (edited)

```
$  ls -la ~/Downloads           
-rw-r--r--@  1 graham.weldon  REDACTED         124 Oct 30 15:58 attachment; filename=_originname-20181030065810.sig.key_
```

**Comment by cnunciato** [comment]
Looks like the value of the `Content-Disposition` header has changed. The UI is currently expecting a value that complies with the spec: https://tools.ietf.org/html/rfc6266#section-5 &mdash; for example:

```
Content-Disposition: attachment; filename*= UTF-8''%e2%82%ac%20rates
```

... where the important is the `''` delimiter, which denotes the filename.

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/761
