### ISSUE TITLE
Builder aggressively logs out users

### ISSUE THREAD

**Issue by predominant** [habitat-sh/builder#767]
I'm finding that I need to re-login to builder every couple of hours.

Its annoying for a number of reasons:

* Its an extra click to get through to where I want to be going. Most (all?) of the time I'm already logged into github, and its just a redirect back.
* The post-redirect destroys my initial URL target. I'll browse to /pkgs/core/blah only to be logged out, click login and be redirected back to "My origins".

Just a UX thing that has been frustrating me.

**Comment by eeyun** [comment]
Hey @predominant I'd like to get some more context on this from you. We've had a whole lot of changes in the api and it's behaviors this month but diving into this today and I haven't been able to duplicate this behavior. I've gone ahead and increased the session length to 72hrs (from 24) but client side caching of site state should _also_ be happening. Is this still something you're seeing on your end?

**Comment by eeyun** [comment]
Correction, we've validated that client side site state caching is not currently working. So that bit we'll get sorted as well!

**Comment by predominant** [comment]
Thanks @eeyun - This behaviour is something that is best tested over a long period. So don't expect immediate updates from me. Its usually end of day to next morning, or similar, perhaps when services are restarted overnight and I get logged out. I guess if my Github session is still active, I expect Habitat Builder to also still have me logged in correctly. That extra login click is annoying.

It would be less annoying if post-login, it took me to the page I was initially trying to view, though.

**Comment by chefsalim** [comment]
Haven't seen this happen lately - please reopen if this is still a problem
