### ISSUE TITLE
Migrate all uses of `tempdir` crate to `tempfile`

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#769]
Same as https://github.com/habitat-sh/habitat/issues/5806

**Comment by rsertelon** [comment]
Looks like there's no direct usage of `tempdir` in builder.

It's in the `Cargo.lock` only as transitive dependency (of `native-tls` and `protoc-rust`) apparently.

**Comment by christophermaier** [comment]
@rsertelon Ah, you're right... Thanks!
