### ISSUE TITLE
Finish API integration tests

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#77]
@raskchanky commented on [Tue Nov 21 2017](https://github.com/habitat-sh/habitat/issues/4105)

This is part of the https://github.com/habitat-sh/habitat/issues/4013 epic.

Right now, we have an integration test suite (written in TypeScript) for the Builder API.  It's only partially complete and requires some setup to run correctly.

In preparation for API v2, we need to:

- [x] Finish the test suite so that the entire API is covered
- [x] Make the setup/teardown easier so that we can run this in CI

---

@raskchanky commented on [Tue Jan 02 2018](https://github.com/habitat-sh/habitat/issues/4105#issuecomment-354902298)

The last thing left for these tests is to get them passing on Travis.  @baumanj will be carrying the torch across the finish line for that final piece.

---

@baumanj commented on [Mon Jan 22 2018](https://github.com/habitat-sh/habitat/issues/4105#issuecomment-359574544)

Currently blocked on the hab-based builder dev env https://github.com/habitat-sh/habitat/issues/4442

**Comment by baumanj** [comment]
Previous habitat repo issue: https://github.com/habitat-sh/habitat/issues/4105
Previous habitat repo PR: https://github.com/habitat-sh/habitat/pull/4223

**Comment by baumanj** [comment]
PR here: https://github.com/habitat-sh/builder/pull/124
