### ISSUE TITLE
The 'Cancel jobs' feature should be more discoverable in the UI

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#819]
We added a very useful feature to allow users to cancel their group jobs.

Unfortunately the UI for that is buried inside of the group page, and even on that page is not very visible.

We should look at making this more discoverable by adding a Cancel button to the higher level pages.

**Comment by apriofrost** [comment]
Hi @chefsalim , I just tried this task flow and realized that the 'view output' link is incorrectly linked to the job details page under the package level, it should be the group details page under the Origin level, which contains the Cancel button (it is not shown immediately after the build request is submitted, however).  I'm going to work with @mgamini to fix this. Thanks for reporting the issue!

**Comment by chefsalim** [comment]
Great, thanks @apriofrost .. also would be great if the Cancel button was a bit more prominent looking, like the Build button.

**Comment by apriofrost** [comment]
@chefsalim The Cancel button was made looking less prominent because it was designed to sit next to the Promote to Stable button, which is the primary action on that page. It seems the promote functionality is not ready to be implemented yet. I'll work with @mgamini to see the current status of the Promote button and will adjust the styles for the Cancel button accordingly.

**Comment by apriofrost** [comment]
To-do after discussion with @mgamini 

- [ ] Change the link of the 'view the output' to the group details page under Build Jobs tab in the Origin level (the page that contains the 'Cancel unfinished jobs' button)
![image](https://user-images.githubusercontent.com/9401459/49461631-f44c2f00-f7a8-11e8-886a-7b1ab8fb66cd.png)
- [ ] Investigate the status of 'Promote to stable' button, if it's not planned to implementation shortly, change the 'Cancel unfinished jobs' button to be the primary button on the page.
- [ ] Investigate and fix the issue when the 'Cancel unfinished jobs' button is not showing up on the page constantly between the time when the job has been initiated and is not completed/canceled, e.g., when the job is in the queue.

**Comment by apriofrost** [comment]
@Shadae is taking a look at this to fix the first to-do item (fixing the link)
