### ISSUE TITLE
Searching Improvements

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/builder#832]
## Description
As a new Habitat user searching for available packages so I can see what's available. However it's hard to get the results that I would expect at this time. When searching for a package right now, typos would result in no search results or incorrect search results. We should have basic search capabilities between the UI and CLI to return consistent results. 

## Acceptance Criteria

**Comment by themightychris** [comment]
One really frustrating specific aspect of this is that the search seems to match whole words and not substrings. Given the domain, substring matching would be more appropriate than word matching

A specific case where this is often frustrating is when a package you're looking for may or may not be prefixed with `lib`.

For example, searching for `"ssl"` right now finds no results. Imagine you're trying to find libssl. That's part of the `core/openssl` package but only typing `"openssl"` will find it.

Bonus points: if a user searches for `"lib___"` and there is no result, offer any results for just `"___"`
