### ISSUE TITLE
builder service: pushing commit to connected plan doesn't trigger build

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#84]
@srenatus commented on [Fri Nov 17 2017](https://github.com/habitat-sh/habitat/issues/4078)

- This is the package: https://bldr.habitat.sh/#/pkgs/srenatus/dirserver/builds
- That's the connected repo: https://github.com/srenatus/upspin-habitat

<img width="699" alt="screen shot 2017-11-17 at 17 18 27" src="https://user-images.githubusercontent.com/870638/32957252-713784a8-cbbb-11e7-9395-0fc19f35f69b.png">

- The app is installed and has access to all repos:
<img width="357" alt="screen shot 2017-11-17 at 17 18 56" src="https://user-images.githubusercontent.com/870638/32957253-7155d016-cbbb-11e7-9d88-76f708e184b8.png">

- I've just pushed this commit: https://github.com/srenatus/upspin-habitat/commit/65cd5196a8bb12b0c2c9cdaba7cd69dfda538a87 (straight to master)
- Nothing happened
- Added a `.bldr.toml` with this commit https://github.com/srenatus/upspin-habitat/commit/3870f3da9777bea69288a862000e247d853cf226

- Still nothing happened

Am I missing something? 😃 

---

@Jrakkez commented on [Fri Nov 17 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-345311577)

Same issue here but ours will build if we update the plan.sh

---

@rsertelon commented on [Fri Nov 17 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-345316894)

Have you tried with the `paths` config too? Something like
```
[pkg]
plan_path = "pkg/plan.sh"
paths = [ "pkg/*" ]
```

Just to see if this works at least ;)

---

@tashimi commented on [Fri Nov 17 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-345330684)

Hi - thanks for reporting this issue. We have reproduced and will be investigating. 

---

@Jrakkez commented on [Fri Nov 17 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-345331232)

For what it's worth - adding an explicit .bldr.toml did not solve the issue in my case

---

@chefsalim commented on [Tue Dec 05 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-349502961)

This issue here is the inclusion of "plan.sh" in the plan_path - the path should NOT include plan.sh. Granted, we should be more forgiving on this, but at the moment, just removing the plan.sh should fix the issue of the build not getting kicked off.  So the .bldr.toml can look like this (in this case, the paths is redundant since it's the same as the plan path).

[pkg]
plan_path = "dirserver"

---

@chefsalim commented on [Tue Dec 05 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-349503263)

Please re-open if the above does not fix the issue.

---

@smartb-pair commented on [Thu Dec 07 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-349986991)

I think we are seeing a related issue with our Plans.  Here's some relevant directory layout and `.bldr.toml` content:

Content of the `habitat` directory at the root our repo (which in turn contains a number of additional Plans under the `plans` dir:
```
habitat
├── composite_plan
│   └── plan.sh
├── config
│   ├── alembic.ini
│   ├── api.env
│   ├── api.ini
│   ├── newrelic_api.ini
│   └── newrelic_background_tasks.ini
├── default.toml
├── hooks
│   ├── health_check
│   ├── init
│   └── run
├── plan.sh
└── plans
    ├── postgresql
    ├── config
    │   ├── functions.sh
    │   ├── pg_hba.conf
    │   ├── pg_ident.conf
    │   ├── postgresql.conf
    │   ├── pwfile
    │   └── recovery.conf
    ├── default.toml
    ├── hooks
    │   ├── health_check
    │   ├── init
    │   ├── reconfigure
    │   ├── run
    │   └── suitability
    └── plan.sh
```
and our `.bldr.toml`:
```
[postgresql]
plan_path = "habitat/plans/postgresql"
paths = [
  "habitat/plans/postgresql/*",
]
```

cc: @bixu @chefsalim 

---

@bixu commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352035694)

This is definitely still an issue for us at smartB.

  ( *eats 🍿 and waits eagerly * )

---

@bixu commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352073403)

Maybe what’s missing here is that, though we have a linked planfile in the root of our repo, pushes to _any file_ in said repo don’t seem to trigger an automated build.

Could it be related to the fact we have planfiles for both public and private packages in the same repo, and both types are linked to their respective Builder origins?

---

@chefsalim commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352129179)

@smartb-pair @bixu what your bldr.toml file is saying is that you want the path that the webhook matches is "habitat/plans/postgresql/*".  So when a file is committed that does not match that path, builder will not issue a build.  Also I don't see a plan.sh file under habitat/plans/postgresql.

Basically, the rule that has to pass any commit before builder will issue a build is: a plan.sh must exist at the plan_path, and the file path for the committed file must match EITHER the plan_path OR one of the paths specified in the .bldr.toml.  Hopefully that helps...

---

@smartb-pair commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352134259)

I’ll look into extending what .bldr.toml covers on Monday and see where we get.

> On 15. Dec 2017, at 23:36, Salim Alam <notifications@github.com> wrote:
> 
> @smartb-pair @bixu what your bldr.toml file is saying is that you want the path that the webhook matches is "habitat/plans/postgresql/*". So when a file is committed that does not match that path, builder will not issue a build.
> 
> Basically, the rule that has to pass any commit before builder will issue a build is: a plan.sh must exist at the plan_path, and the file path for the committed file must match EITHER the plan_path OR one of the paths specified in the bldr.tom. Hopefully that helps...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---

@tashimi commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352142535)

Updating docs: https://github.com/habitat-sh/habitat/pull/4318 

Salim's going to file an issue since this is somewhat ambiguous behavior

---

@tashimi commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352144098)

Related: https://github.com/habitat-sh/habitat/issues/4323

---

@bixu commented on [Sat Dec 16 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352179072)

I'm still seeing cases where autobuilds don't fire.  For example, the `smartb/flower` package [here](https://bldr.habitat.sh/#/pkgs/smartb/flower/builds)

Here's the related `.bldr.toml` bit:
```
[flower]
plan_path = "habitat/plans/flower"
```
I made a change to one of the plan's files but haven't seen a build trigger.

---

@tashimi commented on [Mon Dec 18 2017](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-352612857)

From @bixu, Here’s an example of a linked plan in Builder that’s not auto-building: https://bldr.habitat.sh/#/pkgs/smartb/api_celeryd_default/settings

---

@cnunciato commented on [Thu Jan 18 2018](https://github.com/habitat-sh/habitat/issues/4078#issuecomment-358865326)

FWIW, I hit this on a personal project tonight (a simple one with no `.bldr.toml` and my plan files in a `habitat` directory, same layout as the sample Node app) and was only able to get builds to be triggered if I removed the double-quotes around my `pkg_name` and `pkg_origin` values. (I thought we'd fixed this, but I guess not?)

**Comment by nellshamrell** [comment]
I believe this was related to our Github API rate limit issues, which are now fixed.  If you are still seeing this behavior, please feel free to re-open this issue.

**Comment by smartb-pair** [comment]
whooo :D
