### ISSUE TITLE
[Builder]  Support builds that take more than one hour to complete

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#847]
As a core-plans maintainer, I would like to build all software through builder. There are a handful of core-plans that take longer than one hour to build, which requires building out-of-band and uploading.  

I would like to see a tune-able parameter for build timeouts in order to support building all packages consistently through Builder.

**Comment by chefsalim** [comment]
The build timeout is tunable at a global - see the config for job server (job_timeout)
