### ISSUE TITLE
[Builder] Changing package publish settings does not save after initial configuration

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#849]
### Platform Details
Tested in google chrome on OSX.

### Scenario:
Issue reported by @ericheiser. Once a package is initially created in builder with integration settings configured, it appears that those settings can't be changed. When tweaking the settings from the project view and clicking save, a notification that the settings have been saved appears. However, we see multiple 404's and other 400 level errors in network inspection and the settings in fact do not get saved.

### Steps to Reproduce:
With a project configured to not publish to dockerhub, click edit settings, validate the plan file is the correct planfile and click next. On the integrations/publishing page, enable the publish to dockerhub with whatever tags or lack of tags you wish. Click save. Kick off a build. When the build finishes the publishing step will _not_ be triggered. Re-entering the project settings the dockerhub publishing will again show as disabled.

### Expected Result:
The expectation is that any project could have its publishing settings turned off or on at any given time.

### Actual Result:
The system does not appear to correctly update the project settings when a user attempts to change them.

**Comment by chefsalim** [comment]
Not able to repro.  Possibly the "Update Connection" button at the bottom was not clicked?  It's a two step process - you need to click "Save Settings", and then click "Update Connection".  @eeyun 

Also FYI @apriofrost

**Comment by sfiggins** [comment]
I might be experiencing this problem. I followed the build-demo instructions but my build did not get published to Docker Hub. I don't see any errors related to this in the build log, but also don't see anything suggesting it tried. Ian Henry suggested the integration might not be running.

https://bldr.habitat.sh/#/pkgs/sfiggins/sample-node-app

[builder.log](https://github.com/habitat-sh/builder/files/2931855/builder.log)

**Comment by FutureWulf** [comment]
I am also running into this using Chrome 74.0.3729.169 and Mac OS 10.12.6.  Attempting to do part 2 of the tutorial.
