### ISSUE TITLE
Builder webhook - fix case where plan file is in a "habitat" folder

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#86]
@chefsalim commented on [Fri Dec 15 2017](https://github.com/habitat-sh/habitat/issues/4323)

This issue deals with one specific case - where there is no .bldr.toml file, and the plan.sh file for the repo is in a "habitat" folder.

Under these conditions, and file change that is not inside of the "habitat" folder will not trigger an automated Builder build.

The reason is that the default rule requires a changed file to fall under the plan path folder.

**Comment by nellshamrell** [comment]
@chefsalim is this still an issue that you are seeing?

**Comment by chefsalim** [comment]
This is still an issue - it's also something we've documented, so we could just let it be this way for now.
