### ISSUE TITLE
Disable rdep rebuilds on package uploads

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#883]
When uploading a package, builder will schedule a build group for the reverse dependencies of the package.  When doing base-plan refreshes the packages must be uploaded, and this will cause a "thundering herd" of builds, as each package will generate a new build group.  The current workaround is to take an outage which impacts our users ability to work. 

In order to do the refreshes without impacting our users, we should change the default behavior to not schedule builds on package upload.

**Comment by chefsalim** [comment]
Currently, we have a jobsrv feature flag in builder-api that will stop the build-on-upload, but it also stops checking for circular deps, as well as extending the jobsrv graph.  The desired behavior is to have a way to just turn off the builds on upload feature.

**Comment by smacfarlane** [comment]
Closed by #887
