### ISSUE TITLE
Allow Users to Depart Origin from GUI

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/builder#890]
### Describe the Enhancement:
As a user of builder I would like to be able to depart an origin that I'm not using. I would assume this should follow the same safety mechanics as the current ability to delete a user from an origin.

### Describe the Need:
Any user that spends time in the UI and doesn't want to memorize the API endpoint in order to depart an origin would likely appreciate this behavior. 

### Current Alternative
In order to depart an origin today, a user must know the route and use a CLI based client like curl in order to depart themselves from an origin.

### Can We Help You Implement This?:
We can implement this ourselves at some point if we'd like, the logic already exists, we just need some UI work to add a depart button next to a user's name when they're looking at the user management page.

**Comment by apriofrost** [comment]
Close this issue as it is duplicated with https://github.com/habitat-sh/builder/issues/1292
