### ISSUE TITLE
[feature] Increased visibility of failed builds

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#90]
@stevendanna commented on [Tue Jan 02 2018](https://github.com/habitat-sh/habitat/issues/4401)

For a large origin (such as core-plans), it would be helpful if there was a way to find out about failed bldr builds. Some possibilities include:

- Email notification for failed builds to a configurable notification list
- Slack notification for failed builds
- Some sort of "dashboard" view that would show any failing builds.

---

@eeyun commented on [Tue Jan 16 2018](https://github.com/habitat-sh/habitat/issues/4401#issuecomment-358061682)

Yeah this is another excellent one. This might roll up into #4402 but I think we'll track them separately since they have slightly different areas of concern! Thanks @stevendanna !

Aha! Link: https://chef.aha.io/features/APPDL-10

**Comment by eeyun** [comment]
So I believe we can now see failed builds but, i think this should roll into our notification system as well so I'm leaving a comment here to keep skynet from sending a robot back in time with the intention of erasing this issue.

**Comment by sajjaphani** [comment]
This isn't stale
