### ISSUE TITLE
PRs with multiple PackageTargets build each Target in serial

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#929]
### Scenario:
Merge a Pull Request  to a Plan that contains both `plan.sh` and `plan.ps1`

### Expected Result:
Since the two build groups are for separate PackageTargets, they should build concurrently.

### Actual Result:
The build for the first PackageTarget to be dispatched blocks the remaining PackageTargets until completion. 

From a merged pull request this morning that caused Concourse to be built. The Plan directory contains both a `plan.sh` and a `plan.ps1`
```
2019-02-11T19:28:23.616932+00:00  1179833494082109440  Queued       core/concourse
2019-02-11T19:28:23.584828+00:00  1179833493813665792  Dispatching  core/concourse
```
The job status remained in that state until  `1179833493813665792` transitioned to `Complete` at which point `1179833494082109440` immediately transitioned to `Dispatching`.

**Comment by chefsalim** [comment]
This has been fixed by recent PRs, and builds proceed in parallel now
