### ISSUE TITLE
Convert protobufs to use Prost

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#935]
In the habitat repo, the three places that use protobufs (supervisor, butterfly, launcher) have all been converted from the `protobuf` crate to [prost](https://crates.io/crates/prost).  For the sake of consistency, it'd be great to get Builder migrated to `prost` as well, so that all of our protobuf handling code is consistent across the entire project.

The [most recent conversion effort](https://github.com/habitat-sh/habitat/pull/6105) of the launcher crates to `prost` is probably the best one to follow as far as patterns.  We create a set of internal structs that mirror the protobuf structs and use those, with the generated protobuf structs only used at the edges.  Note that no generated code is stored in the repo.

Subtasks:
- [ ] Switch code generation to `prost`
- [ ] Update [plan files](https://github.com/habitat-sh/habitat/pull/6153) so that the builds don't break
- [ ] Revert [`rustfmt` workaround](https://github.com/habitat-sh/builder/pull/1016/commits/a2e3d3124eef4f3f5c7b0543eef9da4e02c0ff9b)

**Comment by chefsalim** [comment]
It's not clear we will migrate Builder to prost.  Instead, we'd like to move Builder completely off protobuf dependence entirely, and just leverage JSON internally like the external facing API.  The recent refactor work has greatly shrunk the Builder protobuf footprint already.
