### ISSUE TITLE
Take PackageTarget into account for the Fully Qualified Package Identifier 

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#940]
### Scenario:
When using automation to build a package for multiple PackageTargets (the habitat cli, supervisor and launcher for example),  it is possible for them to have the same fully qualified package identifier (FQPI):  
```
* core/hab/0.75.0/20190219200749 (x86_64-linux)
* core/hab/0.75.0/20190219200749 (x86_64-linux-kernel2)
```

When these packages are then uploaded to builder, only the first one is able to be uploaded because Builder expects the FQPI to be unique globally. This then requires you to rebuild the artifact that failed to upload.  

### Expected Result:
Since the packages are for two different PackageTargets and should never be install-able on the same system in regular use, I would expect them to both to be able to be uploaded and stored in Builder. 

### Actual Result:

```
» Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux-kernel2.hart
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux-kernel2.hart
✓ Uploaded core/hab-studio/0.75.0/20190219200210
```

```
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux.hart
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux.hart
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux.hart
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux.hart
↑ Uploading results/core-hab-studio-0.75.0-20190219200210-x86_64-linux.hart
✗✗✗
✗✗✗ Upload failed: We tried 5 times but could not upload core/hab-studio/0.75.0/20190219200210. Giving up.
✗✗✗
```

**Comment by christophermaier** [comment]
We hit this again [in the 0.78.0 release](https://github.com/habitat-sh/habitat/issues/6284#issuecomment-472009202).

**Comment by smacfarlane** [comment]
@chefsalim   I believe this has been resolved,   can we close this out?

**Comment by chefsalim** [comment]
Yes this is resolved - we can back out the curl upload in the release scripts now.
