### ISSUE TITLE
Package upload times out and reports failure

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#961]
### `hab` CLI version
Most recently encountered with 0.77.0, but has been present for multiple releases. 

### Scenario:
Uploading a large package, or possibly one one with many files, can sometimes return a failure but the package is present in Builder. 

### Steps to Reproduce:
Build a large package, `core-plans/rust` is a good example.  `core-plans/cuda` and `core-plans/mongodb` also can trigger this failure case.

### Expected Result:
The package uploads and the cli returns success

### Actual Result:
When uploading via the cli you will see the package upload, pause while it waits for response from builder,and then retry when a response isn't returned until the retry limit of 5. You can then visit the appropriate page for the package on https://bldr.habitat.sh and see the package. You are also able `hab pkg install $pkg_ident` in a fresh studio and install the package.  

I have also seen this occur in builder, presented as a failed build with `Failed post processing for core/rust, err=Retry(RetryError { message: "reached last try without condition match" })` in the build logs.

### Notes:
My suspicion is that the extraction of metadata takes longer than the timeout specified by the cli. Since the extraction appears to happen in it's own thread on builder, it can safely finish the process despite the cli reporting a failure.

**Comment by chefsalim** [comment]
The client fails with a 504 Gateway timeout, while on the server side we see a 499 Nginx failure. So it appears that the timeout is happening at the ELB.  But adjusting the ELB timeout doesn't seem to work either, so more investigation is needed.
