### ISSUE TITLE
Since Airlock has been removed, we no longer need KRANGSCHNAK

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#980]
These lines can be removed https://github.com/habitat-sh/builder/blob/master/.studiorc#L352-L357

**Comment by christophermaier** [comment]
![tenor-248966250](https://user-images.githubusercontent.com/207178/54542520-4c7ef980-4972-11e9-8d20-f92294f3a717.gif)

**Comment by chefsalim** [comment]
fixed!
