### ISSUE TITLE
Public Builder performance issues

### ISSUE THREAD

**Issue by bixu** [habitat-sh/builder#981]
As there doesn't seem to be a paid support option for Habitat Builder yet, I'm submitting this here. Not sure what other options exist.

### `hab` CLI version
From public Builder job logs:
```
api: Using HAB_BIN=/hab/pkgs/core/hab/0.78.0/20190313115951/bin/hab for installs, signing, and hashing
```

### Platform Details
Public Builder

### Scenario:
Verifying that our recent API changes are working requires that Builder generate an API artifact for our Staging environment Supervisor to consume. Builder slowness is preventing this.

### Steps to Reproduce:
Group ID for build: 1205013267986251776

### Expected Result:
Usually this build should take approx. 10 minutes.

### Actual Result:
It's been over 20 minutes since the job kicked off and dependency resolution isn't even complete.

**Comment by chefsalim** [comment]
This should now be resolved - please reopen if needed
